begin;
select no_plan();
create function pg_temp.fid(n integer) returns uuid language sql immutable as $$select ('66000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.studios(id,name) values(pg_temp.fid(1),'Payroll A'),(pg_temp.fid(2),'Payroll B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.fid(n),'authenticated','authenticated','payroll-'||n||'@test','{}','{}',now(),now() from generate_series(10,15)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.fid(n),'Payroll tester '||n,'payroll-'||n||'@test',case when n in (11,15) then 'employee' else 'admin' end,n<>13 from generate_series(10,15)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.fid(case when n=12 then 2 else 1 end),pg_temp.fid(n),case when n in (11,15) then 'employee' else 'admin' end,n<>14 from generate_series(10,15)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.fid(1),'UAH','2026-01-01',pg_temp.fid(10)),(pg_temp.fid(2),'UAH','2026-01-01',pg_temp.fid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.fid(20),pg_temp.fid(1),'Payroll bank','UAH',10000,pg_temp.fid(10));
create function pg_temp.cat(key text,studio integer default 1) returns uuid language sql as $$select id from public.finance_categories where studio_id=pg_temp.fid(studio) and default_key=key$$;
create function pg_temp.result(n integer) returns uuid language sql as $$select result_id from public.finance_planning_requests where studio_id=pg_temp.fid(1) and request_id=pg_temp.fid(n)$$;
create function pg_temp.schedule(n integer,patch jsonb default '{}') returns uuid language sql as $$
 select public.save_finance_schedule(pg_temp.fid(1),pg_temp.fid(n),jsonb_build_object('kind','payroll','employeeId',pg_temp.fid(11),'revision',0,'name','Employee salary','amount','1000','currency','UAH','categoryId',pg_temp.cat('salary'),'basis','gross','employeePayout','800','employeeDeductions','200','employerCostStatus','unknown','intervalMonths',1,'payoutDay',31,'paymentMonthOffset',1,'effectiveFrom','2026-01-01','commitment','agreed','certainty','fixed','reason','Agreement')||patch)$$;
create function pg_temp.generate(n integer,schedule integer default 100,first date default '2026-01-01',last date default '2026-02-01') returns uuid language sql as $$
 select public.generate_finance_obligations(pg_temp.fid(1),pg_temp.fid(n),pg_temp.result(schedule),first,last)$$;
create function pg_temp.item(component text,period date default '2026-01-01',schedule integer default 100) returns uuid language sql as $$
 select l.expected_item_id from public.finance_obligation_items l join public.finance_obligations o on o.id=l.obligation_id where o.schedule_id=pg_temp.result(schedule) and o.period_start=period and l.component=$1$$;
create function pg_temp.edit_item(n integer,item uuid,patch jsonb default '{}') returns uuid language sql as $$
 select public.save_finance_expected_item(pg_temp.fid(1),pg_temp.fid(n),jsonb_build_object('id',i.id,'version',i.version,'direction',i.direction,'amount',i.amount,'currency',i.currency,'categoryId',i.category_id,'description',i.description,'dueDate',i.due_date,'expectedDate',i.expected_payment_date,'commitment',i.commitment,'certainty',i.certainty,'established',i.is_established)||patch) from public.finance_expected_items i where i.id=item$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.fid(10)::text,true);
select public.finalize_finance_setup(pg_temp.fid(1));
select lives_ok($$select pg_temp.schedule(100)$$,'admin creates gross compensation');
select lives_ok($$select pg_temp.schedule(100)$$,'identical request retry');
select throws_like($$select pg_temp.schedule(100,'{"amount":"1001"}')$$,'%finance_request_conflict%','changed retry rejected');
select throws_like($$select pg_temp.schedule(101)$$,'%finance_employee_invalid%','duplicate active salary rejected');
select lives_ok($$select pg_temp.generate(110)$$,'payroll generation');
select lives_ok($$select pg_temp.generate(110)$$,'same request retry');
select lives_ok($$select pg_temp.generate(111)$$,'new request retry');
select is((select count(*) from public.finance_obligations),2::bigint,'one salary occurrence per employee/service month');
select is((select count(*) from public.finance_expected_items),4::bigint,'payout plus explicit remittances');
select is((select count(*) from public.finance_movements),0::bigint,'generation never creates actual cash');
select is((select employer_cost from public.finance_schedule_terms),null::numeric,'unknown employer costs remain null');
select is((select due_date from public.finance_expected_items where id=pg_temp.item('payout')),'2026-02-28'::date,'payday clamps to short following month');
select is((select period_end from public.finance_obligations where period_start='2026-01-01'),'2026-01-31'::date,'service month separate from payout');
select is((select count(*) from public.finance_payroll_calendar),2::bigint,'calendar projects payout only, not remittances');
select is((select count(*) from information_schema.columns where table_schema='public' and table_name='finance_payroll_calendar' and column_name like '%amount%'),0::bigint,'calendar surface has no amount columns');
select lives_ok($$select pg_temp.edit_item(120,pg_temp.item('payout'),'{"established":true,"expectedDate":"2026-03-10"}')$$,'explicit earning and forecast timing update');
select is((select payment_date from public.finance_payroll_calendar where expected_item_id=pg_temp.item('payout')),'2026-03-10'::date,'calendar follows expected cash date');
select throws_like($$select pg_temp.edit_item(121,pg_temp.item('payout'),'{"amount":"801"}')$$,'%finance_obligation_locked%','global editor cannot rewrite configured salary');
select throws_like($$select pg_temp.edit_item(121,pg_temp.item('payout'),'{"dueDate":"2026-04-01"}')$$,'%finance_obligation_locked%','contractual date immutable');
select throws_like($$select pg_temp.generate(122,100,'2026-01-01','2027-01-01')$$,'%finance_schedule_range%','generation batch bounded');
select throws_like($$select pg_temp.schedule(130,jsonb_build_object('id',pg_temp.result(100),'revision',1,'effectiveFrom','2026-02-01'))$$,'%finance_schedule_effective_date%','cannot rewrite historical or generated compensation');
select lives_ok($$select pg_temp.schedule(130,jsonb_build_object('id',pg_temp.result(100),'revision',1,'effectiveFrom','2027-01-01','amount','1200','employeePayout','900','employeeDeductions','300','employerCostStatus','estimated','employerCost','150'))$$,'future effective-dated salary change');
select is((select amount from public.finance_schedule_terms where revision=1),1000::numeric,'prior salary unchanged');
select is((select valid_through from public.finance_schedule_history where revision=1),'2026-12-31'::date,'history derives valid-to');
select lives_ok($$select pg_temp.generate(131,100,'2027-01-01','2027-01-01')$$,'new salary revision generates separately');
select is((select amount from public.finance_expected_items where id=pg_temp.item('payout','2027-01-01')),900::numeric,'new payout applied');
select is((select certainty from public.finance_expected_items where id=pg_temp.item('employer_cost','2027-01-01')),'estimated','estimated employer costs distinct');
select lives_ok($$select pg_temp.edit_item(132,pg_temp.item('employer_cost','2027-01-01'),'{"amount":"160","certainty":"fixed"}')$$,'estimate explicitly reconciled through audited expected editor');
select lives_ok($$select public.create_finance_employee_bonus(pg_temp.fid(1),pg_temp.fid(140),jsonb_build_object('employeeId',pg_temp.fid(11),'amount','75','currency','UAH','periodStart','2026-01-01','periodEnd','2026-01-31','dueDate','2026-02-10','description','Explicit bonus'))$$,'one-off employee bonus');
select lives_ok($$select public.create_finance_employee_bonus(pg_temp.fid(1),pg_temp.fid(140),jsonb_build_object('employeeId',pg_temp.fid(11),'amount','75','currency','UAH','periodStart','2026-01-01','periodEnd','2026-01-31','dueDate','2026-02-10','description','Explicit bonus'))$$,'bonus request retry idempotent');
select is((select count(*) from public.finance_schedule_terms),2::bigint,'bonus never changes salary rates');
select is((select count(*) from public.finance_obligations where kind='bonus'),1::bigint,'bonus separate occurrence');
select lives_ok($$select public.record_finance_expected_payment(pg_temp.fid(1),pg_temp.fid(150),pg_temp.item('payout'),jsonb_build_object('kind','outgoing','date','2026-02-28','amount','300','accountId',pg_temp.fid(20),'categoryId',pg_temp.cat('salary')),300)$$,'payroll reuses ledger + partial allocation');
select is((select payment_state from public.finance_expected_balances where id=pg_temp.item('payout')),'partial','partial payroll settlement');
select is((select outstanding_amount from public.finance_expected_balances where id=pg_temp.item('payout')),500::numeric,'only remaining earned salary outstanding');
select lives_ok($$select public.remove_studio_member(pg_temp.fid(11),'[]'::jsonb,true)$$,'existing Team removal works with compensation');
select is((select stopped_from from public.finance_schedules where id=pg_temp.result(100)),(date_trunc('month',now() at time zone 'Europe/Kyiv')+interval '1 month')::date,'removal stops subsequent service months');
select lives_ok($$select pg_temp.generate(160,100,'2027-02-01','2027-02-01')$$,'removed employee generation skips future');
select is((select count(*) from public.finance_obligations where schedule_id=pg_temp.result(100)),3::bigint,'created future and historical obligations retained');
select lives_ok($$select pg_temp.generate(161,100,'2026-03-01','2026-03-01')$$,'previously earned ungenerated month remains available');
select lives_ok($$select public.restore_studio_member(pg_temp.fid(11))$$,'restore access');
select lives_ok($$select pg_temp.generate(162,100,'2027-02-01','2027-02-01')$$,'restore does not restart old salary');
select is((select count(*) from public.finance_obligations where schedule_id=pg_temp.result(100)),4::bigint,'no silent salary restart');
select throws_like($$select pg_temp.schedule(163,'{"effectiveFrom":"2027-01-01"}')$$,'%finance_schedule_effective_date%','rehiring cannot duplicate already-created future payroll');
select lives_ok($$select pg_temp.schedule(170,jsonb_build_object('employeeId',pg_temp.fid(10),'basis','net','employeePayout','1000','employeeDeductions','','employerCost','0','employerCostStatus','fixed'))$$,'admin own compensation and explicit zero cost');
select lives_ok($$select pg_temp.generate(171,170,'2026-01-01','2026-01-01')$$,'generate admin own salary');
select is((select count(*) from public.finance_payroll_calendar where employee_id=pg_temp.fid(10)),1::bigint,'viewer own payroll reminder retained');
select throws_like($$select pg_temp.schedule(172,jsonb_build_object('employeeId',pg_temp.fid(15),'employeePayout','900'))$$,'%check constraint%','gross agreement must equal payout plus deductions');
select throws_like($$select pg_temp.schedule(172,jsonb_build_object('employeeId',pg_temp.fid(15),'employeeDeductions',''))$$,'%check constraint%','gross does not silently assume zero deductions');
select throws_like($$select pg_temp.schedule(172,jsonb_build_object('employeeId',pg_temp.fid(15),'employerCostStatus','fixed'))$$,'%check constraint%','known employer cost requires explicit amount');
select throws_like($$select pg_temp.schedule(172,jsonb_build_object('employeeId',pg_temp.fid(15),'employeePayout','800.001'))$$,'%finance_amount_invalid%','minor-unit precision');
select throws_like($$select pg_temp.schedule(172,jsonb_build_object('employeeId',pg_temp.fid(12)))$$,'%finance_employee_invalid%','foreign employee denied');
select throws_like($$select pg_temp.schedule(172,jsonb_build_object('employeeId',pg_temp.fid(15),'categoryId',pg_temp.cat('salary',2)))$$,'%finance_category_invalid%','foreign category denied');

create function pg_temp.recurring(n integer,patch jsonb default '{}') returns uuid language sql as $$select pg_temp.schedule(n,jsonb_build_object('kind','recurring','employeeId','','name','Studio rent','basis','','employeePayout','','employeeDeductions','','categoryId',pg_temp.cat('rent'),'intervalMonths',3,'paymentMonthOffset',0,'certainty','estimated','commitment','tentative')||patch)$$;
select lives_ok($$select pg_temp.recurring(200)$$,'quarterly estimated studio obligation');
select lives_ok($$select pg_temp.generate(201,200,'2026-01-01','2026-12-01')$$,'quarterly recurrence');
select lives_ok($$select pg_temp.generate(202,200,'2026-01-01','2026-12-01')$$,'quarterly idempotence across requests');
select is((select count(*) from public.finance_obligations where schedule_id=pg_temp.result(200)),4::bigint,'four stable quarterly occurrences');
select is((select certainty from public.finance_expected_items where id=pg_temp.item('recurring','2026-01-01',200)),'estimated','estimate preserved');
select is((select outstanding_amount from public.finance_expected_balances where id=pg_temp.item('recurring','2026-01-01',200)),0::numeric,'tentative recurrence is planning only');
select throws_like($$select pg_temp.recurring(203,jsonb_build_object('id',pg_temp.result(200),'revision',1,'effectiveFrom','2026-11-01'))$$,'%finance_schedule_effective_date%','revision cannot overlap generated service period');
select lives_ok($$select pg_temp.recurring(203,jsonb_build_object('id',pg_temp.result(200),'revision',1,'effectiveFrom','2027-01-01','effectiveThrough','2027-03-31','intervalMonths',1,'amount','1200','certainty','fixed','commitment','agreed'))$$,'future-only recurrence revision');
select lives_ok($$select pg_temp.generate(204,200,'2027-01-01','2027-04-01')$$,'new recurrence respects end date');
select is((select count(*) from public.finance_obligations where schedule_id=pg_temp.result(200)),7::bigint,'new monthly cadence does not rewrite historical quarters');
select is((select amount from public.finance_expected_items where id=pg_temp.item('recurring','2026-01-01',200)),1000::numeric,'historical amount intact');
select lives_ok($$select pg_temp.recurring(210,jsonb_build_object('categoryId',pg_temp.cat('owner_distribution'),'name','Owner distribution','certainty','fixed','commitment','agreed','intervalMonths',1))$$,'owner withdrawal schedule');
select lives_ok($$select pg_temp.generate(211,210,'2026-01-01','2026-01-01')$$,'owner withdrawal expected item');
select lives_ok($$select public.record_finance_expected_payment(pg_temp.fid(1),pg_temp.fid(212),pg_temp.item('recurring','2026-01-01',210),jsonb_build_object('kind','owner_withdrawal','date','2026-02-28','amount','250','accountId',pg_temp.fid(20),'categoryId',pg_temp.cat('owner_distribution')),250)$$,'owner distribution uses existing partial settlement');
select is((select nature from public.finance_movements where request_id=pg_temp.fid(212)),'owner_distribution','owner actual movement non-operating');
select is((select settled_amount from public.finance_expected_balances where id=pg_temp.item('recurring','2026-01-01',210)),250::numeric,'owner obligation reconciles');
select throws_like($$select public.allocate_finance_payment(pg_temp.fid(1),pg_temp.fid(213),pg_temp.item('payout'),(select id from public.finance_movements where request_id=pg_temp.fid(212)),100)$$,'%finance_allocation_incompatible%','owner distribution cannot settle operating salary');
select public.reverse_finance_movement(pg_temp.fid(1),pg_temp.fid(214),(select id from public.finance_movements where request_id=pg_temp.fid(212)),'2026-03-01','Correction');
select is((select settled_amount from public.finance_expected_balances where id=pg_temp.item('recurring','2026-01-01',210)),0::numeric,'owner reversal releases allocation');

select lives_ok($$select public.stop_finance_schedule(pg_temp.fid(1),pg_temp.fid(220),pg_temp.result(200),'2028-01-01')$$,'explicit future stop');
select lives_ok($$select pg_temp.generate(221,200,'2028-01-01','2028-01-01')$$,'stopped recurring schedule does not generate');
select is((select count(*) from public.finance_obligations where schedule_id=pg_temp.result(200)),7::bigint,'stop preserves all existing recurring history');
select lives_ok($$select pg_temp.edit_item(222,pg_temp.item('recurring','2026-01-01',210),'{"commitment":"cancelled"}')$$,'explicit cancellation preserves occurrence');
select lives_ok($$select pg_temp.generate(223,210,'2026-01-01','2026-01-01')$$,'cancelled occurrence skipped on retry');
select is((select count(*) from public.finance_obligations where schedule_id=pg_temp.result(210)),1::bigint,'cancelled identity cannot duplicate');
select lives_ok($$select pg_temp.schedule(224,jsonb_build_object('employeeId',pg_temp.fid(15)))$$,'second employee salary');
reset role;
update public.profiles set is_active=false where id=pg_temp.fid(15);
select is((select stopped_from from public.finance_schedules where employee_id=pg_temp.fid(15)),(date_trunc('month',now() at time zone 'Europe/Kyiv')+interval '1 month')::date,'profile deactivation stops payroll');
update public.profiles set is_active=true where id=pg_temp.fid(15);
set local role authenticated;
select is((select stopped_from from public.finance_schedules where employee_id=pg_temp.fid(15)),(date_trunc('month',now() at time zone 'Europe/Kyiv')+interval '1 month')::date,'profile restoration does not silently restart payroll');

select throws_like($$insert into public.finance_schedules(studio_id,kind,created_by) values(pg_temp.fid(1),'recurring',pg_temp.fid(10))$$,'%permission denied%','no direct schedule writes');
select throws_like($$delete from public.finance_schedule_terms$$,'%permission denied%','no direct salary history deletion');
select throws_like($$select public.generate_finance_obligations(pg_temp.fid(2),pg_temp.fid(300),pg_temp.result(100),'2026-01-01','2026-01-01')$$,'%finance_admin_required%','cross-studio RPC denial');
select set_config('request.jwt.claim.sub',pg_temp.fid(11)::text,true);
select is((select count(*) from public.finance_schedules),0::bigint,'employee cannot see schedules');
select is((select count(*) from public.finance_schedule_history),0::bigint,'employee cannot see compensation revisions');
select is((select count(*) from public.finance_obligations),0::bigint,'employee cannot see own payroll');
select is((select count(*) from public.finance_obligation_items),0::bigint,'employee cannot see amounts via links');
select is((select count(*) from public.finance_payroll_calendar),0::bigint,'employee calendar contains no compensation');
select is((select count(*) from public.finance_expected_items),0::bigint,'employee cannot read expected salaries');
select is((select count(*) from public.finance_planning_requests),0::bigint,'employee cannot read private audit payloads');
select throws_like($$select pg_temp.schedule(300)$$,'%finance_admin_required%','employee compensation write denied');
select throws_like($$select pg_temp.generate(300)$$,'%finance_admin_required%','employee generation denied');
select throws_like($$select public.stop_finance_schedule(pg_temp.fid(1),pg_temp.fid(300),pg_temp.fid(100),'2027-01-01')$$,'%finance_admin_required%','employee stop denied');
select throws_like($$select public.create_finance_employee_bonus(pg_temp.fid(1),pg_temp.fid(300),'{}')$$,'%finance_admin_required%','employee bonus denied');
select set_config('request.jwt.claim.sub',pg_temp.fid(12)::text,true);
select is((select count(*) from public.finance_schedules),0::bigint,'foreign admin sees no schedules');
select is((select count(*) from public.finance_payroll_calendar),0::bigint,'foreign calendar cannot see salaries');
select set_config('request.jwt.claim.sub',pg_temp.fid(13)::text,true);
select is((select count(*) from public.finance_schedule_terms),0::bigint,'inactive profile admin denied');
select set_config('request.jwt.claim.sub',pg_temp.fid(14)::text,true);
select is((select count(*) from public.finance_schedule_terms),0::bigint,'inactive membership admin denied');
set local role anon;
select throws_like($$select * from public.finance_schedules$$,'%permission denied%','anonymous cannot read');
select throws_like($$select public.save_finance_schedule(pg_temp.fid(1),pg_temp.fid(300),'{}')$$,'%permission denied%','anonymous RPC denied');
reset role;
select is((select count(*) from public.notifications where studio_id=pg_temp.fid(1)),0::bigint,'payroll never emits employee notifications');
select throws_like($$update public.finance_schedule_terms set amount=999 where revision=1$$,'%finance_history_immutable%','history immutable even privileged direct edits');
select * from finish();
rollback;
