begin;
select no_plan();
create function pg_temp.fid(n integer) returns uuid language sql immutable as $$select ('67000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.today() returns date language sql stable as $$select (now() at time zone 'Europe/Kyiv')::date$$;
create function pg_temp.month() returns date language sql stable as $$select date_trunc('month',pg_temp.today())::date$$;
insert into public.studios(id,name) values(pg_temp.fid(1),'Forecast A'),(pg_temp.fid(2),'Forecast B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.fid(n),'authenticated','authenticated','forecast-'||n||'@test','{}','{}',now(),now() from generate_series(10,14)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.fid(n),'Forecast tester','forecast-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,14)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.fid(case when n=12 then 2 else 1 end),pg_temp.fid(n),case when n=11 then 'employee' else 'admin' end,n<>14 from generate_series(10,14)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values
(pg_temp.fid(1),'UAH',(pg_temp.month()-interval '1 month')::date,pg_temp.fid(10)),(pg_temp.fid(2),'UAH',pg_temp.month(),pg_temp.fid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values
(pg_temp.fid(20),pg_temp.fid(1),'Bank','UAH',1000,pg_temp.fid(10)),(pg_temp.fid(21),pg_temp.fid(1),'Dollars','USD',100,pg_temp.fid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,created_by,status) values(pg_temp.fid(30),pg_temp.fid(1),'Forecast project',100,pg_temp.month(),pg_temp.fid(10),'active');
create function pg_temp.cat(key text,studio integer default 1) returns uuid language sql as $$select id from public.finance_categories where studio_id=pg_temp.fid(studio) and default_key=key$$;
create function pg_temp.result(n integer) returns uuid language sql as $$select result_id from public.finance_planning_requests where studio_id=pg_temp.fid(1) and request_id=pg_temp.fid(n)$$;
create function pg_temp.fx(rate text default '40') returns jsonb language sql as $$select jsonb_build_array(jsonb_build_object('currency','USD','rate',rate,'source','manual','effectiveDate',pg_temp.today()))$$;
create function pg_temp.report(scenario text default 'confirmed',fx jsonb default '[]',horizon text default '6') returns jsonb language sql as $$select public.calculate_finance_forecast(pg_temp.fid(1),horizon,scenario,fx)$$;
create function pg_temp.budget(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_budget(pg_temp.fid(1),pg_temp.fid(n),jsonb_build_object('categoryId',pg_temp.cat('project_payments'),'year',extract(year from pg_temp.today()),'revision',0,'months',to_jsonb(array_fill(100000,ARRAY[12])),'reason','Approved annual plan')||patch)$$;
create function pg_temp.expected(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_expected_item(pg_temp.fid(1),pg_temp.fid(n),jsonb_build_object('direction','incoming','amount','100000','currency','UAH','categoryId',pg_temp.cat('project_payments'),'description','Contract receipt','dueDate',pg_temp.today(),'expectedDate',pg_temp.today(),'commitment','agreed','certainty','fixed')||patch)$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.fid(10)::text,true);
select public.finalize_finance_setup(pg_temp.fid(1));
select lives_ok($$select pg_temp.budget(100)$$,'admin approves annual budget');
select lives_ok($$select pg_temp.budget(100)$$,'budget retry idempotent');
select is((select count(*) from public.finance_budget_revisions),1::bigint,'one immutable revision');
select is((select count(*) from public.finance_expected_items),0::bigint,'budget never creates expected cash');
select is((select count(*) from public.finance_movements),0::bigint,'budget never creates actual cash');
select throws_like($$select pg_temp.budget(101)$$,'%finance_version_conflict%','stale budget rejected');
select lives_ok($$select pg_temp.budget(101,'{"revision":1,"reason":"Explicit revision"}')$$,'deliberate revision');
select is((select count(*) from public.finance_budget_revisions),2::bigint,'previous budget retained');
select is((select revision from public.finance_current_budget),2,'latest revision is baseline');
select throws_like($$select pg_temp.budget(102,'{"revision":2,"months":[1,2]}')$$,'%finance_amount_invalid%','exactly 12 months');
select throws_like($$select pg_temp.budget(102,jsonb_build_object('revision',2,'months',to_jsonb(array_fill(1.001,ARRAY[12]))))$$,'%finance_amount_invalid%','budget exact reporting currency precision');
select throws_like($$select pg_temp.budget(102,jsonb_build_object('revision',2,'months',to_jsonb(array_fill(-1,ARRAY[12]))))$$,'%finance_amount_invalid%','negative budget denied');
select throws_like($$select pg_temp.budget(102,jsonb_build_object('categoryId',pg_temp.cat('project_payments',2)))$$,'%finance_category_invalid%','foreign category denied');
select is((pg_temp.report()->'months'->0->>'remaining')::numeric,0::numeric,'budget is never a forecast source');
select is((pg_temp.report()->>'cashIncomplete')::boolean,true,'foreign cash without FX incomplete');
select is((pg_temp.report('confirmed',pg_temp.fx())->>'cashBase')::numeric,5000::numeric,'current cash explicitly valued at assumed FX');
select pg_temp.expected(200);
select public.record_finance_expected_payment(pg_temp.fid(1),pg_temp.fid(201),pg_temp.result(200),jsonb_build_object('kind','incoming','date',pg_temp.today(),'amount','40000','accountId',pg_temp.fid(20),'categoryId',pg_temp.cat('project_payments')),40000);
select is((pg_temp.report()->'items'->0->>'amount')::numeric,60000::numeric,'100000 partially settled by 40000 forecasts only 60000');
select is((pg_temp.report()->'comparisons'->0->>'actual')::numeric,40000::numeric,'actual from authoritative cash');
select is((pg_temp.report()->'comparisons'->0->>'full_period')::numeric,100000::numeric,'actual + remaining, not original expected plus actual');
select pg_temp.expected(202,jsonb_build_object('id',pg_temp.result(200),'version',1,'amount','75000'));
select is((pg_temp.report()->'comparisons'->0->>'full_period')::numeric,75000::numeric,'40000 actual + 35000 remaining = 75000, not 115000');
select is((pg_temp.report()->'comparisons'->0->>'budget')::numeric,100000::numeric,'budget unchanged by actuals and expectations');
select is((pg_temp.report('confirmed',pg_temp.fx())->'months'->0->>'closing')::numeric,80000::numeric,'cash base already includes actual, adds remaining only');
select pg_temp.expected(203,'{"amount":"100","commitment":"tentative","description":"Discretionary"}');
select is(jsonb_array_length(pg_temp.report()->'items'),1,'confirmed excludes tentative');
select is(jsonb_array_length(pg_temp.report('planned')->'items'),2,'including planned includes tentative');
select pg_temp.expected(204,'{"amount":"50","certainty":"estimated"}');
select is(jsonb_array_length(pg_temp.report()->'items'),2,'committed estimates included');
select pg_temp.expected(205,'{"amount":"9","commitment":"cancelled"}');
select is(jsonb_array_length(pg_temp.report('planned')->'items'),3,'cancelled excluded from both scenarios');
select pg_temp.expected(206,jsonb_build_object('direction','outgoing','categoryId',pg_temp.cat('rent'),'amount','20','dueDate',pg_temp.today()-1,'expectedDate',''));
select is((select i->>'date' from jsonb_array_elements(pg_temp.report()->'items') i where i->>'id'=pg_temp.result(206)::text),pg_temp.today()::text,'overdue outgoing immediate exposure');
select is((select i->>'dueDate' from jsonb_array_elements(pg_temp.report()->'items') i where i->>'id'=pg_temp.result(206)::text),(pg_temp.today()-1)::text,'due date preserved');
select pg_temp.expected(207,jsonb_build_object('direction','outgoing','categoryId',pg_temp.cat('rent'),'amount','21','dueDate',pg_temp.today()-1,'expectedDate',pg_temp.today()+5));
select is((select i->>'date' from jsonb_array_elements(pg_temp.report()->'items') i where i->>'id'=pg_temp.result(207)::text),(pg_temp.today()+5)::text,'revised outgoing date overrides overdue due date');
select pg_temp.expected(208,'{"amount":"77","dueDate":"","expectedDate":""}');
select is((select i->>'date' from jsonb_array_elements(pg_temp.report()->'items') i where i->>'id'=pg_temp.result(208)::text),null::text,'undated incoming never invented');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.report()->'issues') i where i->>'id'=pg_temp.result(208)::text and i->>'reason'='undated'),'undated incoming visible in attention');
select pg_temp.expected(209,jsonb_build_object('amount','10','dueDate',pg_temp.today()-1,'expectedDate',''));
select ok(exists(select 1 from jsonb_array_elements(pg_temp.report()->'issues') i where i->>'id'=pg_temp.result(209)::text and i->>'reason'='stale_incoming'),'past incoming needs a revised date');
select pg_temp.expected(210,'{"direction":"outgoing","amount":"11","dueDate":"","expectedDate":""}'::jsonb||jsonb_build_object('categoryId',pg_temp.cat('rent')));
select is((select i->>'date' from jsonb_array_elements(pg_temp.report()->'items') i where i->>'id'=pg_temp.result(210)::text),null::text,'truly undated outgoing not assigned an invented date');
select pg_temp.expected(211,jsonb_build_object('direction','outgoing','categoryId',pg_temp.cat('owner_distribution'),'amount','200'));
select is((select i->>'nature' from jsonb_array_elements(pg_temp.report()->'items') i where i->>'id'=pg_temp.result(211)::text),'owner_distribution','owner withdrawals forecast non-operating');
select pg_temp.expected(212,'{"currency":"USD","amount":"100"}');
select public.record_finance_expected_payment(pg_temp.fid(1),pg_temp.fid(213),pg_temp.result(212),jsonb_build_object('kind','incoming','date',pg_temp.today(),'amount','40','accountId',pg_temp.fid(21),'categoryId',pg_temp.cat('project_payments'),'fx',jsonb_build_object('rate','39','source','manual','effectiveDate',pg_temp.today())),40);
select is((select (i->>'reportingAmount')::numeric from jsonb_array_elements(pg_temp.report('confirmed',pg_temp.fx())->'items') i where i->>'id'=pg_temp.result(212)::text),2400::numeric,'remaining USD uses assumed rate, not historical rate');
select is((select (i->>'actual')::numeric from jsonb_array_elements(pg_temp.report('confirmed',pg_temp.fx('50'))->'comparisons') i where i->>'category_id'=pg_temp.cat('project_payments')::text and i->>'month'=pg_temp.month()::text),41560::numeric,'historical 40 USD keeps rate 39 when forecast rate changes');
select throws_like($$select pg_temp.report('confirmed',pg_temp.fx('0'))$$,'%finance_fx_invalid%','zero FX denied');
select throws_like($$select pg_temp.report('confirmed',pg_temp.fx()||pg_temp.fx())$$,'%finance_fx_invalid%','duplicate FX denied');
select throws_like($$select pg_temp.report('confirmed',jsonb_build_array(jsonb_build_object('currency','USD','rate','40','source','nbu','effectiveDate',pg_temp.today()-1)))$$,'%finance_fx_invalid%','stale assumptions denied');
select is(jsonb_array_length(pg_temp.report('confirmed','[]','3')->'months'),3,'3 month horizon');
select is(jsonb_array_length(pg_temp.report('confirmed','[]','6')->'months'),6,'default 6 month horizon');
select is(jsonb_array_length(pg_temp.report('confirmed','[]','12')->'months'),12,'12 month horizon crosses year');
select is((pg_temp.report('confirmed','[]','year')->>'through'),make_date(extract(year from pg_temp.today())::integer,12,31)::text,'year end horizon');
-- All sources enter exactly once via existing expected items.
select public.save_finance_schedule(pg_temp.fid(1),pg_temp.fid(300),jsonb_build_object('kind','payroll','employeeId',pg_temp.fid(11),'revision',0,'name','Payroll','amount','1000','currency','UAH','categoryId',pg_temp.cat('salary'),'basis','net','employeePayout','1000','employeeDeductions','','employerCostStatus','unknown','intervalMonths',1,'payoutDay',31,'paymentMonthOffset',0,'effectiveFrom',pg_temp.month(),'commitment','agreed','certainty','fixed','reason','Agreement'));
select public.generate_finance_obligations(pg_temp.fid(1),pg_temp.fid(301),pg_temp.result(300),pg_temp.month(),pg_temp.month());
select public.generate_finance_obligations(pg_temp.fid(1),pg_temp.fid(302),pg_temp.result(300),pg_temp.month(),pg_temp.month());
select is((select count(*) from jsonb_array_elements(pg_temp.report()->'items') i where i->>'obligationKind'='payroll'),1::bigint,'payroll occurrence not re-expanded or duplicated');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.report()->'issues') i where i->>'reason'='unknown_employer_cost'),'unknown employer costs stay incomplete');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.report()->'issues') i where i->>'reason'='ungenerated_period'),'missing payroll horizon explicitly flagged');
select public.save_finance_schedule(pg_temp.fid(1),pg_temp.fid(303),jsonb_build_object('kind','recurring','revision',0,'name','Recurring rent','amount','100','currency','UAH','categoryId',pg_temp.cat('rent'),'intervalMonths',1,'payoutDay',31,'paymentMonthOffset',0,'effectiveFrom',pg_temp.month(),'commitment','agreed','certainty','estimated','reason','Agreement'));
select public.generate_finance_obligations(pg_temp.fid(1),pg_temp.fid(304),pg_temp.result(303),pg_temp.month(),pg_temp.month());
select public.generate_finance_obligations(pg_temp.fid(1),pg_temp.fid(305),pg_temp.result(303),pg_temp.month(),pg_temp.month());
select is((select count(*) from jsonb_array_elements(pg_temp.report()->'items') i where i->>'obligationKind'='recurring'),1::bigint,'recurring occurrence contributes exactly once');
select public.save_finance_project_terms(pg_temp.fid(1),pg_temp.fid(310),pg_temp.fid(30),'{"stream":"design","revision":0,"mode":"design","amount":"500","currency":"UAH","reason":"Contract"}');
select public.save_finance_project_item(pg_temp.fid(1),pg_temp.fid(311),pg_temp.fid(30),jsonb_build_object('stream','design','item',jsonb_build_object('direction','incoming','amount','100','currency','UAH','categoryId',pg_temp.cat('project_payments'),'expectedDate',pg_temp.today(),'commitment','agreed','certainty','fixed')));
select public.save_finance_project_item(pg_temp.fid(1),pg_temp.fid(312),pg_temp.fid(30),jsonb_build_object('stream','contractor_bonus','item',jsonb_build_object('direction','incoming','amount','25','currency','UAH','categoryId',pg_temp.cat('contractor_bonus'),'expectedDate',pg_temp.today(),'commitment','tentative','certainty','estimated')));
select is((select count(*) from jsonb_array_elements(pg_temp.report()->'items') i where i->>'stream'='design'),1::bigint,'project receipts use same expected item');
select is((select count(*) from jsonb_array_elements(pg_temp.report('planned')->'items') i where i->>'stream'='contractor_bonus'),1::bigint,'planned contractor bonus included');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.report()->'issues') i where i->>'reason'='unscheduled_project'),'unscheduled contract visible without invented date');
select public.save_finance_project_terms(pg_temp.fid(1),pg_temp.fid(313),pg_temp.fid(30),jsonb_build_object('stream','supervision','revision',0,'mode','monthly','amount','50','currency','UAH','effectiveFrom',pg_temp.month(),'reason','Monthly supervision'));
select public.generate_finance_supervision_months(pg_temp.fid(1),pg_temp.fid(314),pg_temp.fid(30),pg_temp.month(),pg_temp.month());
select is((select count(*) from jsonb_array_elements(pg_temp.report()->'items') i where i->>'stream'='supervision'),1::bigint,'supervision generated item included once');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.report()->'issues') i where i->>'reason'='ungenerated_supervision'),'missing supervision months visible');
-- Immutable snapshots preserve old values after expected/budget/FX edits.
select public.save_finance_forecast_snapshot(pg_temp.fid(1),pg_temp.fid(400),'Month close','6','confirmed',pg_temp.fx());
select lives_ok($$select public.save_finance_forecast_snapshot(pg_temp.fid(1),pg_temp.fid(400),'Month close','6','confirmed',pg_temp.fx())$$,'snapshot retry idempotent');
select is((select count(*) from public.finance_forecast_snapshots),1::bigint,'one saved forecast');
select ok(not exists(select 1 from public.finance_forecast_snapshots s,jsonb_array_elements(s.forecast->'comparisons') c where c ? 'actual' or c ? 'full_period'),'snapshot does not duplicate actuals');
select pg_temp.expected(401,jsonb_build_object('id',pg_temp.result(200),'version',2,'amount','76000'));
select pg_temp.budget(402,jsonb_build_object('revision',2,'months',to_jsonb(array_fill(123,ARRAY[12]))));
select is((select (i->>'amount')::numeric from public.finance_forecast_snapshots s,jsonb_array_elements(s.forecast->'items') i where i->>'id'=pg_temp.result(200)::text),35000::numeric,'saved expected amount stable after edit');
select is((select i->>'rate' from public.finance_forecast_snapshots s,jsonb_array_elements(s.forecast->'fx') i where i->>'currency'='USD'),'40','saved FX stays fixed');
select is((select (i->>'budget')::numeric from public.finance_forecast_snapshots s,jsonb_array_elements(s.forecast->'comparisons') i where i->>'category_id'=pg_temp.cat('project_payments')::text limit 1),100000::numeric,'saved budget baseline stable');
select is(jsonb_array_length(public.compare_finance_forecast_snapshot(pg_temp.fid(1),pg_temp.result(400))),6,'snapshot compares against live actuals');
-- Refunds/reversals stay signed within the original income classification.
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(410),jsonb_build_object('kind','refund','date',pg_temp.today(),'amount','1000','accountId',pg_temp.fid(20),'relatedMovementId',(select id from public.finance_movements where request_id=pg_temp.fid(201))));
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1) and category_id=pg_temp.cat('project_payments')),40560::numeric,'refund reduces historical income actual instead of inventing expense');
select public.reverse_finance_movement(pg_temp.fid(1),pg_temp.fid(411),(select id from public.finance_movements where request_id=pg_temp.fid(410)),pg_temp.today(),'Refund recorded in error');
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1) and category_id=pg_temp.cat('project_payments')),41560::numeric,'reversed refund restores original category actual');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(412),jsonb_build_object('kind','transfer','category','Transfer','date',pg_temp.today(),'amount','10','accountId',pg_temp.fid(21),'destinationId',pg_temp.fid(20),'receivedAmount','390','fee','1','fx',jsonb_build_object('rate','40','source','manual','effectiveDate',pg_temp.today())));
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1) and category_id is null),40::numeric,'transfer fee alone enters actual expenses; FX principal difference is not operating');
select public.reverse_finance_movement(pg_temp.fid(1),pg_temp.fid(413),(select id from public.finance_movements where request_id=pg_temp.fid(412)),pg_temp.today(),'Incorrect transfer');
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1) and category_id is null),0::numeric,'reversed fee cancels exactly');
select lives_ok($$select pg_temp.budget(414,jsonb_build_object('categoryId',pg_temp.cat('rent'),'months',to_jsonb(array_fill(80000,ARRAY[12]))))$$,'expense budget shares existing category direction');
select is((select i->>'direction' from jsonb_array_elements(pg_temp.report()->'comparisons') i where i->>'category_id'=pg_temp.cat('rent')::text limit 1),'outgoing','expense budget remains outgoing');
-- Correction semantics and access boundaries.
select throws_like($$update public.finance_budget_revisions set reason='rewrite'$$,'%permission denied%','no direct budget updates');
select throws_like($$delete from public.finance_forecast_snapshots$$,'%permission denied%','no direct snapshot deletion');
select throws_like($$insert into public.finance_forecast_snapshots(studio_id,name,forecast,created_by) values(pg_temp.fid(1),'Forged','{}',pg_temp.fid(10))$$,'%permission denied%','snapshot result cannot be supplied by caller');
select throws_like($$select public.calculate_finance_forecast(pg_temp.fid(2))$$,'%finance_admin_required%','foreign studio forecast denied');
select set_config('request.jwt.claim.sub',pg_temp.fid(11)::text,true);
select is((select count(*) from public.finance_budget_revisions),0::bigint,'employee budget read denied');
select is((select count(*) from public.finance_current_budget),0::bigint,'budget view respects RLS');
select is((select count(*) from public.finance_forecast_snapshots),0::bigint,'employee snapshot read denied');
select is((select count(*) from public.finance_planning_actuals),0::bigint,'actuals view respects RLS');
select throws_like($$select pg_temp.report()$$,'%finance_admin_required%','employee forecast RPC denied');
select throws_like($$select pg_temp.budget(500)$$,'%finance_admin_required%','employee budget RPC denied');
select throws_like($$select public.save_finance_forecast_snapshot(pg_temp.fid(1),pg_temp.fid(500),'x','6','confirmed','[]')$$,'%finance_admin_required%','employee snapshot write denied');
select throws_like($$select public.compare_finance_forecast_snapshot(pg_temp.fid(1),pg_temp.fid(400))$$,'%finance_admin_required%','employee snapshot comparison denied');
select set_config('request.jwt.claim.sub',pg_temp.fid(12)::text,true);
select is((select count(*) from public.finance_budget_revisions),0::bigint,'foreign admin no budget rows');
select is((select count(*) from public.finance_forecast_snapshots),0::bigint,'foreign admin no snapshots');
select set_config('request.jwt.claim.sub',pg_temp.fid(13)::text,true);
select throws_like($$select pg_temp.report()$$,'%finance_admin_required%','inactive profile denied');
select set_config('request.jwt.claim.sub',pg_temp.fid(14)::text,true);
select throws_like($$select pg_temp.report()$$,'%finance_admin_required%','inactive membership denied');
set local role anon;
select throws_like($$select * from public.finance_budget_revisions$$,'%permission denied%','anonymous budget denied');
select throws_like($$select public.calculate_finance_forecast(pg_temp.fid(1))$$,'%permission denied%','anonymous forecast denied');
reset role;
select throws_like($$update public.finance_budget_revisions set reason='rewrite'$$,'%finance_history_immutable%','budget history immutable even privileged');
select throws_like($$update public.finance_forecast_snapshots set forecast='{}'$$,'%finance_history_immutable%','saved assumptions immutable even privileged');
select * from finish();
rollback;
