begin;
select no_plan();
create function pg_temp.tid(n integer) returns uuid language sql immutable as $$select ('79000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.studios(id,name) values(pg_temp.tid(1),'Trips A'),(pg_temp.tid(2),'Trips B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.tid(n),'authenticated','authenticated','trips-'||n||'@test','{}','{}',now(),now() from generate_series(10,14)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.tid(n),'Traveler '||n,'trips-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,14)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.tid(case when n=12 then 2 else 1 end),pg_temp.tid(n),case when n=11 then 'employee' else 'admin' end,n<>14 from generate_series(10,14)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.tid(1),'UAH','2026-09-01',pg_temp.tid(10));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.tid(20),pg_temp.tid(1),'Bank','UAH',0,pg_temp.tid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,status,created_by) values(pg_temp.tid(30),pg_temp.tid(1),'Project',100,'2026-09-01','active',pg_temp.tid(10)),(pg_temp.tid(31),pg_temp.tid(2),'Foreign',100,'2026-09-01','active',pg_temp.tid(12));
create function pg_temp.result(n integer) returns uuid language sql as $$select result_id from public.finance_planning_requests where studio_id=pg_temp.tid(1) and request_id=pg_temp.tid(n)$$;
create function pg_temp.trip(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_trip(pg_temp.tid(1),pg_temp.tid(n),jsonb_build_object('title','Warsaw','destination','Warsaw','startsOn','2026-09-12','endsOn','2026-09-15','status','planned','travelers',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11)))||patch)$$;
create function pg_temp.entry(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.record_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(n),pg_temp.result(100),jsonb_build_object('kind','expense','expenseType','meals','amount','100','currency','UAH','date','2026-09-12','employeeId',pg_temp.tid(11))||patch)$$;
create function pg_temp.balance(dir text,code text default 'UAH') returns uuid language sql as $$select expected_item_id from public.finance_trip_balances where trip_id=pg_temp.result(100) and employee_id=pg_temp.tid(11) and currency=code and direction=dir$$;
create function pg_temp.remaining(dir text,code text default 'UAH') returns numeric language sql as $$select case when commitment='cancelled' then 0 else remaining_amount end from public.finance_expected_balances where id=pg_temp.balance(dir,code)$$;
create function pg_temp.post(n integer,amount text,dir text default 'outgoing') returns uuid language sql as $$select public.record_finance_movement(pg_temp.tid(1),pg_temp.tid(n),jsonb_build_object('kind',dir,'date','2026-09-12','accountId',pg_temp.tid(20),'amount',amount,'categoryId',(select id from public.finance_categories where studio_id=pg_temp.tid(1) and default_key=case when dir='outgoing' then 'business_travel' else 'other_income' end)))$$;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.tid(2),'UAH','2026-09-01',pg_temp.tid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.tid(22),pg_temp.tid(2),'Bank','UAH',0,pg_temp.tid(12));
select set_config('request.jwt.claim.sub',pg_temp.tid(10)::text,true);
insert into public.project_members(project_id,user_id,project_role,assigned_area_m2,assigned_at) values(pg_temp.tid(30),pg_temp.tid(10),'designer',0,current_date),(pg_temp.tid(30),pg_temp.tid(11),'designer',0,current_date);
update public.projects set city='Warsaw',country_code='PL' where id=pg_temp.tid(30);
set local role authenticated;
select public.finalize_finance_setup(pg_temp.tid(1));

select pg_temp.trip(100);
select pg_temp.entry(101,'{"kind":"plan","employeeId":"","currency":"PLN","expectedDate":"2026-10-01"}');
create function pg_temp.edit(n integer,source integer,patch jsonb default '{}') returns uuid language sql as $$select public.edit_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(n),pg_temp.result(100),pg_temp.result(source),jsonb_build_object('kind','plan','expenseType','meals','amount','120','currency','PLN','date','2026-09-12','expectedDate','2026-10-02')||patch)$$;
select lives_ok($$select pg_temp.edit(102,101)$$,'Plan edit needs no reason and is atomic');
select is((select amount from finance_trip_entries where id=pg_temp.result(101)),100::numeric,'original plan immutable');
select is((select count(*) from finance_movements),0::bigint,'plan edit creates no cash');
select is((select commitment from finance_expected_items where id=(select expected_item_id from finance_trip_entries where id=pg_temp.result(101))),'cancelled','old forecast retired');
select is((select amount from finance_trip_entries where id=pg_temp.result(102)),120::numeric,'replacement planned amount');
select is((select reporting_amount from finance_trip_entries where id=pg_temp.result(102)),null::numeric,'no historical plan FX');
select is(pg_temp.edit(102,101),pg_temp.result(102),'edit retry returns same result');
select throws_like($$select pg_temp.edit(102,101,'{"amount":"130"}')$$,'%finance_request_conflict%','changed retry conflicts');
select throws_like($$select pg_temp.edit(103,101)$$,'%finance_trip_edit_unavailable%','stale edit denied');
select throws_like($$select pg_temp.edit(104,102,'{"amount":"-5"}')$$,'%finance_amount_invalid%','invalid replacement rolls back');
select is((select count(*) from finance_trip_entries where reverses_id=pg_temp.result(102)),0::bigint,'no stranded reversal');
select is((select commitment from finance_expected_items where id=(select expected_item_id from finance_trip_entries where id=pg_temp.result(102))),'tentative','failed edit preserves forecast');
select pg_temp.entry(110,jsonb_build_object('planId',pg_temp.result(102)));
select throws_like($$select pg_temp.edit(111,102)$$,'%finance_trip_correction_invalid%','used plan remains baseline');
select throws_like($$select pg_temp.edit(112,110,jsonb_build_object('kind','expense','currency','UAH','employeeId',pg_temp.tid(11)))$$,'%finance_input_invalid%','actual edit requires reason');
select lives_ok($$select pg_temp.edit(113,110,jsonb_build_object('kind','expense','currency','UAH','employeeId',pg_temp.tid(11),'reason','Receipt amount corrected'))$$,'personal actual edit');
select is((select amount from finance_trip_entries where id=pg_temp.result(110)),100::numeric,'actual history retained');
select is((select plan_id from finance_trip_entries where id=pg_temp.result(110)),pg_temp.result(102),'original keeps the immutable unique planning relationship');
select is((select payload->>'entry' from finance_planning_requests where request_id=pg_temp.tid(113)),pg_temp.result(110)::text,'edit audit links replacement to original planned actual');
select is(pg_temp.remaining('outgoing'),120::numeric,'reimbursement reconciled to replacement');
select is((select count(*) from finance_movements),0::bigint,'personal edit creates no studio cash');
select pg_temp.entry(120,jsonb_build_object('employeeId','','accountId',pg_temp.tid(20)));
select throws_like($$select pg_temp.edit(121,120,jsonb_build_object('kind','expense','currency','UAH','accountId',pg_temp.tid(20),'reason','Receipt corrected'))$$,'%finance_trip_edit_unavailable%','posted cash edit requires confirmation');
select throws_like($$select pg_temp.edit(122,120,jsonb_build_object('kind','expense','currency','UAH','accountId',pg_temp.tid(20),'reason','Receipt corrected','confirmed',true,'amount','-1'))$$,'%finance_amount_invalid%','cash edit failure rolls back');
select is((select recorded_balance from finance_account_balances where id=pg_temp.tid(20)),-100::numeric,'failed edit preserves cash balance');
select lives_ok($$select pg_temp.edit(123,120,jsonb_build_object('kind','expense','currency','UAH','accountId',pg_temp.tid(20),'reason','Receipt corrected','confirmed',true))$$,'cash reversal and replacement in one transaction');
select is((select recorded_balance from finance_account_balances where id=pg_temp.tid(20)),-120::numeric,'only revised cash effect remains');
select is((select net_amount from finance_trip_entry_values where id=pg_temp.result(120)),0::numeric,'original payment retained with zero net');
select is((select net_amount from finance_trip_entry_values where id=pg_temp.result(123)),120::numeric,'new payment recorded once');
select throws_like($$select pg_temp.edit(124,120,jsonb_build_object('kind','expense','currency','UAH','accountId',pg_temp.tid(20),'reason','Receipt corrected','confirmed',true))$$,'%finance_trip_edit_unavailable%','already corrected payment cannot be edited again');
select pg_temp.entry(140,jsonb_build_object('kind','plan','employeeId','','amount','100','dailyRate','50','dayCount','1','coveredTravelerIds',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11))));
select lives_ok($$select pg_temp.edit(141,140,jsonb_build_object('currency','UAH','amount','50','dailyRate','50','dayCount','1','coveredTravelerIds',jsonb_build_array(pg_temp.tid(11))))$$,'per diem plan edit selects a subset');
select is((select traveler_count from finance_trip_entries where reverses_id=pg_temp.result(140)),2,'old per diem coverage retained on correction');
select is((select traveler_count from finance_trip_entries where id=pg_temp.result(141)),1,'replacement per diem covers one traveler');
select is((select count(*) from finance_trip_entry_travelers where entry_id=pg_temp.result(140)),2::bigint,'original covered identities immutable');
select ok(not has_function_privilege('anon','public.edit_finance_trip_entry(uuid,uuid,uuid,uuid,jsonb)','execute'),'anonymous cannot call edit boundary');
select set_config('request.jwt.claim.sub',pg_temp.tid(11)::text,true);
select throws_like($$select pg_temp.edit(130,113)$$,'%finance_admin_required%','employee cannot edit');
select set_config('request.jwt.claim.sub',pg_temp.tid(12)::text,true);
select throws_like($$select pg_temp.edit(131,113)$$,'%finance_admin_required%','cross-studio administrator cannot edit');
select * from finish();
rollback;
