begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.fid(n integer) returns uuid language sql immutable as $$select ('6e000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.day(n integer default 0) returns date language sql stable as $$select (now() at time zone 'Europe/Kyiv')::date+n$$;
insert into public.studios(id,name) values(pg_temp.fid(1),'Optional reporting valuation'),(pg_temp.fid(2),'Other studio');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.fid(n),'authenticated','authenticated','correction-'||n||'@test','{}','{}',now(),now() from generate_series(10,12)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.fid(n),'Correction tester','correction-'||n||'@test',case when n=11 then 'employee' else 'admin' end,true from generate_series(10,12)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active) values
(pg_temp.fid(1),pg_temp.fid(10),'admin',true),(pg_temp.fid(1),pg_temp.fid(11),'employee',true),(pg_temp.fid(2),pg_temp.fid(12),'admin',true);
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.fid(1),'UAH',pg_temp.day(-10),pg_temp.fid(10));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values
(pg_temp.fid(20),pg_temp.fid(1),'Bank','UAH',1000,pg_temp.fid(10)),(pg_temp.fid(21),pg_temp.fid(1),'Cash','UAH',200,pg_temp.fid(10)),
(pg_temp.fid(22),pg_temp.fid(1),'Dollars','USD',0,pg_temp.fid(10));
create function pg_temp.cat(k text) returns uuid language sql as $$select id from public.finance_categories where studio_id=pg_temp.fid(1) and default_key=k$$;
create function pg_temp.input(amount text,day date,account integer default 20,kind text default 'incoming',patch jsonb default '{}') returns jsonb language sql as $$
select jsonb_build_object('kind',kind,'date',day,'accountId',pg_temp.fid(account),'amount',amount,'category','Actual','categoryId',pg_temp.cat(case when kind='incoming' then 'other_income' else 'other_expense' end),'description','Actual')||patch;
$$;
create function pg_temp.mid(request integer) returns uuid language sql as $$select id from public.finance_movements where studio_id=pg_temp.fid(1) and request_id=pg_temp.fid(request)$$;
insert into public.projects(id,studio_id,name,total_area_m2,start_date,status,created_by) values(pg_temp.fid(40),pg_temp.fid(1),'VAT valuation',100,pg_temp.day(-10),'active',pg_temp.fid(10));
select set_config('request.jwt.claim.sub',pg_temp.fid(10)::text,true);
set local role authenticated;
select public.finalize_finance_setup(pg_temp.fid(1));

select lives_ok($$select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(100),pg_temp.input('10',pg_temp.day(),22))$$,'foreign native cash saves without reporting FX');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(22)),10::numeric,'native USD balance remains exact');
select ok((select reporting_amount is null and fx_rate is null and fx_source is null and fx_effective_date is null from public.finance_movement_entries where movement_id=pg_temp.mid(100)),'unresolved is an all-null metadata group, never a fake rate or amount');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(101),pg_temp.input('100',pg_temp.day()));
select is(public.get_finance_overview(pg_temp.fid(1))->>'netFlow',null,'a resolved and unresolved inflow never produces a partial converted net flow');
select ok((public.get_finance_overview(pg_temp.fid(1))->>'historyIncomplete')::boolean,'cash history marked incomplete');
select ok(not exists(select 1 from jsonb_array_elements(public.get_finance_overview(pg_temp.fid(1))->'history') p where (p->>'date')::date>=pg_temp.day() and p->>'amount' is not null),'historical cash unavailable from unresolved movement date onward');
select is((public.calculate_finance_forecast(pg_temp.fid(1))->'comparisons'->0->>'actual'),null,'category actual unavailable instead of a known subtotal');
select ok((public.get_finance_overview(pg_temp.fid(1))->>'movementValuationIncomplete')::boolean,'report links missing movement valuation to its non-blocking fallback');
select ok(exists(select 1 from jsonb_array_elements(public.get_finance_overview(pg_temp.fid(1))->'history') p where (p->>'date')::date<pg_temp.day() and p->>'amount' is not null),'history before missing valuation date stays usable');
select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(100),'USD',jsonb_build_object('rate','40','source','manual','effectiveDate',pg_temp.day()));
select is((select reporting_amount from public.finance_movement_entries where movement_id=pg_temp.mid(100)),400::numeric,'manual completion values original native cash exactly');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(22)),10::numeric,'manual valuation leaves native cash unchanged');
select is(public.get_finance_overview(pg_temp.fid(1))->>'netFlow','500.00','complete report includes native UAH and valued USD');
select lives_ok($$select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(100),'USD',jsonb_build_object('rate','40','source','manual','effectiveDate',pg_temp.day()))$$,'same valuation retry is idempotent');
select throws_like($$select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(100),'USD',jsonb_build_object('rate','41','source','manual','effectiveDate',pg_temp.day()))$$,'%finance_valuation_locked%','resolved reporting metadata cannot be revalued');
select throws_like($$update public.finance_movement_entries set amount=1 where movement_id=pg_temp.mid(100)$$,'%permission denied%','caller has no direct cash or valuation update permission');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(102),pg_temp.input('5',pg_temp.day(-7),22,'incoming',jsonb_build_object('fx',jsonb_build_object('rate','42','source','nbu','effectiveDate',pg_temp.day(-7)))));
select is((select fx_source from public.finance_movement_entries where movement_id=pg_temp.mid(102)),'nbu','automatic rate provenance retained');
select is((select reporting_amount from public.finance_movement_entries where movement_id=pg_temp.mid(102)),210::numeric,'successful automatic valuation is exact');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(103),pg_temp.input('2',pg_temp.day(-6),22,'refund',jsonb_build_object('relatedMovementId',pg_temp.mid(102))));
select is((select count(*) from public.finance_current_movements where id=pg_temp.mid(103)),1::bigint,'actual refund remains a visible real movement');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(22)),13::numeric,'real refund changes native cash on its own date');
select is(public.get_finance_overview(pg_temp.fid(1))->>'netFlow',null,'unresolved actual refund makes reporting totals unavailable');
select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(103),'USD',jsonb_build_object('rate','43','source','manual','effectiveDate',pg_temp.day(-6)));
select is((select reporting_amount from public.finance_movement_entries where movement_id=pg_temp.mid(103)),-86::numeric,'refund has its own dated rate, independent of original');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(104),pg_temp.input('3',pg_temp.day(-5),22));
select public.reverse_finance_movement(pg_temp.fid(1),pg_temp.fid(105),pg_temp.mid(104),pg_temp.day(-5),'Entered by mistake');
select ok(not (public.get_finance_overview(pg_temp.fid(1))->>'historyIncomplete')::boolean,'cancelled unresolved pair does not poison effective history');
select is((select count(*) from public.finance_cash_effects where movement_id in (pg_temp.mid(104),pg_temp.mid(105))),0::bigint,'unvalued same-date technical cancellation has no reporting effect');
select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(104),'USD',jsonb_build_object('rate','44','source','manual','effectiveDate',pg_temp.day(-5)));
select is((select sum(reporting_amount) from public.finance_movement_entries where movement_id in (pg_temp.mid(104),pg_temp.mid(105))),0::numeric,'completion mirrors reversal, preserving exact cancellation');
select is((select count(*) from public.finance_movement_entries where movement_id in (pg_temp.mid(104),pg_temp.mid(105)) and fx_rate=44),2::bigint,'original and technical reversal remain recoverable with their metadata');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(106),pg_temp.input('7',pg_temp.day(-4),22));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(107),pg_temp.mid(106),pg_temp.input('8',pg_temp.day(-3),22));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(108),pg_temp.mid(107),pg_temp.input('9',pg_temp.day(-2),22,'incoming',jsonb_build_object('fx',jsonb_build_object('rate','45','source','nbu','effectiveDate',pg_temp.day(-2)))));
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(22)),22::numeric,'repeated corrections count only the final native effect');
select is((select count(*) from public.finance_current_movements where id in (pg_temp.mid(106),pg_temp.mid(107),pg_temp.mid(108))),1::bigint,'only current correction is shown normally');
select ok(not (public.get_finance_overview(pg_temp.fid(1))->>'historyIncomplete')::boolean,'resolved replacement clears reporting incompleteness while technical history survives');
select is((select sum(reporting_amount) from public.finance_cash_effects where movement_id in (pg_temp.mid(106),pg_temp.mid(107),pg_temp.mid(108))),405::numeric,'replacement contributes exactly once to reporting');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(109),pg_temp.input('10',pg_temp.day(-1),22,'transfer',jsonb_build_object('destinationId',pg_temp.fid(20),'receivedAmount','390','fee','1')));
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(22)),11::numeric,'exchange deducts actual sent cash plus fee without reporting FX');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(20)),1490::numeric,'exchange credits actual received cash, independent of reporting FX');
select is((select fx_source from public.finance_movement_entries where movement_id=pg_temp.mid(109) and entry_role='destination'),'identity','native reporting leg stays valued during provider outage');
select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(109),'USD',jsonb_build_object('rate','41','source','manual','effectiveDate',pg_temp.day(-1)));
select is((select sum(reporting_amount) from public.finance_movement_entries where movement_id=pg_temp.mid(109) and currency='USD'),(-451)::numeric,'one fallback completes primary and fee consistently');
-- A matched cash receipt remains valid while its optional reporting metadata is pending.
select public.save_finance_trip(pg_temp.fid(1),pg_temp.fid(200),jsonb_build_object('title','Trip','destination','Kyiv','startsOn',pg_temp.day(-10),'endsOn',pg_temp.day(1),'status','active','travelers',jsonb_build_array(pg_temp.fid(11))));
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(201),pg_temp.input('2',pg_temp.day(-2),22,'outgoing'));
select lives_ok($$select public.record_finance_trip_entry(pg_temp.fid(1),pg_temp.fid(202),(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(200)),jsonb_build_object('kind','expense','expenseType','travel','amount','2','currency','USD','date',pg_temp.day(-2),'movementId',pg_temp.mid(201)))$$,'cash-linked receipt accepts unresolved reporting valuation');
select is((select actual_amount from public.finance_trip_totals where id=(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(200))),null,'trip actual is unresolved instead of zero');
select lives_ok($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(203),pg_temp.mid(201),pg_temp.input('3',pg_temp.day(-1),22,'outgoing',jsonb_build_object('categoryId',pg_temp.cat('business_travel'))))$$,'trip-linked cash correction survives provider outage');
select is((select sum(net_amount) from public.finance_trip_entry_values where movement_id in (pg_temp.mid(201),pg_temp.mid(203))),3::numeric,'trip native expense follows only replacement');
select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(203),'USD',jsonb_build_object('rate','42','source','manual','effectiveDate',pg_temp.day(-1)));
select is((select actual_amount from public.finance_trip_totals where id=(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(200))),'126.00','completing replacement values the trip once without changing receipt history');
-- Project VAT retains its refund/reallocation baseline and pending provenance.
select public.save_finance_project_terms(pg_temp.fid(1),pg_temp.fid(210),pg_temp.fid(40),jsonb_build_object('stream','design','revision',0,'mode','design','amount','10','currency','USD','vatRate','20','priceBasis','net','reason','Agreement'));
select public.save_finance_project_item(pg_temp.fid(1),pg_temp.fid(211),pg_temp.fid(40),jsonb_build_object('stream','design','useAgreementBasis',true,'item',jsonb_build_object('direction','incoming','amount','10','currency','USD','categoryId',pg_temp.cat('project_payments'),'description','Invoice','dueDate',pg_temp.day(-1),'expectedDate',pg_temp.day(-1),'commitment','agreed','certainty','fixed','established',true)));
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(212),pg_temp.input('12',pg_temp.day(-1),22,'incoming',jsonb_build_object('categoryId',pg_temp.cat('project_payments'))));
select public.allocate_finance_payment(pg_temp.fid(1),pg_temp.fid(213),(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(211)),pg_temp.mid(212),12);
select is((select vat_reporting_amount from public.finance_project_vat_actuals where studio_id=pg_temp.fid(1) and financial_date=pg_temp.day(-1)),null::numeric,'unresolved project VAT is never a partial or zero converted total');
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(214),pg_temp.mid(212),pg_temp.input('12',pg_temp.day(-1),22,'incoming',jsonb_build_object('categoryId',pg_temp.cat('project_payments'),'fx',jsonb_build_object('rate','41','source','nbu','effectiveDate',pg_temp.day(-1)))));
select is((select vat_reporting_amount from public.finance_project_vat_actuals where studio_id=pg_temp.fid(1) and financial_date=pg_temp.day(-1)),0::numeric,'cancelled unvalued VAT attribution has zero economic effect');
select public.allocate_finance_payment(pg_temp.fid(1),pg_temp.fid(215),(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(211)),pg_temp.mid(214),12);
select is((select vat_reporting_amount from public.finance_project_vat_actuals where studio_id=pg_temp.fid(1) and financial_date=pg_temp.day(-1)),82::numeric,'corrected VAT uses replacement valuation exactly once');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(216),pg_temp.input('6',pg_temp.day(),22,'refund',jsonb_build_object('relatedMovementId',pg_temp.mid(214))));
select is((select vat_reporting_amount from public.finance_project_vat_actuals where studio_id=pg_temp.fid(1) and financial_date=pg_temp.day()),null::numeric,'real pending refund retains unresolved VAT on its actual date');
select public.reverse_finance_movement(pg_temp.fid(1),pg_temp.fid(217),pg_temp.mid(216),pg_temp.day(),'Mistaken refund entry');
select is((select vat_reporting_amount from public.finance_project_vat_actuals where studio_id=pg_temp.fid(1) and financial_date=pg_temp.day()),0::numeric,'technical refund cancellation does not poison VAT reporting');
select public.save_finance_forecast_snapshot(pg_temp.fid(1),pg_temp.fid(220),'Pending actual','3','confirmed',jsonb_build_array(jsonb_build_object('currency','USD','rate','40','source','manual','effectiveDate',pg_temp.day())));
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(221),pg_temp.input('1',pg_temp.day(),22));
select is((public.compare_finance_forecast_snapshot(pg_temp.fid(1),(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(220)))->0->>'actual'),null,'subsequent snapshot actual stays unresolved instead of zero');
select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(221),'USD',jsonb_build_object('rate','43','source','manual','effectiveDate',pg_temp.day()));
select is((public.compare_finance_forecast_snapshot(pg_temp.fid(1),(select result_id from public.finance_planning_requests where request_id=pg_temp.fid(220)))->0->>'actual'),'43.00','completing snapshot actual preserves posting-order boundary');
select set_config('request.jwt.claim.sub',pg_temp.fid(11)::text,true);
select throws_like($$select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(109),'USD',jsonb_build_object('rate','41','source','manual','effectiveDate',pg_temp.day(-1)))$$,'%finance_admin_required%','employee denied reporting valuation');
select set_config('request.jwt.claim.sub',pg_temp.fid(12)::text,true);
select throws_like($$select public.value_finance_movement(pg_temp.fid(1),pg_temp.mid(109),'USD',jsonb_build_object('rate','41','source','manual','effectiveDate',pg_temp.day(-1)))$$,'%finance_admin_required%','other tenant denied reporting valuation');
reset role;
select throws_like($$update public.finance_movement_entries set amount=1 where movement_id=pg_temp.mid(100)$$,'%finance_history_immutable%','even privileged updates cannot change posted native cash');
select throws_like($$update public.finance_movement_entries set fx_rate=1 where movement_id=pg_temp.mid(100)$$,'%finance_history_immutable%','even privileged updates cannot change resolved reporting metadata');
select * from finish();
rollback;
