begin;
select no_plan();
create function pg_temp.tid(n integer) returns uuid language sql immutable as $$select ('79000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.studios(id,name) values(pg_temp.tid(1),'Trips A'),(pg_temp.tid(2),'Trips B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.tid(n),'authenticated','authenticated','trips-'||n||'@test','{}','{}',now(),now() from generate_series(10,14)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.tid(n),'Traveler '||n,'trips-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,14)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.tid(case when n=12 then 2 else 1 end),pg_temp.tid(n),case when n=11 then 'employee' else 'admin' end,n<>14 from generate_series(10,14)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.tid(1),'UAH','2026-09-01',pg_temp.tid(10));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.tid(20),pg_temp.tid(1),'Bank','UAH',0,pg_temp.tid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,status,created_by) values(pg_temp.tid(30),pg_temp.tid(1),'Project',100,'2026-09-01','active',pg_temp.tid(10)),(pg_temp.tid(31),pg_temp.tid(2),'Foreign',100,'2026-09-01','active',pg_temp.tid(12));
create function pg_temp.result(n integer) returns uuid language sql as $$select result_id from public.finance_planning_requests where studio_id=pg_temp.tid(1) and request_id=pg_temp.tid(n)$$;
create function pg_temp.trip(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_trip(pg_temp.tid(1),pg_temp.tid(n),jsonb_build_object('title','Warsaw','destination','Warsaw','startsOn','2026-09-12','endsOn','2026-09-15','status','planned','travelers',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11)))||patch)$$;
create function pg_temp.entry(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.record_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(n),pg_temp.result(100),jsonb_build_object('kind','expense','expenseType','meals','amount','100','currency','UAH','date','2026-09-12','employeeId',pg_temp.tid(11))||patch)$$;
create function pg_temp.balance(dir text,code text default 'UAH') returns uuid language sql as $$select expected_item_id from public.finance_trip_balances where trip_id=pg_temp.result(100) and employee_id=pg_temp.tid(11) and currency=code and direction=dir$$;
create function pg_temp.remaining(dir text,code text default 'UAH') returns numeric language sql as $$select case when commitment='cancelled' then 0 else remaining_amount end from public.finance_expected_balances where id=pg_temp.balance(dir,code)$$;
create function pg_temp.post(n integer,amount text,dir text default 'outgoing') returns uuid language sql as $$select public.record_finance_movement(pg_temp.tid(1),pg_temp.tid(n),jsonb_build_object('kind',dir,'date','2026-09-12','accountId',pg_temp.tid(20),'amount',amount,'categoryId',(select id from public.finance_categories where studio_id=pg_temp.tid(1) and default_key=case when dir='outgoing' then 'business_travel' else 'other_income' end)))$$;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.tid(2),'UAH','2026-09-01',pg_temp.tid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.tid(22),pg_temp.tid(2),'Bank','UAH',0,pg_temp.tid(12));
select set_config('request.jwt.claim.sub',pg_temp.tid(10)::text,true);
insert into public.project_members(project_id,user_id,project_role,assigned_area_m2,assigned_at) values(pg_temp.tid(30),pg_temp.tid(10),'designer',0,current_date),(pg_temp.tid(30),pg_temp.tid(11),'designer',0,current_date);
update public.projects set city='Warsaw',country_code='PL' where id=pg_temp.tid(30);
set local role authenticated;
select public.finalize_finance_setup(pg_temp.tid(1));
select lives_ok($$select public.create_calendar_event_with_invites(pg_temp.tid(1),'Calendar Warsaw','business_trip','2026-10-24T00:00:00+03','2026-10-27T00:00:00+02',true,p_project_id=>pg_temp.tid(30),p_participant_ids=>array[pg_temp.tid(10),pg_temp.tid(11)])$$,'Calendar atomically creates one linked Finance trip');
create function pg_temp.event_id() returns uuid language sql as $$select id from public.calendar_events where studio_id=pg_temp.tid(1) and title='Calendar Warsaw'$$;
create function pg_temp.linked_trip() returns uuid language sql as $$select id from public.finance_trips where studio_id=pg_temp.tid(1) and calendar_source_id=pg_temp.event_id()$$;
select is((select count(*) from public.finance_trips),1::bigint,'one trip after participant inserts');
select is((select ends_on-starts_on+1 from public.finance_trips),3,'all-day exclusive Calendar end becomes inclusive Finance dates across DST');
select is((select destination from public.finance_trips),'Warsaw, PL','destination from project');
select is((select count(*) from public.finance_trip_travelers where active),2::bigint,'participants synchronized');
select lives_ok($$update public.calendar_events set description='Updated note',ends_at='2026-10-28T00:00:00+02' where id=pg_temp.event_id()$$,'Calendar edit');
select is((select note from public.finance_trips),'Updated note','operational note updated');
select is((select ends_on from public.finance_trips),'2026-10-27'::date,'trip dates updated');
select lives_ok($$select public.replace_business_trip_participants(pg_temp.event_id(),array[pg_temp.tid(11)])$$,'participant subset update');
select is((select count(*) from public.finance_trip_travelers where active),1::bigint,'removed participant is inactive');
select lives_ok($$select public.replace_business_trip_participants(pg_temp.event_id(),array[pg_temp.tid(10),pg_temp.tid(11)])$$,'participants restored');
select lives_ok($$update public.calendar_events set description=description where id=pg_temp.event_id()$$,'repeat synchronization');
select is((select count(*) from public.finance_trips),1::bigint,'repeat never duplicates trip');
select throws_like($$select public.save_finance_trip(pg_temp.tid(1),pg_temp.tid(400),jsonb_build_object('id',pg_temp.linked_trip(),'version',(select version from public.finance_trips where id=pg_temp.linked_trip()),'title','Override','destination','Warsaw','startsOn','2026-10-24','endsOn','2026-10-27','status','planned','travelers',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11))))$$,'%finance_trip_calendar_owned%','Finance cannot overwrite Calendar metadata');
select lives_ok($$select pg_temp.trip(100)$$,'manual trips still available');
select lives_ok($$select pg_temp.entry(401,'{"kind":"plan","employeeId":"","currency":"PLN","amount":"1200"}')$$,'PLN plan without PLN account or FX');
select is((select count(*) from public.finance_accounts where currency='PLN'),0::bigint,'no PLN account');
select ok((select reporting_amount is null and fx_rate is null from public.finance_trip_entries where id=pg_temp.result(401)),'no historical cash valuation stored for foreign plan');
select is((select count(*) from public.finance_movements),0::bigint,'planning creates no cash');
select is((select count(*) from public.finance_expected_items),0::bigint,'undated plan invents no cash timing');
select lives_ok($$select pg_temp.entry(402,jsonb_build_object('kind','plan','employeeId','','currency','USD','amount','300','dailyRate','50','dayCount','3','coveredTravelerIds',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11)),'expectedDate','2026-10-24'))$$,'50 USD times 3 days times 2 travelers');
select is((select traveler_count from public.finance_trip_entries where id=pg_temp.result(402)),2,'covered count stored');
select is((select count(*) from public.finance_trip_entry_travelers where entry_id=pg_temp.result(402)),2::bigint,'coverage identities stored');
select lives_ok($$select pg_temp.entry(403,jsonb_build_object('kind','plan','employeeId','','amount','150','dailyRate','50','dayCount','3','coveredTravelerIds',jsonb_build_array(pg_temp.tid(11))))$$,'selected single traveler');
select throws_like($$select pg_temp.entry(404,jsonb_build_object('kind','plan','employeeId','','amount','150','dailyRate','50','dayCount','3','coveredTravelerIds',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11))))$$,'%check constraint%','wrong covered total rejected');
select throws_like($$select pg_temp.entry(405,jsonb_build_object('kind','plan','employeeId','','amount','150','dailyRate','50','dayCount','3','coveredTravelerIds',jsonb_build_array(pg_temp.tid(12))))$$,'%finance_trip_traveler_invalid%','cross-studio per diem denied');
select lives_ok($$select pg_temp.entry(406,jsonb_build_object('currency','USD','amount','280','fx',jsonb_build_object('rate','40','source','manual','effectiveDate','2026-09-12'),'planId',pg_temp.result(402)))$$,'actual uses historical rate and retires plan');
select is((select commitment from public.finance_expected_items where id=(select expected_item_id from public.finance_trip_entries where id=pg_temp.result(402))),'cancelled','plan expectation retired');
select is((select reporting_amount from public.finance_trip_entries where id=pg_temp.result(406)),11200::numeric,'historical actual preserved');
select lives_ok($$select public.record_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(410),pg_temp.linked_trip(),jsonb_build_object('kind','expense','expenseType','travel','amount','100','currency','UAH','date','2026-09-12','employeeId',pg_temp.tid(11)))$$,'Calendar-linked trip can incur personal expense');
create temporary table before_cancel as select to_jsonb(e) as entry,(select jsonb_agg(to_jsonb(i) order by i.id) from public.finance_expected_items i) as obligations from public.finance_trip_entries e where e.trip_id=pg_temp.linked_trip();
select lives_ok($$update public.calendar_events set cancelled_at=now() where id=pg_temp.event_id()$$,'Calendar cancellation with Finance history');
select is((select calendar_state from public.finance_trips where id=pg_temp.linked_trip()),'cancelled','source lifecycle explicit');
select is((select status from public.finance_trips where id=pg_temp.linked_trip()),'planned','Finance status requires deliberate reconciliation');
select is((select to_jsonb(e) from public.finance_trip_entries e where e.trip_id=pg_temp.linked_trip()),(select entry from before_cancel),'original expense unchanged');
select is((select jsonb_agg(to_jsonb(i) order by i.id) from public.finance_expected_items i),(select obligations from before_cancel),'all Finance obligations unchanged by Calendar cancellation');
select lives_ok($$select public.create_calendar_event_with_invites(pg_temp.tid(1),'Empty Calendar trip','business_trip','2026-10-24T00:00:00+03','2026-10-25T00:00:00+03',true,p_project_id=>pg_temp.tid(30),p_participant_ids=>array[pg_temp.tid(10)])$$,'second empty calendar trip');
select lives_ok($$update public.calendar_events set cancelled_at=now() where title='Empty Calendar trip'$$,'empty trip cancellation');
select is((select status from public.finance_trips where title='Empty Calendar trip'),'cancelled','empty Finance trip safely cancelled');
-- Project/traveler changes preserve financial classification and receipt coverage.
select lives_ok($$select public.create_calendar_event_with_invites(pg_temp.tid(1),'Moving trip','business_trip','2026-10-24T10:00:00+03','2026-10-26T17:00:00+02',false,p_project_id=>pg_temp.tid(30),p_participant_ids=>array[pg_temp.tid(10),pg_temp.tid(11)])$$,'timed Calendar trip');
reset role;
insert into public.projects(id,studio_id,name,total_area_m2,start_date,status,created_by) values(pg_temp.tid(32),pg_temp.tid(1),'Second project',100,'2026-09-01','active',pg_temp.tid(10));
insert into public.project_members(project_id,user_id,project_role,assigned_area_m2,assigned_at) values(pg_temp.tid(32),pg_temp.tid(10),'designer',0,current_date),(pg_temp.tid(32),pg_temp.tid(11),'designer',0,current_date);
set local role authenticated;
select lives_ok($$update public.calendar_events set project_id=pg_temp.tid(32) where title='Moving trip'$$,'project sync before history');
select is((select project_id from public.finance_trips where title='Moving trip'),pg_temp.tid(32),'Finance project follows Calendar without history');
select lives_ok($$select public.record_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(420),(select id from public.finance_trips where title='Moving trip'),jsonb_build_object('kind','expense','expenseType','meals','amount','300','currency','UAH','date','2026-09-12','employeeId',pg_temp.tid(11),'dailyRate','50','dayCount','3','coveredTravelerIds',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11))))$$,'actual per diem covers two travelers but preserves actual payer');
select lives_ok($$update public.calendar_events set project_id=pg_temp.tid(30) where title='Moving trip'$$,'Calendar project can change after history');
select is((select project_id from public.finance_trips where title='Moving trip'),pg_temp.tid(32),'historical Finance project unchanged');
select lives_ok($$select public.replace_business_trip_participants((select id from calendar_events where title='Moving trip'),array[pg_temp.tid(10)])$$,'remove traveler after actual expense');
select is((select count(*) from public.finance_trip_entry_travelers where entry_id=pg_temp.result(420)),2::bigint,'original coverage retained');
select lives_ok($$update public.calendar_events set event_type='general' where title='Moving trip'$$,'change Calendar type');
select is((select calendar_state from public.finance_trips where title='Moving trip'),'changed_type','type change explicit');
select lives_ok($$delete from public.calendar_event_participants where event_id in(select id from calendar_events where title='Moving trip')$$,'clear participants using Calendar rules');
reset role;
select lives_ok($$delete from public.calendar_events where title='Moving trip'$$,'physical deletion preserves Finance history');
set local role authenticated;
select ok((select calendar_event_id is null and calendar_source_id is not null and calendar_state='deleted' from public.finance_trips where title='Moving trip'),'deleted source identity retained');
select is((select amount from public.finance_trip_entries where id=pg_temp.result(420)),300::numeric,'expense survives source deletion');
select lives_ok($$select public.create_calendar_event_with_invites(pg_temp.tid(1),'Delete empty trip','business_trip','2026-10-24T00:00:00+03','2026-10-25T00:00:00+03',true,p_project_id=>pg_temp.tid(30),p_participant_ids=>array[pg_temp.tid(10)])$$,'empty deletion fixture');
select lives_ok($$delete from calendar_event_participants where event_id in(select id from calendar_events where title='Delete empty trip')$$,'clear empty event participants');
reset role;
select lives_ok($$delete from calendar_events where title='Delete empty trip'$$,'delete empty Calendar event');
set local role authenticated;
select ok((select calendar_state='deleted' and status='cancelled' from finance_trips where title='Delete empty trip'),'empty Finance trip retained as cancelled');
select set_config('request.jwt.claim.sub',pg_temp.tid(11)::text,true);
select lives_ok($$select public.create_calendar_event_with_invites(pg_temp.tid(1),'Employee Calendar trip','business_trip','2026-10-24T00:00:00+03','2026-10-25T00:00:00+03',true,p_project_id=>pg_temp.tid(30))$$,'employee Calendar writes safely project operational trip');
select is((select count(*) from public.finance_trips),0::bigint,'employee has no Finance reads');
select is((select count(*) from public.finance_trip_entry_travelers),0::bigint,'employee cannot read per diem coverage');
select throws_like($$select pg_temp.entry(450)$$,'%finance_admin_required%','employee cannot create financial entries');
select set_config('request.jwt.claim.sub',pg_temp.tid(12)::text,true);
select is((select count(*) from public.finance_trips),0::bigint,'cross-studio Finance reads denied');
reset role;
insert into public.project_members(project_id,user_id,project_role,assigned_area_m2,assigned_at) values(pg_temp.tid(31),pg_temp.tid(12),'designer',0,current_date);
set local role authenticated;
select lives_ok($$select public.create_calendar_event_with_invites(pg_temp.tid(2),'Before Finance setup','business_trip','2026-10-24T00:00:00+03','2026-10-25T00:00:00+03',true,p_project_id=>pg_temp.tid(31),p_participant_ids=>array[pg_temp.tid(12)])$$,'Calendar works before Finance setup');
select is((select count(*) from public.finance_trips),0::bigint,'no Finance setup invented');
select lives_ok($$select public.finalize_finance_setup(pg_temp.tid(2))$$,'finalization backfills existing trip');
select is((select count(*) from public.finance_trips),1::bigint,'one backfilled trip');
reset role;
select * from finish();
rollback;
