begin;
select no_plan();
create function pg_temp.tid(n integer) returns uuid language sql immutable as $$select ('79000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.studios(id,name) values(pg_temp.tid(1),'Trips A'),(pg_temp.tid(2),'Trips B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.tid(n),'authenticated','authenticated','trips-'||n||'@test','{}','{}',now(),now() from generate_series(10,14)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.tid(n),'Traveler '||n,'trips-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,14)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.tid(case when n=12 then 2 else 1 end),pg_temp.tid(n),case when n=11 then 'employee' else 'admin' end,n<>14 from generate_series(10,14)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.tid(1),'UAH','2026-09-01',pg_temp.tid(10));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.tid(20),pg_temp.tid(1),'Bank','UAH',0,pg_temp.tid(10)),(pg_temp.tid(21),pg_temp.tid(1),'PLN','PLN',0,pg_temp.tid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,status,created_by) values(pg_temp.tid(30),pg_temp.tid(1),'Project',100,'2026-09-01','active',pg_temp.tid(10)),(pg_temp.tid(31),pg_temp.tid(2),'Foreign',100,'2026-09-01','active',pg_temp.tid(12));
create function pg_temp.result(n integer) returns uuid language sql as $$select result_id from public.finance_planning_requests where studio_id=pg_temp.tid(1) and request_id=pg_temp.tid(n)$$;
create function pg_temp.trip(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_trip(pg_temp.tid(1),pg_temp.tid(n),jsonb_build_object('title','Warsaw','destination','Warsaw','startsOn','2026-09-12','endsOn','2026-09-15','status','planned','travelers',jsonb_build_array(pg_temp.tid(10),pg_temp.tid(11)))||patch)$$;
create function pg_temp.entry(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.record_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(n),pg_temp.result(100),jsonb_build_object('kind','expense','expenseType','meals','amount','100','currency','UAH','date','2026-09-12','employeeId',pg_temp.tid(11))||patch)$$;
create function pg_temp.balance(dir text,code text default 'UAH') returns uuid language sql as $$select expected_item_id from public.finance_trip_balances where trip_id=pg_temp.result(100) and employee_id=pg_temp.tid(11) and currency=code and direction=dir$$;
create function pg_temp.remaining(dir text,code text default 'UAH') returns numeric language sql as $$select case when commitment='cancelled' then 0 else remaining_amount end from public.finance_expected_balances where id=pg_temp.balance(dir,code)$$;
create function pg_temp.post(n integer,amount text,dir text default 'outgoing') returns uuid language sql as $$select public.record_finance_movement(pg_temp.tid(1),pg_temp.tid(n),jsonb_build_object('kind',dir,'date','2026-09-12','accountId',pg_temp.tid(20),'amount',amount,'categoryId',(select id from public.finance_categories where studio_id=pg_temp.tid(1) and default_key=case when dir='outgoing' then 'business_travel' else 'other_income' end)))$$;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.tid(2),'UAH','2026-09-01',pg_temp.tid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.tid(22),pg_temp.tid(2),'Bank','UAH',0,pg_temp.tid(12));
select set_config('request.jwt.claim.sub',pg_temp.tid(10)::text,true);
set local role authenticated;
select public.finalize_finance_setup(pg_temp.tid(1));
select lives_ok($$select pg_temp.trip(100)$$,'trip with optional project and multiple travelers');
select is((select count(*) from public.finance_trip_travelers),2::bigint,'multiple travelers');
select is(pg_temp.trip(100),pg_temp.result(100),'trip retry');
select lives_ok($$select pg_temp.trip(101,jsonb_build_object('id',pg_temp.result(100),'version',1,'projectId',pg_temp.tid(30),'title','Warsaw edit'))$$,'edit trip and project');
select throws_like($$select pg_temp.trip(102,jsonb_build_object('id',pg_temp.result(100),'version',1))$$,'%finance_version_conflict%','stale edit denied');
select throws_like($$select pg_temp.trip(103,jsonb_build_object('projectId',pg_temp.tid(31)))$$,'%foreign key%','cross-studio project denied');
select throws_like($$select pg_temp.trip(104,jsonb_build_object('travelers',jsonb_build_array(pg_temp.tid(12))))$$,'%finance_trip_traveler_invalid%','cross-studio traveler denied');
select lives_ok($$select pg_temp.entry(110,'{"kind":"plan","employeeId":"","amount":"26000","expectedDate":"2026-10-10"}')$$,'dated plan creates tentative forecast item');
select is((select planned_amount::numeric from public.finance_trip_totals where id=pg_temp.result(100)),26000::numeric,'plan total');
select is((select count(*) from public.finance_movements),0::bigint,'plan creates no cash');
select lives_ok($$select pg_temp.entry(120,'{"amount":"18400"}')$$,'employee-paid expense');
select is((select count(*) from public.finance_movements),0::bigint,'employee receipt creates no studio cash');
select is(pg_temp.remaining('outgoing'),18400::numeric,'reimbursement due');
select lives_ok($$select pg_temp.entry(121,jsonb_build_object('kind','advance','amount','20000','accountId',pg_temp.tid(20)))$$,'issue advance');
select is(pg_temp.remaining('incoming'),null::numeric,'unused advance is not forecast as an immediate return during travel');
select lives_ok($$select pg_temp.trip(123,jsonb_build_object('id',pg_temp.result(100),'version',2,'projectId',pg_temp.tid(30),'status','completed'))$$,'completion confirms advance reconciliation');
select is(pg_temp.remaining('incoming'),1600::numeric,'excess advance due back');
select is(pg_temp.remaining('outgoing'),0::numeric,'advance clears reimbursement obligation');
select is((select actual_amount::numeric from public.finance_trip_totals where id=pg_temp.result(100)),18400::numeric,'advance is not a second expense');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.tid(20)),-20000::numeric,'only advance changes cash');
select is(pg_temp.entry(121,jsonb_build_object('kind','advance','amount','20000','accountId',pg_temp.tid(20))),pg_temp.result(121),'contextual movement retry idempotent');
select throws_like($$select pg_temp.entry(121,jsonb_build_object('kind','advance','amount','20001','accountId',pg_temp.tid(20)))$$,'%finance_request_conflict%','changed retry rejected');
select lives_ok($$select public.allocate_finance_payment(pg_temp.tid(1),pg_temp.tid(131),pg_temp.balance('incoming'),pg_temp.post(130,'1600','incoming'),1600)$$,'unused advance return settled with canonical allocation');
select is(pg_temp.remaining('incoming'),0::numeric,'return settled');
select lives_ok($$select pg_temp.entry(122,'{"amount":"6100"}')$$,'additional employee spending');
select is(pg_temp.remaining('outgoing'),6100::numeric,'additional reimbursement after return');
select lives_ok($$select public.allocate_finance_payment(pg_temp.tid(1),pg_temp.tid(141),pg_temp.balance('outgoing'),pg_temp.post(140,'2000'),2000)$$,'partial reimbursement');
select is(pg_temp.remaining('outgoing'),4100::numeric,'partial remaining');
select lives_ok($$select pg_temp.entry(150,jsonb_build_object('amount','100','employeeId','','movementId',pg_temp.post(151,'100')))$$,'studio expense matched to existing cash');
select is((select count(*) from public.finance_movements),4::bigint,'matching creates no duplicate cash');
select is((select actual_amount::numeric from public.finance_trip_totals where id=pg_temp.result(100)),24600::numeric,'actual total');
select is((select variance::numeric from public.finance_trip_totals where id=pg_temp.result(100)),-1400::numeric,'variance');
select lives_ok($$select pg_temp.entry(160,'{"currency":"PLN","amount":"100","fx":{"rate":"10.123456","source":"manual","effectiveDate":"2026-09-12"}}')$$,'foreign receipt valued once');
select is((select reporting_amount from public.finance_trip_entries where id=pg_temp.result(160)),1012.35::numeric,'canonical currency rounding');
select is(pg_temp.remaining('outgoing','PLN'),100::numeric,'currency-separated employee balance');
select lives_ok($$select pg_temp.entry(170,'{"amount":"3200","dailyRate":"800","dayCount":"4"}')$$,'per diem');
select throws_like($$select pg_temp.entry(171,'{"amount":"3100","dailyRate":"800","dayCount":"4"}')$$,'%check constraint%','per diem calculation enforced');
select throws_like($$select pg_temp.trip(180,jsonb_build_object('id',pg_temp.result(100),'version',3,'projectId',''))$$,'%finance_trip_project_locked%','project history cannot be silently reassigned');
select throws_like($$update public.finance_trip_entries set amount=1$$,'%permission denied%','immutable receipt boundary');
select throws_like($$select public.save_finance_expected_item(pg_temp.tid(1),pg_temp.tid(181),jsonb_build_object('id',pg_temp.balance('outgoing'),'version',(select version from public.finance_expected_items where id=pg_temp.balance('outgoing')),'direction','outgoing','amount','99999','currency','UAH','categoryId',(select category_id from public.finance_expected_items where id=pg_temp.balance('outgoing')),'commitment','agreed','certainty','fixed'))$$,'%finance_trip_expected_locked%','generic expectations cannot overwrite derived amounts');
select lives_ok($$select public.record_finance_trip_entry(pg_temp.tid(1),pg_temp.tid(190),pg_temp.result(100),jsonb_build_object('reversesId',pg_temp.result(170),'note','Wrong allowance'))$$,'explicit receipt correction');
select is(pg_temp.remaining('outgoing'),4100::numeric,'correction reconciles reimbursement');
select lives_ok($$select public.reverse_finance_movement(pg_temp.tid(1),pg_temp.tid(191),(select movement_id from public.finance_trip_entries where id=pg_temp.result(121)),'2026-09-13','Advance recorded in error')$$,'advance reversal');
select is(pg_temp.remaining('outgoing'),24100::numeric,'advance reversal reopens true reimbursement');
select lives_ok($$select public.reverse_finance_movement(pg_temp.tid(1),pg_temp.tid(192),(select movement_id from public.finance_trip_entries where id=pg_temp.result(150)),'2026-09-13','Duplicate hotel')$$,'studio expense reversal');
select is((select studio_paid::numeric from public.finance_trip_totals where id=pg_temp.result(100)),0::numeric,'studio reversal adjusts actual without rewriting original');
select is((select amount from public.finance_trip_entries where id=pg_temp.result(150)),100::numeric,'original studio amount retained');

-- Forecast: a planned payment is retired atomically, while its comparison baseline stays.
select lives_ok($$select pg_temp.entry(210,jsonb_build_object('amount','500','planId',pg_temp.result(110)))$$,'actual retires planned cash');
select is((select commitment from public.finance_expected_items where id=(select expected_item_id from public.finance_trip_entries where id=pg_temp.result(110))),'cancelled','plan cash no longer enters Forecast');
select is((select planned_amount::numeric from public.finance_trip_totals where id=pg_temp.result(100)),26000::numeric,'actual does not overwrite plan');
select throws_like($$select pg_temp.entry(211,jsonb_build_object('planId',pg_temp.result(110)))$$,'%duplicate key%','same planned payment cannot be completed twice');
select lives_ok($$select pg_temp.entry(212,'{"kind":"plan","employeeId":"","amount":"100","expectedDate":"2026-09-12"}')$$,'another planned payment');
select lives_ok($$select public.allocate_finance_payment(pg_temp.tid(1),pg_temp.tid(214),(select expected_item_id from public.finance_trip_entries where id=pg_temp.result(212)),pg_temp.post(213,'100'),100)$$,'plan paid through existing settlement UI');
select lives_ok($$select pg_temp.entry(215,jsonb_build_object('employeeId','','planId',pg_temp.result(212),'movementId',(select id from public.finance_movements where request_id=pg_temp.tid(213))))$$,'paid plan converted to actual without duplicate cash');
select is((select count(*) from public.finance_movements where request_id=pg_temp.tid(213)),1::bigint,'conversion reused same ledger event');
select lives_ok($$select public.record_finance_movement(pg_temp.tid(1),pg_temp.tid(216),jsonb_build_object('kind','refund','date','2026-09-13','accountId',pg_temp.tid(20),'amount','40','relatedMovementId',(select movement_id from public.finance_trip_entries where id=pg_temp.result(215))))$$,'partial studio refund');
select is((select net_amount from public.finance_trip_entry_values where id=pg_temp.result(215)),60::numeric,'refund lowers trip cost');
select is((select remaining_amount from public.finance_expected_balances where id=(select expected_item_id from public.finance_trip_entries where id=pg_temp.result(215))),0::numeric,'refund creates no phantom outgoing obligation');
select lives_ok($$select public.reverse_finance_movement(pg_temp.tid(1),pg_temp.tid(217),(select id from public.finance_movements where request_id=pg_temp.tid(216)),'2026-09-14','Refund entered twice')$$,'reverse refund');
select is((select net_amount from public.finance_trip_entry_values where id=pg_temp.result(215)),100::numeric,'reversed refund restores cost');
select is((select unapplied_amount from public.finance_payment_availability where id=(select movement_id from public.finance_trip_entries where id=pg_temp.result(215))),0::numeric,'restored trip cash stays reserved by canonical allocation');
select throws_like($$select public.release_finance_allocation(pg_temp.tid(1),pg_temp.tid(218),(select id from public.finance_allocations where expected_item_id=(select expected_item_id from public.finance_trip_entries where id=pg_temp.result(215)) and amount>0 limit 1),'Release')$$,'%finance_trip_expected_locked%','cash expense cannot be reused as another payment');
select lives_ok($$select pg_temp.entry(220,jsonb_build_object('employeeId','','amount','12.34','currency','PLN','accountId',pg_temp.tid(21),'fx',jsonb_build_object('rate','10.123456','source','manual','effectiveDate','2026-09-12')))$$,'foreign studio expense');
select is((select reporting_amount from public.finance_trip_entries where id=pg_temp.result(220)),124.92::numeric,'studio trip valuation copied from canonical ledger');
select throws_like($$select pg_temp.entry(221,'{"amount":"1.001"}')$$,'%finance_amount_invalid%','currency precision enforced');
select throws_like($$select pg_temp.entry(222,'{"currency":"PLN","fx":{"rate":"0","source":"manual","effectiveDate":"2026-09-12"}}')$$,'%finance_fx_required%','missing or invalid foreign valuation fails closed');
select throws_like($$select pg_temp.entry(223,'{"currency":"PLN","fx":{"rate":"10","source":"manual","effectiveDate":"2026-09-13"}}')$$,'%finance_fx_required%','FX must use original date');
select lives_ok($$update public.projects set status='completed',completed_at='2026-09-15' where id=pg_temp.tid(30)$$,'project completion preserves travel history');
select lives_ok($$update public.projects set status='archived',archived_at='2026-09-16' where id=pg_temp.tid(30)$$,'project archival preserves travel history');
select lives_ok($$select pg_temp.entry(224)$$,'archived project trip can finish financial reconciliation');
select is((select project_id from public.finance_trips where id=pg_temp.result(100)),pg_temp.tid(30),'project linkage retained');
select is((select count(*) from public.finance_project_items where project_id=pg_temp.tid(30)),0::bigint,'travel is not project contract revenue');
select throws_like($$insert into public.finance_trip_balances values(pg_temp.tid(1),pg_temp.result(100),pg_temp.tid(11),'UAH','outgoing',pg_temp.tid(999))$$,'%permission denied%','no direct settlement link mutation');
select throws_like($$delete from public.finance_trips where id=pg_temp.result(100)$$,'%permission denied%','trip cannot delete financial history');
select set_config('request.jwt.claim.sub',pg_temp.tid(11)::text,true);
select is((select count(*) from public.finance_trip_totals),0::bigint,'employee Finance denial');
select is((select count(*) from public.finance_trip_travelers),0::bigint,'traveler identity does not grant access');
select throws_like($$select pg_temp.trip(200)$$,'%finance_admin_required%','employee cannot write');
select set_config('request.jwt.claim.sub',pg_temp.tid(12)::text,true);
select is((select count(*) from public.finance_trip_entries),0::bigint,'other studio cannot read receipts');
select throws_like($$select pg_temp.entry(201)$$,'%finance_admin_required%','other studio cannot write');
select public.finalize_finance_setup(pg_temp.tid(2));
select public.save_finance_category(pg_temp.tid(2),pg_temp.tid(300),'{"name":"Business travel","direction":"outgoing","nature":"operating"}');
select public.save_finance_trip(pg_temp.tid(2),pg_temp.tid(301),'{"title":"Existing travel category","destination":"Kyiv","startsOn":"2026-09-12","endsOn":"2026-09-12","status":"active","travelers":[]}');
select lives_ok($$select public.record_finance_trip_entry(pg_temp.tid(2),pg_temp.tid(302),(select result_id from public.finance_planning_requests where studio_id=pg_temp.tid(2) and request_id=pg_temp.tid(301)),jsonb_build_object('kind','expense','expenseType','travel','amount','100','currency','UAH','date','2026-09-12','accountId',pg_temp.tid(22)))$$,'reuse existing custom travel category');
select is((select count(*) from public.finance_categories where name='Business travel'),1::bigint,'no duplicate travel category');
select ok((select custom_name from public.finance_categories where name='Business travel'),'existing category identity retained');
select set_config('request.jwt.claim.sub',pg_temp.tid(13)::text,true);
select throws_like($$select pg_temp.trip(202)$$,'%finance_admin_required%','inactive profile denial');
select set_config('request.jwt.claim.sub',pg_temp.tid(14)::text,true);
select throws_like($$select pg_temp.trip(203)$$,'%finance_admin_required%','inactive membership denial');
reset role;
set local role anon;
select throws_like($$select * from public.finance_trips$$,'%permission denied%','anonymous trip read denied');
select throws_like($$select pg_temp.trip(999)$$,'%permission denied%','anonymous trip RPC denied');
reset role;
select * from finish();
rollback;
