begin;
select no_plan();
create function pg_temp.gid(n integer) returns uuid language sql immutable as $$select ('68000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.studios(id,name) values(pg_temp.gid(1),'Group A'),(pg_temp.gid(2),'Group B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.gid(n),'authenticated','authenticated','group-'||n||'@test','{}','{}',now(),now() from generate_series(10,13)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.gid(n),'Group tester','group-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,13)n;
insert into public.studio_members(studio_id,user_id,system_role)
select pg_temp.gid(case when n=12 then 2 else 1 end),pg_temp.gid(n),case when n=11 then 'employee' else 'admin' end from generate_series(10,13)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.gid(1),'UAH','2026-01-01',pg_temp.gid(10)),(pg_temp.gid(2),'UAH','2026-01-01',pg_temp.gid(12));
insert into public.finance_accounts(studio_id,name,currency,opening_balance,created_by) values(pg_temp.gid(1),'Bank','UAH',10000,pg_temp.gid(10));
create function pg_temp.rule_input(group_id uuid default null) returns jsonb language sql as $$
select jsonb_build_object('kind','recurring','revision',0,'name','Rent','amount','1000','currency','UAH','categoryId',id,'intervalMonths',1,'payoutDay',5,'paymentMonthOffset',0,'effectiveFrom','2026-09-01','commitment','agreed','certainty','fixed','employerCostStatus','unknown','reason','Agreement','groupId',group_id) from public.finance_categories where studio_id=pg_temp.gid(1) and default_key='rent'$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.gid(12)::text,true);
select public.manage_finance_recurring_group(pg_temp.gid(2),'create',pg_temp.gid(22),'Foreign');
select set_config('request.jwt.claim.sub',pg_temp.gid(10)::text,true);
select public.finalize_finance_setup(pg_temp.gid(1));
select lives_ok($$select public.manage_finance_recurring_group(pg_temp.gid(1),'create',pg_temp.gid(20),'Office')$$,'admin creates studio group');
select lives_ok($$select public.manage_finance_recurring_group(pg_temp.gid(1),'create',pg_temp.gid(20),'Office')$$,'create retry is idempotent');
select throws_like($$select public.manage_finance_recurring_group(pg_temp.gid(1),'create',pg_temp.gid(23),'office')$$,'%duplicate key%','duplicate names are case-insensitive');
select public.manage_finance_recurring_group(pg_temp.gid(1),'create',pg_temp.gid(21),'Software');
select public.manage_finance_recurring_group(pg_temp.gid(1),'up',pg_temp.gid(21));
select is((select name from public.finance_recurring_groups where studio_id=pg_temp.gid(1) order by position limit 1),'Software','group order changes');
select public.manage_finance_recurring_group(pg_temp.gid(1),'rename',pg_temp.gid(20),'Office costs');
select is((select name from public.finance_recurring_groups where id=pg_temp.gid(20)),'Office costs','rename persists');
select lives_ok($$select public.save_finance_recurring_schedule(pg_temp.gid(1),pg_temp.gid(100),pg_temp.rule_input(pg_temp.gid(20)))$$,'new rule and organization save together');
select is((select group_id from public.finance_schedules where studio_id=pg_temp.gid(1)),pg_temp.gid(20),'new rule assigned');
reset role;
create temporary table grouping_snapshot as select (select jsonb_agg(to_jsonb(t) order by id) from public.finance_schedule_terms t where studio_id=pg_temp.gid(1)) terms,(select jsonb_agg(to_jsonb(i) order by id) from public.finance_expected_items i where studio_id=pg_temp.gid(1)) items,(select jsonb_agg(to_jsonb(o) order by id) from public.finance_obligations o where studio_id=pg_temp.gid(1)) obligations;
grant select on grouping_snapshot to authenticated;
set local role authenticated;
select public.manage_finance_recurring_group(pg_temp.gid(1),'assign',pg_temp.gid(21),null,(select id from public.finance_schedules where studio_id=pg_temp.gid(1)));
select is((select group_id from public.finance_schedules where studio_id=pg_temp.gid(1)),pg_temp.gid(21),'move is organization only');
select public.manage_finance_recurring_group(p_studio_id=>pg_temp.gid(1),p_operation=>'assign',p_schedule_id=>(select id from public.finance_schedules where studio_id=pg_temp.gid(1)));
select ok((select group_id is null from public.finance_schedules where studio_id=pg_temp.gid(1)),'omitted group means ungrouped');
select public.save_finance_recurring_schedule(pg_temp.gid(1),pg_temp.gid(100),pg_temp.rule_input(pg_temp.gid(20)));
select ok((select group_id is null from public.finance_schedules where studio_id=pg_temp.gid(1)),'save retry does not undo a later group move');
select throws_like($$select public.save_finance_recurring_schedule(pg_temp.gid(1),pg_temp.gid(100),pg_temp.rule_input(pg_temp.gid(21)))$$,'%finance_request_conflict%','retry cannot change original group payload');
select is((select jsonb_agg(to_jsonb(t) order by id) from public.finance_schedule_terms t where studio_id=pg_temp.gid(1)),(select terms from grouping_snapshot),'group moves preserve every term');
select is((select jsonb_agg(to_jsonb(i) order by id) from public.finance_expected_items i where studio_id=pg_temp.gid(1)),(select items from grouping_snapshot),'group moves preserve financial categories and expectations');
select is((select jsonb_agg(to_jsonb(o) order by id) from public.finance_obligations o where studio_id=pg_temp.gid(1)),(select obligations from grouping_snapshot),'group moves preserve obligation identity');
select is((select count(*) from public.finance_movements where studio_id=pg_temp.gid(1)),0::bigint,'group operations create no ledger entries');
select throws_like($$select public.save_finance_recurring_schedule(pg_temp.gid(1),pg_temp.gid(101),pg_temp.rule_input(pg_temp.gid(22)))$$,'%finance_group_invalid%','cross-studio group assignment denied before financial save');
select is((select count(*) from public.finance_schedules where studio_id=pg_temp.gid(1)),1::bigint,'failed grouped save leaves no partial schedule');
select throws_like($$select public.manage_finance_recurring_group(pg_temp.gid(1),'rename',pg_temp.gid(22),'Stolen')$$,'%finance_group_invalid%','cannot rename another studio group');
select throws_like($$update public.finance_schedules set group_id=pg_temp.gid(20)$$,'%permission denied%','direct financial schedule writes remain denied');
select throws_like($$insert into public.finance_recurring_groups(id,studio_id,name,position) values(pg_temp.gid(24),pg_temp.gid(1),'Bypass',8)$$,'%permission denied%','group writes require guarded operations');
select is((select count(*) from public.finance_recurring_groups where studio_id=pg_temp.gid(2)),0::bigint,'foreign groups hidden');
select set_config('request.jwt.claim.sub',pg_temp.gid(11)::text,true);
select is((select count(*) from public.finance_recurring_groups),0::bigint,'employee cannot read groups');
select throws_like($$select public.manage_finance_recurring_group(pg_temp.gid(1),'create',pg_temp.gid(25),'Denied')$$,'%finance_admin_required%','employee group RPC denied');
select throws_like($$select public.save_finance_recurring_schedule(pg_temp.gid(1),pg_temp.gid(102),'{}')$$,'%finance_admin_required%','employee grouped schedule RPC denied');
select set_config('request.jwt.claim.sub',pg_temp.gid(13)::text,true);
select throws_like($$select public.manage_finance_recurring_group(pg_temp.gid(1),'up',pg_temp.gid(20))$$,'%finance_admin_required%','inactive profile cannot organize groups');
set local role anon;
select throws_like($$select * from public.finance_recurring_groups$$,'%permission denied%','anonymous group reads denied');
select throws_like($$select public.manage_finance_recurring_group(pg_temp.gid(1),'up',pg_temp.gid(20))$$,'%permission denied%','anonymous group RPC denied');
reset role;
select * from finish();
rollback;
