begin;
select no_plan();
create function pg_temp.fid(n integer) returns uuid language sql immutable as $$select ('67000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.today() returns date language sql stable as $$select (now() at time zone 'Europe/Kyiv')::date$$;
create function pg_temp.month() returns date language sql stable as $$select date_trunc('month',pg_temp.today())::date$$;
insert into public.studios(id,name) values(pg_temp.fid(1),'Overview A'),(pg_temp.fid(2),'Overview B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.fid(n),'authenticated','authenticated','forecast-'||n||'@test','{}','{}',now(),now() from generate_series(10,14)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.fid(n),'Forecast tester','forecast-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,14)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.fid(case when n=12 then 2 else 1 end),pg_temp.fid(n),case when n=11 then 'employee' else 'admin' end,n<>14 from generate_series(10,14)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values
(pg_temp.fid(1),'UAH',(pg_temp.month()-interval '1 month')::date,pg_temp.fid(10)),(pg_temp.fid(2),'UAH',pg_temp.month(),pg_temp.fid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values
(pg_temp.fid(20),pg_temp.fid(1),'Bank','UAH',1000,pg_temp.fid(10)),(pg_temp.fid(21),pg_temp.fid(1),'Dollars','USD',100,pg_temp.fid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,created_by,status) values(pg_temp.fid(30),pg_temp.fid(1),'Forecast project',100,pg_temp.month(),pg_temp.fid(10),'active');
create function pg_temp.cat(key text,studio integer default 1) returns uuid language sql as $$select id from public.finance_categories where studio_id=pg_temp.fid(studio) and default_key=key$$;
create function pg_temp.value_opening(rate text default '39',source text default 'nbu',patch jsonb default '{}') returns void language sql as $$
select public.value_finance_opening(pg_temp.fid(1),pg_temp.fid(21),jsonb_build_object('currency','USD','reportingCurrency','UAH','openingAmount','100','date',(pg_temp.month()-interval '1 month')::date,'fx',jsonb_build_object('rate',rate,'source',source,'effectiveDate',(pg_temp.month()-interval '1 month')::date))||patch)$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.fid(10)::text,true);
select throws_like($$select public.finalize_finance_setup(pg_temp.fid(1))$$,'%finance_opening_fx_required%','draft cannot finalize while nonzero foreign opening has no valuation');
select throws_like($$select pg_temp.value_opening('0')$$,'%finance_opening_fx_invalid%','zero rate rejected');
select throws_like($$select pg_temp.value_opening('NaN')$$,'%finance_opening_fx_invalid%','NaN rejected');
select throws_like($$select pg_temp.value_opening('1.12345678901')$$,'%finance_opening_fx_invalid%','excess FX precision rejected');
select throws_like($$select pg_temp.value_opening('39','nbu',jsonb_build_object('fx',jsonb_build_object('rate','39','source','nbu','effectiveDate',pg_temp.today())))$$,'%finance_opening_fx_invalid%','today rate cannot masquerade as a cutover valuation');
select throws_like($$select pg_temp.value_opening('39','identity')$$,'%finance_opening_fx_invalid%','foreign opening cannot use identity fallback');
select lives_ok($$select pg_temp.value_opening()$$,'dated NBU valuation stored on draft');
select is((select opening_reporting_amount from public.finance_accounts where id=pg_temp.fid(21)),3900::numeric,'reporting opening calculated with exact numeric');
select is((select opening_fx_effective_date from public.finance_accounts where id=pg_temp.fid(21)),(pg_temp.month()-interval '1 month')::date,'effective date is financial cutover');
select is((select opening_valued_by from public.finance_accounts where id=pg_temp.fid(21)),pg_temp.fid(10),'verified actor recorded');
select public.save_finance_account(pg_temp.fid(1),'Renamed dollars','USD',100,pg_temp.fid(21));
select is((select opening_fx_rate from public.finance_accounts where id=pg_temp.fid(21)),39::numeric,'rename preserves valuation');
select public.save_finance_account(pg_temp.fid(1),'Renamed dollars','USD',101,pg_temp.fid(21));
select is((select opening_reporting_amount from public.finance_accounts where id=pg_temp.fid(21)),null::numeric,'draft opening amount correction clears stale valuation');
select throws_like($$select pg_temp.value_opening()$$,'%finance_setup_context_changed%','stale browser opening context rejected');
select public.save_finance_account(pg_temp.fid(1),'Renamed dollars','USD',100,pg_temp.fid(21));
select pg_temp.value_opening();
select public.save_finance_settings(pg_temp.fid(1),'EUR',(pg_temp.month()-interval '1 month')::date);
select is((select opening_fx_rate from public.finance_accounts where id=pg_temp.fid(21)),null::numeric,'draft reporting currency change clears valuation');
select throws_like($$select pg_temp.value_opening('39','nbu','{"reportingCurrency":"EUR"}')$$,'%finance_opening_fx_invalid%','NBU requires UAH reporting');
select public.save_finance_settings(pg_temp.fid(1),'UAH',(pg_temp.month()-interval '1 month')::date);
select pg_temp.value_opening('40','manual');
select public.save_finance_settings(pg_temp.fid(1),'UAH',pg_temp.month());
select is((select opening_fx_rate from public.finance_accounts where id=pg_temp.fid(21)),null::numeric,'draft cutover change clears valuation');
select public.save_finance_settings(pg_temp.fid(1),'UAH',(pg_temp.month()-interval '1 month')::date);
select pg_temp.value_opening();
select public.save_finance_account(pg_temp.fid(1),'Renamed dollars','EUR',100,pg_temp.fid(21));
select is((select opening_reporting_amount from public.finance_accounts where id=pg_temp.fid(21)),null::numeric,'draft account currency change invalidates valuation');
select public.save_finance_account(pg_temp.fid(1),'Renamed dollars','USD',100,pg_temp.fid(21));
select pg_temp.value_opening();
select is((select opening_reporting_amount from public.finance_accounts where id=pg_temp.fid(20)),null::numeric,'same-currency opening requires no separate FX fields');
select public.save_finance_account(pg_temp.fid(1),'Zero euros','EUR',0);
select is((select opening_reporting_amount from public.finance_accounts where name='Zero euros'),null::numeric,'zero foreign opening requires no invented rate');
select public.set_finance_account_archived(pg_temp.fid(1),pg_temp.fid(21),true);
select lives_ok($$select public.finalize_finance_setup(pg_temp.fid(1))$$,'all required valuations allow setup finalization including archived openings');
select is((select opening_balance from public.finance_accounts where id=pg_temp.fid(21)),100::numeric,'original foreign opening remains authoritative');
select lives_ok($$select pg_temp.value_opening()$$,'identical finalized retry is idempotent');
select throws_like($$select pg_temp.value_opening('42')$$,'%finance_opening_valuation_locked%','later rate cannot rewrite finalized opening');
select throws_like($$select pg_temp.value_opening('39','manual')$$,'%finance_opening_valuation_locked%','source provenance cannot be rewritten');
select is((select count(*) from public.finance_movements),0::bigint,'opening valuation creates no movement');
select is((select count(*) from public.finance_movement_entries),0::bigint,'opening valuation creates no ledger entry');
select is((select count(*) from public.finance_planning_actuals),0::bigint,'opening valuation creates no cash-flow actual');
select is((public.get_finance_overview(pg_temp.fid(1))->'history'->0->>'amount')::numeric,4900::numeric,'history starts with base and foreign frozen openings');
select is((public.get_finance_overview(pg_temp.fid(1))->>'historyIncomplete')::boolean,false,'complete valued openings restore history');
select public.set_finance_account_archived(pg_temp.fid(1),pg_temp.fid(21),false);
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(500),jsonb_build_object('kind','incoming','date',pg_temp.today(),'amount','10','accountId',pg_temp.fid(21),'categoryId',pg_temp.cat('project_payments'),'fx',jsonb_build_object('rate','40','source','manual','effectiveDate',pg_temp.today())));
select is((public.get_finance_overview(pg_temp.fid(1))->'history'->-1->>'amount')::numeric,5300::numeric,'historical movement adds its own frozen rate to frozen opening');
select is((public.get_finance_overview(pg_temp.fid(1))->>'netFlow')::numeric,400::numeric,'opening excluded from net cash flow');
select is((public.get_finance_overview(pg_temp.fid(1),'6','confirmed',jsonb_build_array(jsonb_build_object('currency','USD','rate','50','source','manual','effectiveDate',pg_temp.today())))->'forecast'->>'cashBase')::numeric,6500::numeric,'current cash still uses report-date FX');
select is((public.get_finance_overview(pg_temp.fid(1),'6','confirmed',jsonb_build_array(jsonb_build_object('currency','USD','rate','50','source','manual','effectiveDate',pg_temp.today())))->'history'->-1->>'amount')::numeric,5300::numeric,'later report rates never alter historical consolidated cash');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(21)),110::numeric,'native balance arithmetic unchanged');
select throws_like($$update public.finance_accounts set opening_fx_rate=50$$,'%permission denied%','no direct admin write grant');
reset role;
select throws_like($$update public.finance_accounts set opening_fx_rate=50 where id=pg_temp.fid(21)$$,'%finance_opening_valuation_locked%','trigger also protects finalized valuation against privileged edits');
select throws_like($$update public.finance_accounts set opening_reporting_amount=null,opening_fx_rate=null,opening_fx_source=null,opening_fx_effective_date=null,opening_valued_at=null,opening_valued_by=null where id=pg_temp.fid(21)$$,'%finance_opening_valuation_locked%','cannot clear frozen valuation for a second completion');
-- Simulate rows predating this migration; never invent rates for these setups.
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.fid(25),pg_temp.fid(2),'Legacy dollars','USD',5000,pg_temp.fid(12));
alter table public.finance_settings disable trigger guard_finance_opening_finalization;
update public.finance_settings set finalized_at=now(),finalized_by=pg_temp.fid(12) where studio_id=pg_temp.fid(2);
alter table public.finance_settings enable trigger guard_finance_opening_finalization;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.fid(12)::text,true);
select is((public.get_finance_overview(pg_temp.fid(2))->>'historyIncomplete')::boolean,true,'legacy finalized opening stays explicitly incomplete');
select public.set_finance_account_archived(pg_temp.fid(2),pg_temp.fid(25),true);
select lives_ok($$select public.value_finance_opening(pg_temp.fid(2),pg_temp.fid(25),jsonb_build_object('currency','USD','reportingCurrency','UAH','openingAmount','5000','date',pg_temp.month(),'fx',jsonb_build_object('rate','39.123456789','source','manual','effectiveDate',pg_temp.month())))$$,'explicit one-time manual completion works for archived legacy account');
select is((public.get_finance_overview(pg_temp.fid(2))->'history'->0->>'amount')::numeric,195617.28::numeric,'manual historical valuation rounds once to reporting precision');
select is((select opening_balance from public.finance_accounts where id=pg_temp.fid(25)),5000::numeric,'legacy amount not altered');
select is((select count(*) from public.finance_movements),0::bigint,'legacy completion has no cash activity');
select throws_like($$select public.value_finance_opening(pg_temp.fid(2),pg_temp.fid(21),'{}')$$,'%finance_account_unavailable%','foreign account rejected');
select throws_like($$select pg_temp.value_opening()$$,'%finance_admin_required%','foreign studio rejected');
select set_config('request.jwt.claim.sub',pg_temp.fid(11)::text,true);
select throws_like($$select pg_temp.value_opening()$$,'%finance_admin_required%','employee rejected');
select is((select count(*) from public.finance_accounts),0::bigint,'opening valuation metadata protected by existing RLS');
select set_config('request.jwt.claim.sub',pg_temp.fid(13)::text,true);
select throws_like($$select pg_temp.value_opening()$$,'%finance_admin_required%','inactive profile rejected');
select set_config('request.jwt.claim.sub',pg_temp.fid(14)::text,true);
select throws_like($$select pg_temp.value_opening()$$,'%finance_admin_required%','inactive membership rejected');
set local role anon;
select throws_like($$select public.value_finance_opening(pg_temp.fid(1),pg_temp.fid(21),'{}')$$,'%permission denied%','anonymous rejected');
select * from finish();
rollback;
