begin;
select no_plan();
create function pg_temp.fid(n integer) returns uuid language sql immutable as $$select ('67000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.today() returns date language sql stable as $$select (now() at time zone 'Europe/Kyiv')::date$$;
create function pg_temp.month() returns date language sql stable as $$select date_trunc('month',pg_temp.today())::date$$;
insert into public.studios(id,name) values(pg_temp.fid(1),'Overview A'),(pg_temp.fid(2),'Overview B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.fid(n),'authenticated','authenticated','forecast-'||n||'@test','{}','{}',now(),now() from generate_series(10,14)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.fid(n),'Forecast tester','forecast-'||n||'@test',case when n=11 then 'employee' else 'admin' end,n<>13 from generate_series(10,14)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active)
select pg_temp.fid(case when n=12 then 2 else 1 end),pg_temp.fid(n),case when n=11 then 'employee' else 'admin' end,n<>14 from generate_series(10,14)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values
(pg_temp.fid(1),'UAH',(pg_temp.month()-interval '1 month')::date,pg_temp.fid(10)),(pg_temp.fid(2),'UAH',pg_temp.month(),pg_temp.fid(12));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values
(pg_temp.fid(20),pg_temp.fid(1),'Bank','UAH',1000,pg_temp.fid(10)),(pg_temp.fid(21),pg_temp.fid(1),'Dollars','USD',100,pg_temp.fid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,created_by,status) values(pg_temp.fid(30),pg_temp.fid(1),'Forecast project',100,pg_temp.month(),pg_temp.fid(10),'active');
create function pg_temp.cat(key text,studio integer default 1) returns uuid language sql as $$select id from public.finance_categories where studio_id=pg_temp.fid(studio) and default_key=key$$;
create function pg_temp.result(n integer) returns uuid language sql as $$select result_id from public.finance_planning_requests where studio_id=pg_temp.fid(1) and request_id=pg_temp.fid(n)$$;
create function pg_temp.fx(rate text default '40') returns jsonb language sql as $$select jsonb_build_array(jsonb_build_object('currency','USD','rate',rate,'source','manual','effectiveDate',pg_temp.today()))$$;
create function pg_temp.report(scenario text default 'confirmed',fx jsonb default '[]',horizon text default '6') returns jsonb language sql as $$select public.calculate_finance_forecast(pg_temp.fid(1),horizon,scenario,fx)$$;
create function pg_temp.budget(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_budget(pg_temp.fid(1),pg_temp.fid(n),jsonb_build_object('categoryId',pg_temp.cat('project_payments'),'year',extract(year from pg_temp.today()),'revision',0,'months',to_jsonb(array_fill(100000,ARRAY[12])),'reason','Approved annual plan')||patch)$$;
create function pg_temp.expected(n integer,patch jsonb default '{}') returns uuid language sql as $$select public.save_finance_expected_item(pg_temp.fid(1),pg_temp.fid(n),jsonb_build_object('direction','incoming','amount','100000','currency','UAH','categoryId',pg_temp.cat('project_payments'),'description','Contract receipt','dueDate',pg_temp.today(),'expectedDate',pg_temp.today(),'commitment','agreed','certainty','fixed')||patch)$$;
-- Legacy finalized setup intentionally lacks opening FX, as before Phase 6B.1.
alter table public.finance_settings disable trigger guard_finance_opening_finalization;
update public.finance_settings set finalized_at=now(),finalized_by=pg_temp.fid(10) where studio_id=pg_temp.fid(1);
alter table public.finance_settings enable trigger guard_finance_opening_finalization;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.fid(10)::text,true);
select public.finalize_finance_setup(pg_temp.fid(1));

create function pg_temp.overview(scenario text default 'confirmed',fx jsonb default '[]',horizon text default '6',period text default '3') returns jsonb language sql as $$select public.get_finance_overview(pg_temp.fid(1),horizon,scenario,fx,period)$$;
select is(pg_temp.overview()->'forecast',pg_temp.report(),'Overview preserves the complete canonical forecast');
select is((pg_temp.overview()->'forecast'->>'cashIncomplete')::boolean,true,'unvalued cash visibly incomplete');
select is((pg_temp.overview()->>'historyIncomplete')::boolean,true,'foreign opening has no invented historical valuation');
select ok(not exists(select 1 from jsonb_array_elements(pg_temp.overview()->'history') p where p->>'amount' is not null),'unknown history is not shown as zero');
select pg_temp.expected(200,'{"established":true}');
select public.record_finance_expected_payment(pg_temp.fid(1),pg_temp.fid(201),pg_temp.result(200),jsonb_build_object('kind','incoming','date',pg_temp.today(),'amount','40000','accountId',pg_temp.fid(20),'categoryId',pg_temp.cat('project_payments')),40000);
select pg_temp.expected(202,'{"amount":"100","commitment":"tentative","description":"Planned"}');
select pg_temp.expected(203,'{"amount":"50","certainty":"estimated"}');
select pg_temp.expected(204,'{"established":true,"amount":"75","dueDate":"","expectedDate":""}');
select pg_temp.expected(205,jsonb_build_object('established',true,'amount','25','dueDate',pg_temp.today()-1,'expectedDate',''));
select pg_temp.expected(206,jsonb_build_object('direction','outgoing','categoryId',pg_temp.cat('rent'),'amount','200','dueDate',pg_temp.today()-1,'expectedDate',''));
select pg_temp.expected(207,jsonb_build_object('established',true,'currency','USD','amount','2','dueDate',pg_temp.today()+500,'expectedDate',pg_temp.today()+500));
select is((pg_temp.overview('confirmed',pg_temp.fx())->>'receivableTotal')::numeric,60180::numeric,'all-date receivables include partial remaining, undated, overdue and far future fixed amounts, exclude estimates and tentative');
select is((pg_temp.overview()->>'receivablesIncomplete')::boolean,true,'outside-horizon foreign receivables require FX');
select is(pg_temp.overview()->'requiredCurrencies','["USD"]'::jsonb,'currency discovery includes receivables outside forecast');
select is((pg_temp.overview('confirmed',pg_temp.fx())->>'receivablesIncomplete')::boolean,false,'explicit FX completes receivable valuation');
select is((pg_temp.overview()->>'outgoingTotal')::numeric,200::numeric,'overdue outgoing contributes remaining exposure today');
select is((select i->>'dueDate' from jsonb_array_elements(pg_temp.overview()->'forecast'->'items') i where i->>'id'=pg_temp.result(206)::text),(pg_temp.today()-1)::text,'overdue due date retained for display');
select is((pg_temp.overview()->>'netFlow')::numeric,40000::numeric,'partial payment enters actual once');
select is((pg_temp.overview('confirmed',pg_temp.fx())->'projection'->-1->>'amount')::numeric,104850::numeric,'cash base includes actual once and projection adds only dated remaining');
select is((pg_temp.overview('planned',pg_temp.fx())->'projection'->-1->>'amount')::numeric,104950::numeric,'planned adds tentative amount only');
select is((pg_temp.overview('confirmed',pg_temp.fx())->'projection'->-1->>'amount')::numeric,(pg_temp.report('confirmed',pg_temp.fx())->'months'->-1->>'closing')::numeric,'daily projection final balance equals existing monthly forecast');
select pg_temp.budget(210);
select is((select (c->>'actual')::numeric from jsonb_array_elements(pg_temp.overview()->'categories') c where c->>'id'=pg_temp.cat('project_payments')::text),40000::numeric,'category actual reconciles with Phase 6A');
select is((select (c->>'forecast')::numeric from jsonb_array_elements(pg_temp.overview()->'categories') c where c->>'id'=pg_temp.cat('project_payments')::text),100050::numeric,'full period is actual plus dated remaining, not original expected');
select is((select (c->>'budget')::numeric from jsonb_array_elements(pg_temp.overview('confirmed','[]','3')->'categories') c where c->>'id'=pg_temp.cat('project_payments')::text),(select sum((c->>'budget')::numeric) from jsonb_array_elements(pg_temp.report('confirmed','[]','3')->'comparisons') c where c->>'category_id'=pg_temp.cat('project_payments')::text),'category budget is same monthly baseline');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(220),jsonb_build_object('kind','transfer','category','Transfer','date',pg_temp.today(),'amount','10','accountId',pg_temp.fid(21),'destinationId',pg_temp.fid(20),'receivedAmount','390','fee','1','fx',jsonb_build_object('rate','40','source','manual','effectiveDate',pg_temp.today())));
select is((pg_temp.overview()->>'netFlow')::numeric,39960::numeric,'transfer principal excluded; operating fee retained');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(221),jsonb_build_object('kind','owner_withdrawal','date',pg_temp.today(),'amount','500','accountId',pg_temp.fid(20),'categoryId',pg_temp.cat('owner_distribution')));
select is((pg_temp.overview()->>'netFlow')::numeric,39460::numeric,'owner withdrawal reduces total non-transfer flow');
select is((select sum((f->>'amount')::numeric) from jsonb_array_elements(pg_temp.overview()->'flows') f where f->>'nature'='operating' and f->>'direction'='outgoing'),40::numeric,'owner withdrawal not operating expense');
select is((select sum((f->>'amount')::numeric) from jsonb_array_elements(pg_temp.overview()->'flows') f where f->>'nature'='owner_distribution'),500::numeric,'owner classification remains visible');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(222),jsonb_build_object('kind','incoming','date',pg_temp.today(),'amount','2','accountId',pg_temp.fid(21),'categoryId',pg_temp.cat('project_payments'),'fx',jsonb_build_object('rate','39','source','manual','effectiveDate',pg_temp.today())));
select is((pg_temp.overview('confirmed',pg_temp.fx('50'))->>'netFlow')::numeric,39538::numeric,'forecast FX never revalues historical cash flow');
select is((select sum((a->>'amount')::numeric) from jsonb_array_elements(pg_temp.overview('confirmed',pg_temp.fx())->'accounts') a),(pg_temp.report('confirmed',pg_temp.fx())->>'cashBase')::numeric,'account breakdown reconciles exactly with canonical cash base');
select is(jsonb_array_length(pg_temp.overview('confirmed','[]','3')->'forecast'->'months'),3,'3-month horizon');
select is(jsonb_array_length(pg_temp.overview('confirmed','[]','6')->'forecast'->'months'),6,'6-month horizon');
select is(jsonb_array_length(pg_temp.overview('confirmed','[]','12')->'forecast'->'months'),12,'12-month horizon');
select is(pg_temp.overview('confirmed','[]','year')->'forecast'->>'through',make_date(extract(year from pg_temp.today())::integer,12,31)::text,'year-end horizon');
select is(pg_temp.overview('confirmed','[]','6','month')->>'actualFrom',pg_temp.month()::text,'actual period independent of forecast horizon');
select throws_like($$select pg_temp.overview('confirmed','[]','6','bad')$$,'%finance_input_invalid%','invalid actual period rejected');
select throws_like($$select public.get_finance_overview(pg_temp.fid(2))$$,'%finance_admin_required%','foreign studio rejected');
select set_config('request.jwt.claim.sub',pg_temp.fid(11)::text,true);
select throws_like($$select pg_temp.overview()$$,'%finance_admin_required%','employee rejected');
select set_config('request.jwt.claim.sub',pg_temp.fid(13)::text,true);
select throws_like($$select pg_temp.overview()$$,'%finance_admin_required%','inactive profile rejected');
select set_config('request.jwt.claim.sub',pg_temp.fid(14)::text,true);
select throws_like($$select pg_temp.overview()$$,'%finance_admin_required%','inactive membership rejected');
set local role anon;
select throws_like($$select public.get_finance_overview(pg_temp.fid(1))$$,'%permission denied%','anonymous rejected');
reset role;
-- A base-currency-only studio has complete historical cash, including the opening and transfers.
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.fid(25),pg_temp.fid(2),'Bank B','UAH',1000,pg_temp.fid(12));
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.fid(12)::text,true);
select public.finalize_finance_setup(pg_temp.fid(2));
select public.record_finance_movement(pg_temp.fid(2),pg_temp.fid(230),jsonb_build_object('kind','incoming','date',pg_temp.today(),'amount','200','accountId',pg_temp.fid(25),'categoryId',pg_temp.cat('project_payments',2)));
select is((public.get_finance_overview(pg_temp.fid(2))->'history'->-1->>'amount')::numeric,1200::numeric,'today history includes opening and recorded cash');
select is((public.get_finance_overview(pg_temp.fid(2))->>'netFlow')::numeric,200::numeric,'opening excluded from actual flows');
select is((public.get_finance_overview(pg_temp.fid(2))->'lowPoint'->>'amount')::numeric,1200::numeric,'without future sources projection remains flat, never fabricates sales');
select public.save_finance_expected_item(pg_temp.fid(2),pg_temp.fid(231),jsonb_build_object('direction','outgoing','amount','1500','currency','UAH','categoryId',pg_temp.cat('rent',2),'description','Pressure','expectedDate',pg_temp.today()+1,'commitment','agreed','certainty','fixed'));
select public.save_finance_expected_item(pg_temp.fid(2),pg_temp.fid(232),jsonb_build_object('direction','incoming','amount','2000','currency','UAH','categoryId',pg_temp.cat('project_payments',2),'description','Later receipt','expectedDate',pg_temp.today()+2,'commitment','agreed','certainty','fixed'));
select is((public.get_finance_overview(pg_temp.fid(2))->'lowPoint'->>'amount')::numeric,(-300)::numeric,'daily low point exposes pressure hidden by later monthly receipts');
select is(public.get_finance_overview(pg_temp.fid(2))->'lowPoint'->>'date',(pg_temp.today()+1)::text,'daily low point preserves source date precision');
select is((public.get_finance_overview(pg_temp.fid(2))->'projection'->-1->>'amount')::numeric,1700::numeric,'later receipts restore closing cash without hiding low point');
select is(public.get_finance_overview(pg_temp.fid(2))->>'actualFrom',pg_temp.month()::text,'history clipped to cutover');
select * from finish();
rollback;
