begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.fid(n integer) returns uuid language sql immutable as $$select ('6f000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.day(n integer default 0) returns date language sql stable as $$select (now() at time zone 'Europe/Kyiv')::date+n$$;
insert into public.studios(id,name) values(pg_temp.fid(1),'Movement corrections'),(pg_temp.fid(2),'Other studio');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.fid(n),'authenticated','authenticated','correction-'||n||'@test','{}','{}',now(),now() from generate_series(10,12)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.fid(n),'Correction tester','correction-'||n||'@test',case when n=11 then 'employee' else 'admin' end,true from generate_series(10,12)n;
insert into public.studio_members(studio_id,user_id,system_role,is_active) values
(pg_temp.fid(1),pg_temp.fid(10),'admin',true),(pg_temp.fid(1),pg_temp.fid(11),'employee',true),(pg_temp.fid(2),pg_temp.fid(12),'admin',true);
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.fid(1),'UAH',pg_temp.day(-10),pg_temp.fid(10));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values
(pg_temp.fid(20),pg_temp.fid(1),'Bank','UAH',1000,pg_temp.fid(10)),(pg_temp.fid(21),pg_temp.fid(1),'Cash','UAH',200,pg_temp.fid(10)),
(pg_temp.fid(22),pg_temp.fid(1),'Dollars','USD',0,pg_temp.fid(10));
create function pg_temp.cat(k text) returns uuid language sql as $$select id from public.finance_categories where studio_id=pg_temp.fid(1) and default_key=k$$;
create function pg_temp.input(amount text,day date,account integer default 20,kind text default 'incoming',patch jsonb default '{}') returns jsonb language sql as $$
select jsonb_build_object('kind',kind,'date',day,'accountId',pg_temp.fid(account),'amount',amount,'category','Actual','categoryId',pg_temp.cat(case when kind='incoming' then 'other_income' else 'other_expense' end),'description','Actual')||patch;
$$;
create function pg_temp.mid(request integer) returns uuid language sql as $$select id from public.finance_movements where studio_id=pg_temp.fid(1) and request_id=pg_temp.fid(request)$$;
select set_config('request.jwt.claim.sub',pg_temp.fid(10)::text,true);
set local role authenticated;
select public.finalize_finance_setup(pg_temp.fid(1));
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(100),pg_temp.input('100',pg_temp.day(-9)));
select public.save_finance_expected_item(pg_temp.fid(1),pg_temp.fid(90),jsonb_build_object('direction','incoming','amount','100','currency','UAH','categoryId',pg_temp.cat('other_income'),'description','Invoice','commitment','agreed','certainty','fixed','established',true));
select public.allocate_finance_payment(pg_temp.fid(1),pg_temp.fid(91),(select id from public.finance_expected_items where description='Invoice' and studio_id=pg_temp.fid(1)),pg_temp.mid(100),100);
select lives_ok($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(101),pg_temp.mid(100),pg_temp.input('150',pg_temp.day(-11),21))$$,'amount/account/date corrected atomically across cutover');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(20)),1000::numeric,'original account effect cancelled');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(21)),200::numeric,'corrected pre-cutover date does not change cash stock');
select is((select count(*) from public.finance_current_movements where studio_id=pg_temp.fid(1)),1::bigint,'only replacement appears normally');
select is((select id from public.finance_current_movements where studio_id=pg_temp.fid(1)),pg_temp.mid(101),'replacement is the visible event');
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1)),150::numeric,'historical report contains corrected economic effect');
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1) and financial_date=pg_temp.day(-9)),0::numeric,'original effect neutralized on original date');
select is((select settled_amount from public.finance_expected_balances where studio_id=pg_temp.fid(1) and description='Invoice'),0::numeric,'existing reversal releases settlement for review');
select is((select unapplied_amount from public.finance_payment_availability where id=pg_temp.mid(101)),150::numeric,'corrected payment is available for matching');
select ok(exists(select 1 from public.finance_actionable_unapplied where id=pg_temp.mid(101)),'released payment replacement stays visible for rematching');
select is(cardinality(public.get_finance_movement_history_ids(pg_temp.fid(1),pg_temp.mid(101))),3,'original and technical reversal recoverable with replacement');
select ok(pg_temp.mid(100)=any(public.get_finance_movement_history_ids(pg_temp.fid(1),pg_temp.mid(101))),'history retains immutable original');
select is((select amount from public.finance_movement_entries where movement_id=pg_temp.mid(100) and entry_role='primary'),100::numeric,'original entry never changes');
select is((select financial_date from public.finance_movements where related_movement_id=pg_temp.mid(100) and kind='reversal'),pg_temp.day(-9),'technical cancellation uses original date');
select lives_ok($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(102),pg_temp.mid(101),pg_temp.input('175',pg_temp.day(-5)))$$,'replacement can be corrected again');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(20)),1175::numeric,'only newest correction affects current balance');
select is((select sum(amount) from public.finance_planning_actuals where studio_id=pg_temp.fid(1)),175::numeric,'repeated correction never double counts');
select is(cardinality(public.get_finance_movement_history_ids(pg_temp.fid(1),pg_temp.mid(100))),5,'history follows full chain from original');
select is((select count(*) from public.finance_current_movements where studio_id=pg_temp.fid(1)),1::bigint,'all technical and superseded versions stay hidden');
select lives_ok($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(102),pg_temp.mid(101),pg_temp.input('175',pg_temp.day(-5)))$$,'retry recovers existing result');
select is((select count(*) from public.finance_movements where studio_id=pg_temp.fid(1)),5::bigint,'retry creates no second pair');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(102),pg_temp.mid(101),pg_temp.input('176',pg_temp.day(-5)))$$,'%finance_request_conflict%','changed retry rejected');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(103),pg_temp.mid(100),pg_temp.input('200',pg_temp.day()))$$,'%finance_already_reversed%','stale original cannot start another branch');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(104),pg_temp.mid(102),pg_temp.input('-1',pg_temp.day()))$$,'%finance_input_invalid%','invalid replacement rolls back its reversal');
select is((select count(*) from public.finance_movement_corrections where studio_id=pg_temp.fid(1)),2::bigint,'failed correction creates no linkage');
select ok(exists(select 1 from public.finance_current_movements where id=pg_temp.mid(102)),'failed replacement leaves current version visible');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(110),pg_temp.input('25',pg_temp.day(-1),20,'refund',jsonb_build_object('relatedMovementId',pg_temp.mid(102))));
select is((select count(*) from public.finance_current_movements where studio_id=pg_temp.fid(1)),2::bigint,'actual refund remains a separate visible movement');
select is((select financial_date from public.finance_current_movements where id=pg_temp.mid(110)),pg_temp.day(-1),'real refund keeps actual later date');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(20)),1150::numeric,'refund has real opposite cash effect');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(111),pg_temp.mid(102),pg_temp.input('190',pg_temp.day(-5)))$$,'%finance_reverse_refunds_first%','existing real refund guard preserved');
select lives_ok($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(112),pg_temp.mid(110),pg_temp.input('20',pg_temp.day(-2),20,'refund',jsonb_build_object('relatedMovementId',pg_temp.mid(102))))$$,'refund recording itself can be corrected immutably');
select is((select count(*) from public.finance_current_movements where studio_id=pg_temp.fid(1)),2::bigint,'corrected refund stays visible without technical records');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(20)),1155::numeric,'corrected actual refund counts once');
select is((select net_amount from public.finance_payment_availability where id=pg_temp.mid(102)),155::numeric,'refund principal limit follows corrected refund');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(120),pg_temp.input('10',pg_temp.day(-4),20,'transfer',jsonb_build_object('destinationId',pg_temp.fid(21),'receivedAmount','10','fee','2')));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(121),pg_temp.mid(120),pg_temp.input('15',pg_temp.day(-3),20,'transfer',jsonb_build_object('destinationId',pg_temp.fid(21),'receivedAmount','15','fee','3')));
select is((select sum(reporting_amount) from public.finance_cash_effects where studio_id=pg_temp.fid(1) and entry_role='fee'),(-3)::numeric,'transfer correction cancels original fee too');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(21)),215::numeric,'transfer destination counts corrected amount once');
select public.record_finance_movement(pg_temp.fid(1),pg_temp.fid(130),pg_temp.input('10',pg_temp.day(-4),22,'incoming',jsonb_build_object('fx',jsonb_build_object('rate','40','source','manual','effectiveDate',pg_temp.day(-4)))));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(131),pg_temp.mid(130),pg_temp.input('12',pg_temp.day(-3),22,'incoming',jsonb_build_object('fx',jsonb_build_object('rate','42','source','manual','effectiveDate',pg_temp.day(-3)))));
select is((select sum(reporting_amount) from public.finance_cash_effects where studio_id=pg_temp.fid(1) and account_id=pg_temp.fid(22)),504::numeric,'technical reversal cancels original FX while replacement uses corrected date FX');
select is((select fx_rate from public.finance_movement_entries e join public.finance_movements m on m.id=e.movement_id where m.related_movement_id=pg_temp.mid(130) and m.kind='reversal'),40::numeric,'reversal never revalues original');
select public.reverse_finance_movement(pg_temp.fid(1),pg_temp.fid(132),pg_temp.mid(131),pg_temp.day(-3),'Entered by mistake');
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(22)),0::numeric,'storno removes financial effect');
select ok(not exists(select 1 from public.finance_current_movements where id=pg_temp.mid(131)),'storno source disappears normally');
select is(cardinality(public.get_finance_movement_history_ids(pg_temp.fid(1),pg_temp.mid(131))),4,'final storno remains recoverable with correction chain');
select public.record_finance_account_balance(pg_temp.fid(1),pg_temp.fid(150),jsonb_build_object('kind','balance_adjustment','accountId',pg_temp.fid(21),'date',pg_temp.day(-2),'amount','220'));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(151),pg_temp.mid(150),pg_temp.input('-7',pg_temp.day(-1),21,'balance_adjustment'));
select is((select recorded_balance from public.finance_account_balances where id=pg_temp.fid(21)),208::numeric,'balance correction edits signed delta without recapturing current stock');
select ok(not exists(select 1 from public.finance_planning_actuals where studio_id=pg_temp.fid(1) and nature='balance'),'balance corrections remain outside income and expenses');
select public.create_finance_account_with_opening(pg_temp.fid(1),pg_temp.fid(160),jsonb_build_object('name','Later account','currency','UAH','date',pg_temp.day(-2),'openingBalance','50'));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(161),pg_temp.mid(160),pg_temp.input('40',pg_temp.day(-1),(20),'account_opening',jsonb_build_object('accountId',(select id from public.finance_accounts where studio_id=pg_temp.fid(1) and name='Later account'))));
select is((select recorded_balance from public.finance_account_balances where studio_id=pg_temp.fid(1) and name='Later account'),40::numeric,'dated opening can be corrected on its existing account');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(162),pg_temp.mid(161),pg_temp.input('30',pg_temp.day(),20,'account_opening'))$$,'%finance_opening_unavailable%','opening cannot move to an account with existing stock or history');
reset role;
insert into public.finance_trips(id,studio_id,title,destination,starts_on,ends_on,created_by)
values(pg_temp.fid(30),pg_temp.fid(1),'Correction trip','Kyiv',pg_temp.day(-6),pg_temp.day(-1),pg_temp.fid(10));
insert into public.finance_trip_travelers(studio_id,trip_id,employee_id,employee_name)
values(pg_temp.fid(1),pg_temp.fid(30),pg_temp.fid(11),'Traveler');
set local role authenticated;
select public.record_finance_trip_entry(pg_temp.fid(1),pg_temp.fid(170),pg_temp.fid(30),jsonb_build_object('kind','expense','expenseType','travel','label','Travel','date',pg_temp.day(-6),'amount','7','currency','UAH','accountId',pg_temp.fid(20)));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(171),pg_temp.mid(170),pg_temp.input('12',pg_temp.day(-3),21,'outgoing',jsonb_build_object('categoryId',pg_temp.cat('business_travel'))));
select is((select sum(net_amount) from public.finance_trip_entry_values where trip_id=pg_temp.fid(30)),12::numeric,'trip expense context follows corrected payment');
select is((select count(*) from public.finance_trip_entries where trip_id=pg_temp.fid(30)),2::bigint,'trip snapshots remain immutable with replacement');
select is((select unapplied_amount from public.finance_payment_availability where id=pg_temp.mid(171)),0::numeric,'trip replacement uses existing whole-payment reconciliation');
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(172),pg_temp.mid(171),pg_temp.input('15',pg_temp.day(-1),20,'outgoing',jsonb_build_object('categoryId',pg_temp.cat('business_travel'))));
select is((select sum(net_amount) from public.finance_trip_entry_values where trip_id=pg_temp.fid(30)),15::numeric,'repeated trip correction never double counts');
select ok(exists(select 1 from public.finance_current_movements where id=pg_temp.mid(172)) and not exists(select 1 from public.finance_current_movements where id in(pg_temp.mid(170),pg_temp.mid(171))),'only latest trip cash appears normally');
select public.record_finance_trip_entry(pg_temp.fid(1),pg_temp.fid(180),pg_temp.fid(30),jsonb_build_object('kind','advance','expenseType','other','date',pg_temp.day(-4),'amount','20','currency','UAH','accountId',pg_temp.fid(20),'employeeId',pg_temp.fid(11)));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(181),pg_temp.mid(180),pg_temp.input('30',pg_temp.day(-2),21,'outgoing',jsonb_build_object('categoryId',pg_temp.cat('business_travel'))));
select is((select sum(net_amount) from public.finance_trip_entry_values where trip_id=pg_temp.fid(30) and kind='advance'),30::numeric,'trip advance follows corrected amount');
select is((select unapplied_amount from public.finance_payment_availability where id=pg_temp.mid(181)),0::numeric,'corrected advance remains reserved for trip');
select public.record_finance_trip_entry(pg_temp.fid(1),pg_temp.fid(190),pg_temp.fid(30),jsonb_build_object('kind','expense','expenseType','meals','date',pg_temp.day(-4),'amount','20','currency','UAH','accountId',pg_temp.fid(20),'dailyRate','10','dayCount','2','coveredTravelerIds',jsonb_build_array(pg_temp.fid(11))));
select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(191),pg_temp.mid(190),pg_temp.input('20',pg_temp.day(-2),21,'outgoing',jsonb_build_object('categoryId',pg_temp.cat('business_travel'))));
select is((select count(*) from public.finance_trip_entry_travelers t join public.finance_trip_entries e on e.id=t.entry_id where e.movement_id=pg_temp.mid(191)),1::bigint,'per-diem traveler coverage survives supported correction');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(192),pg_temp.mid(191),pg_temp.input('30',pg_temp.day(),21,'outgoing',jsonb_build_object('categoryId',pg_temp.cat('business_travel'))))$$,'%finance_trip_edit_unavailable%','per-diem amount changes require its existing rate/day editor');
select ok(exists(select 1 from public.finance_current_movements where id=pg_temp.mid(191)),'incompatible per-diem correction leaves prior version intact');
select throws_like($$insert into public.finance_movement_corrections values(pg_temp.fid(1),pg_temp.fid(900),pg_temp.fid(901),pg_temp.fid(902))$$,'%permission denied%','linkage cannot be forged directly');
select throws_like($$update public.finance_movements set description='Rewrite' where id=pg_temp.mid(102)$$,'%permission denied%','posted original remains immutable');
reset role;
select throws_like($$update public.finance_movement_corrections set original_movement_id=pg_temp.fid(900) where original_movement_id=pg_temp.mid(100)$$,'%finance_history_immutable%','linkage is append-only even for table owner');
select set_config('request.jwt.claim.sub',pg_temp.fid(11)::text,true);
set local role authenticated;
select is((select count(*) from public.finance_current_movements),0::bigint,'employees cannot read current movements');
select is((select count(*) from public.finance_movement_corrections),0::bigint,'employees cannot read correction history');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(140),pg_temp.mid(102),pg_temp.input('1',pg_temp.day()))$$,'%finance_admin_required%','employees cannot correct cash');
select throws_like($$select public.get_finance_movement_history_ids(pg_temp.fid(1),pg_temp.fid(100))$$,'%finance_admin_required%','employees cannot read history RPC');
select set_config('request.jwt.claim.sub',pg_temp.fid(12)::text,true);
select is((select count(*) from public.finance_movement_corrections),0::bigint,'other studio admin cannot read correction links');
select throws_like($$select public.correct_finance_movement(pg_temp.fid(1),pg_temp.fid(140),pg_temp.fid(100),pg_temp.input('1',pg_temp.day()))$$,'%finance_admin_required%','other studio admin cannot correct another tenant');
select * from finish();
rollback;
