begin;
select no_plan();
create function pg_temp.pid(n integer) returns uuid language sql immutable as $$select ('79000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.studios(id,name) values(pg_temp.pid(1),'Proposal A'),(pg_temp.pid(2),'Proposal B');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.pid(n),'authenticated','authenticated','proposal-'||n||'@test','{}','{}',now(),now() from generate_series(10,12)n;
insert into public.profiles(id,full_name,email,system_role,is_active)
select pg_temp.pid(n),'Proposal tester','proposal-'||n||'@test',case when n=11 then 'employee' else 'admin' end,true from generate_series(10,12)n;
insert into public.studio_members(studio_id,user_id,system_role)
select pg_temp.pid(case when n=12 then 2 else 1 end),pg_temp.pid(n),case when n=11 then 'employee' else 'admin' end from generate_series(10,12)n;
insert into public.finance_settings(studio_id,base_currency,cutover_date,created_by) values(pg_temp.pid(1),'EUR','2026-09-01',pg_temp.pid(10));
insert into public.finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values(pg_temp.pid(20),pg_temp.pid(1),'Bank','EUR',0,pg_temp.pid(10));
insert into public.projects(id,studio_id,name,total_area_m2,start_date,created_by,status,client_name,city,site_address)
values(pg_temp.pid(30),pg_temp.pid(1),'336_Стоматологічна клініка',120,'2026-09-01',pg_temp.pid(10),'active','Олена Коваль','Київ','вул. Городецького, 12');
-- The test harness stands in for the trusted renderer, with a fixed verified actor.
create function pg_temp.save_proposal(studio uuid,project uuid,request uuid,source jsonb,presentation jsonb,pdf text) returns uuid
language sql security definer set search_path='' as $$select public.save_finance_project_proposal(studio,project,request,source,presentation,pdf,pg_temp.pid(10))$$;
select set_config('request.jwt.claim.sub',pg_temp.pid(10)::text,true);
set local role authenticated;
select public.finalize_finance_setup(pg_temp.pid(1));
select public.save_finance_project_plan(pg_temp.pid(1),pg_temp.pid(100),pg_temp.pid(30),jsonb_build_object('revision',0,'pricingMethod','area','area','100','rate','40','amount','4000','currency','EUR','vatRate','23','priceBasis','net','revenueTaxRate','6','reason','Agreement','known','[]'::jsonb,'items',jsonb_build_array(
  jsonb_build_object('id','','name','Створення функціонального планування','amount','1200','percentage','30','clientNote','Оплата перед початком етапу'),
  jsonb_build_object('id','','name','Створення 3D-візуалізації','amount','2000','percentage','50'),
  jsonb_build_object('id','','name','Розробка робочої документації та специфікації','amount','800','percentage','20'))));
select lives_ok($$select public.save_studio_contact_details(pg_temp.pid(1),'https://space.example','hello@space.example','+380 44 000 00 00','Київ, вул. Городецького, 12')$$,'active admin saves contacts on existing studio profile');
create temporary table captured as select public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30)) as source;
create function pg_temp.presentation(source jsonb) returns jsonb language sql as $$select jsonb_build_object('projectTitle',source->>'projectTitle','clientName',source->>'clientName','contact',source->>'contact','address',source->>'address','intro','Площа попередня; уточнюється після обмірів.','studioContacts','space.example · hello@space.example')$$;
select ok(not has_function_privilege('authenticated','public.save_finance_project_proposal(uuid,uuid,uuid,jsonb,jsonb,text,uuid)','EXECUTE'),'untrusted clients cannot inject PDF bytes');
select ok(has_function_privilege('service_role','public.save_finance_project_proposal(uuid,uuid,uuid,jsonb,jsonb,text,uuid)','EXECUTE'),'trusted renderer can persist generated bytes');
select is((select source->'studioContactDetails'->>'website' from captured),'https://space.example','new proposal defaults use saved studio profile');
select is((select source->>'projectNumber' from captured),'336','leading project number accepts underscore');
select is((select source->>'gross' from captured),'4920.00','payable total is Gross');
select is((select (source->>'clientRatePerM2')::numeric from captured),49.2::numeric,'single area tariff uses the existing client Gross VAT convention');
select is((select source->>'vatAmount' from captured),'920.00','included VAT follows Finance');
select is((select source->>'address' from captured),'Київ, вул. Городецького, 12','site address prefilled');
select is((select jsonb_array_length(source->'rows') from captured),3,'same number of Finance rows');
select is((select (source->'rows'->0->>'percentage')::numeric from captured),30::numeric,'same percentage');
select is((select source->'rows'->0->>'name' from captured),'Створення функціонального планування','same editable row name');
select is((select (source->'rows'->0->>'gross')::numeric from captured),1476::numeric,'same Gross row amount');
select is((select source->'rows'->0->>'note' from captured),'Оплата перед початком етапу','optional note uses payment data');
select ok((select not source ? 'revenueTaxRate' and not source ? 'netAmount' and not source ? 'afterTax' from captured),'client data excludes internal tax values');
select lives_ok($$select pg_temp.save_proposal(pg_temp.pid(1),pg_temp.pid(30),pg_temp.pid(200),source,pg_temp.presentation(source),'JVBERi0=') from captured$$,'save snapshot');
select is((select snapshot->>'studioContacts' from public.finance_project_proposals),'space.example · hello@space.example','studio footer contacts are part of the immutable presentation');
create temporary table frozen as select snapshot,pdf from public.finance_project_proposals where project_id=pg_temp.pid(30);
select lives_ok($$select pg_temp.save_proposal(pg_temp.pid(1),pg_temp.pid(30),pg_temp.pid(200),source,pg_temp.presentation(source),'JVBERi0=') from captured$$,'lost-response retry is idempotent');
select is((select count(*) from public.finance_project_proposals),1::bigint,'retry adds no revision');
select throws_like($$update public.finance_project_proposals set snapshot='{}'$$,'%permission denied%','authenticated cannot rewrite history');
select throws_like($$select pg_temp.save_proposal(pg_temp.pid(1),pg_temp.pid(30),pg_temp.pid(201),source,pg_temp.presentation(source),'JVBERi0=') from captured$$,'%finance_version_conflict%','stale preview cannot generate another revision');
select throws_like($$select pg_temp.save_proposal(pg_temp.pid(1),pg_temp.pid(30),pg_temp.pid(202),public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30)),jsonb_build_object('gross','1'),'JVBERi0=')$$,'%finance_input_invalid%','cannot override contractual values');
reset role;
select throws_like($$update public.finance_project_proposals set snapshot='{}'$$,'%finance_history_immutable%','privileged snapshot updates blocked');
select throws_like($$delete from public.finance_project_proposals$$,'%finance_history_immutable%','privileged deletion blocked');
update public.projects set name='999 Changed name',client_name='Changed client',site_address='Changed address' where id=pg_temp.pid(30);
update public.finance_expected_items set description='Changed stage',client_note='Changed note' where studio_id=pg_temp.pid(1);
set local role authenticated;
create temporary table old_contacts_source as select public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30)) as source;
select public.save_studio_contact_details(pg_temp.pid(1),'https://new.space.example','new@space.example','','');
select throws_like($$select pg_temp.save_proposal(pg_temp.pid(1),pg_temp.pid(30),pg_temp.pid(205),source,pg_temp.presentation(source),'JVBERi0=') from old_contacts_source$$,'%finance_version_conflict%','contact profile changes invalidate a stale draft');
select results_eq($$select snapshot,pdf from public.finance_project_proposals where project_id=pg_temp.pid(30)$$,$$select snapshot,pdf from frozen$$,'project and studio profile edits cannot alter saved snapshot or PDF');
select is(public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))->>'projectNumber','336','later revision keeps initial project number');
select lives_ok($$select pg_temp.save_proposal(pg_temp.pid(1),pg_temp.pid(30),pg_temp.pid(203),s,pg_temp.presentation(s),'JVBERi0=') from (select public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30)) s) q$$,'later revision snapshots current data');
select is((select snapshot->'studioContactDetails'->>'email' from public.finance_project_proposals where revision=2),'new@space.example','later revision snapshots current contact defaults');
select is((select snapshot->>'clientName' from public.finance_project_proposals where revision=2),'Changed client','revision has its own snapshot');
select public.record_finance_expected_payment(pg_temp.pid(1),pg_temp.pid(300),(select (source->'rows'->0->>'id')::uuid from captured),jsonb_build_object('kind','incoming','date','2026-09-20','amount','1','accountId',pg_temp.pid(20),'categoryId',(select id from public.finance_categories where studio_id=pg_temp.pid(1) and default_key='project_payments')),1);
create temporary table protected_money as select id,amount,net_amount,vat_amount from public.finance_project_plan_items where has_settlement_history;
select lives_ok($$select public.save_finance_project_plan(pg_temp.pid(1),pg_temp.pid(301),pg_temp.pid(30),jsonb_build_object(
  'revision',1,'pricingMethod','fixed','amount','4000','currency','EUR','vatRate','23','priceBasis','net','revenueTaxRate','6','reason','Client note on paid stage','allowUnscheduled',false,
  'known',(select jsonb_agg(jsonb_build_object('id',id,'version',version,'protected',has_settlement_history) order by id) from public.finance_project_plan_items),
  'protectedNotes',(select jsonb_agg(jsonb_build_object('id',id,'clientNote','Етап оплачується перед початком робіт')) from public.finance_project_plan_items where has_settlement_history),
  'items',(select jsonb_agg(jsonb_build_object('id',id,'name',description,'amount',net_amount::text,'percentage',schedule_percentage::text,'clientNote',client_note)) from public.finance_project_plan_items where not has_settlement_history)))$$,'optional note can change on settled payment without changing its money');
select results_eq($$select id,amount,net_amount,vat_amount from public.finance_project_plan_items where has_settlement_history$$,$$select * from protected_money$$,'protected money stays intact');
select is((select client_note from public.finance_project_plan_items where has_settlement_history),'Етап оплачується перед початком робіт','protected note remains Finance-owned');
select public.save_finance_project_terms(pg_temp.pid(1),pg_temp.pid(302),pg_temp.pid(30),jsonb_build_object('stream','design','mode','design','revision',2,'amount','5000','currency','EUR','vatRate','20','priceBasis','net','reason','New price and VAT'));
select is((select (value->>'percentage')::numeric from jsonb_array_elements(public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))->'rows') where value->>'id'=(select source->'rows'->0->>'id' from captured)),24.6::numeric,'retained stage share follows amended Gross contract');
select results_eq($$select snapshot,pdf from public.finance_project_proposals where revision=1$$,$$select snapshot,pdf from frozen$$,'later price and VAT changes cannot change generated snapshot or bytes');
select lives_ok($$select public.save_finance_project_plan(pg_temp.pid(1),pg_temp.pid(303),pg_temp.pid(30),jsonb_build_object(
  'revision',3,'pricingMethod','fixed','amount','5000','currency','EUR','vatRate','20','priceBasis','net','reason','Rebalance remaining payments','allowUnscheduled',false,
  'known',(select jsonb_agg(jsonb_build_object('id',id,'version',version,'protected',has_settlement_history) order by id) from public.finance_project_plan_items),
  'items',jsonb_build_array(jsonb_build_object('id','','name','Фінальний платіж','amount','3770','percentage','100'))))$$,'remaining-pool schedule is saved');
select ok(public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))->'clientRatePerM2'='null'::jsonb,'fixed contracts do not invent an area tariff');
select is((public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))->'rows'->0->>'percentage')::numeric,75.4::numeric,'100 percent of remaining pool becomes its whole-contract share');
select is((select sum((value->>'percentage')::numeric) from jsonb_array_elements(public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))->'rows')),100::numeric,'amended schedule shares reconcile');
select results_eq($$select snapshot,pdf from public.finance_project_proposals where revision=1$$,$$select snapshot,pdf from frozen$$,'later schedule replacement cannot change saved document');
select set_config('request.jwt.claim.sub',pg_temp.pid(11)::text,true);
select throws_like($$select public.save_studio_contact_details(pg_temp.pid(1),'','','','')$$,'%studio_forbidden%','employee cannot change contact defaults');
select is((select count(*) from public.finance_project_proposals),0::bigint,'employee cannot read proposals');
select throws_like($$select public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))$$,'%finance_forbidden%','employee cannot read draft');
select set_config('request.jwt.claim.sub',pg_temp.pid(12)::text,true);
select throws_like($$select public.save_studio_contact_details(pg_temp.pid(1),'','','','')$$,'%studio_forbidden%','other studio admin cannot change contact defaults');
select is((select count(*) from public.finance_project_proposals),0::bigint,'other-studio admin cannot read proposals');
select throws_like($$select public.get_finance_proposal_source(pg_temp.pid(1),pg_temp.pid(30))$$,'%finance_forbidden%','other-studio draft denied');
select ok(not has_function_privilege('anon','public.get_finance_proposal_source(uuid,uuid)','EXECUTE'),'anonymous cannot read proposal data');
select ok(not has_function_privilege('anon','public.save_studio_contact_details(uuid,text,text,text,text)','EXECUTE'),'anonymous cannot change contact defaults');
select * from finish();
rollback;
