"use client";

import Link from "next/link";
import { useLocale, useTranslations } from "next-intl";
import { getPriorityBadgeStyle, getProjectHealthBadgeStyle } from "@/lib/semantic-styles";
import { getProjectHref, getProjectProgressLabel, type PresentedProject } from "@/lib/project-list-presentation";
import { formatDateOnly } from "@/lib/utils";
import type { AccessibleProjectWithTasks } from "@/data/queries/project-progress";

type ProjectItem = PresentedProject<AccessibleProjectWithTasks>;

const healthKeys = { on_track: "healthOnTrack", needs_attention: "healthNeedsAttention", deadline_soon: "healthDeadlineSoon", overdue: "healthOverdue", completed: "healthCompleted" } as const;

export function ProjectList({ projects }: { projects: readonly ProjectItem[] }) {
  const t = useTranslations("Projects");
  return <><div className="hidden xl:block"><div className="rounded-[var(--ui-radius-panel)] border border-[var(--ui-border)] bg-[var(--ui-surface)]"><div className="grid grid-cols-[minmax(14rem,1.55fr)_minmax(10rem,0.85fr)_minmax(12rem,1fr)_auto_minmax(10rem,0.8fr)] gap-6 border-b border-[var(--ui-border)] bg-[var(--ui-surface-muted)] px-4 py-2 text-xs font-medium text-[var(--ui-text-muted)]"><span>{t("project")}</span><span className="pr-8">{t("progress")}</span><span className="pl-8">{t("deadline")}</span><span>{t("open")}</span><span className="text-right">{t("health")}</span></div><ul className="divide-y divide-[var(--ui-border)]">{projects.map((project) => <ProjectDesktopRow key={project.id} project={project} />)}</ul></div></div><ul className="grid gap-3 sm:grid-cols-2 xl:hidden">{projects.map((project) => <ProjectMobileCard key={project.id} project={project} />)}</ul></>;
}

function ProjectDesktopRow({ project }: { project: ProjectItem }) { const t = useTranslations("Projects"); return <li><Link href={getProjectHref(project.id)} className="grid min-h-24 grid-cols-[minmax(14rem,1.55fr)_minmax(10rem,0.85fr)_minmax(12rem,1fr)_auto_minmax(10rem,0.8fr)] items-center gap-6 px-4 py-3 transition-colors hover:bg-[var(--ui-surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--ui-focus)]"><ProjectIdentity project={project} /><div className="min-w-0 pr-8"><ProjectProgress project={project} compact /></div><div className="min-w-0 pl-8"><ProjectDeadlines project={project} /></div><span className="ui-numeric text-sm font-medium text-[var(--ui-text-secondary)]">{t("openCount", { count: project.progress.openTaskCount })}</span><ProjectSignals project={project} /></Link></li>; }
function ProjectMobileCard({ project }: { project: ProjectItem }) { const t = useTranslations("Projects"); return <li><Link href={getProjectHref(project.id)} className="block min-h-44 rounded-[var(--ui-radius-panel)] border border-[var(--ui-border)] bg-[var(--ui-surface)] p-4 transition-colors hover:border-[var(--ui-border-strong)] hover:bg-[var(--ui-surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ui-focus)]"><div className="flex items-start justify-between gap-3"><ProjectIdentity project={project} /><div className="flex shrink-0 flex-col items-end gap-2"><ProjectSignals project={project} /><span className="text-xs font-medium text-[var(--ui-text-secondary)]">{t("openProject")}</span></div></div><ProjectProgress project={project} /><ProjectDeadlines project={project} /></Link></li>; }
function ProjectIdentity({ project }: { project: ProjectItem }) { const status = useTranslations("Status"); const label = status(project.status); return <div className="min-w-0"><p className="flex items-center gap-2 break-words font-semibold text-[var(--ui-text)]"><LifecycleDot status={project.status} label={label} />{project.name}</p>{project.client_name ? <p className="mt-0.5 text-sm text-[var(--ui-text-muted)]">{project.client_name}</p> : null}</div>; }
function ProjectSignals({ project }: { project: ProjectItem }) { const t = useTranslations("Projects"); const priority = useTranslations("Priority"); const healthLabel = t(healthKeys[project.health]); const needsAttention = project.health !== "on_track" && project.health !== "completed"; return <div className="flex min-w-0 flex-col items-end text-right">{needsAttention ? <Badge className={`font-semibold ${getProjectHealthBadgeStyle(project.health).className}`} label={healthLabel} title={project.healthReason ?? healthLabel} /> : null}<PrioritySignal priority={project.priority} label={priority(project.priority)} className={needsAttention ? "mt-1.5" : ""} /></div>; }
function LifecycleDot({ label, status }: { label: string; status: string }) { const className = status === "active" ? "bg-[var(--ui-success-accent)]" : status === "paused" ? "bg-[var(--ui-info-accent)]" : status === "completed" ? "bg-[var(--ui-violet-text)]" : "bg-[var(--ui-text-muted)]"; return <span role="img" aria-label={label} title={label} className={`size-2 shrink-0 rounded-full ${className}`}><span className="sr-only">{label}</span></span>; }
function PrioritySignal({ className = "", label, priority }: { className?: string; label: string; priority: string }) { if (priority === "normal" || priority === "low") return <span className={`text-xs font-medium text-[var(--ui-text-muted)] ${className}`}>{label}</span>; return <Badge className={`${getPriorityBadgeStyle(priority).className} ${className}`} label={label} />; }
function ProjectProgress({ compact = false, project }: { compact?: boolean; project: ProjectItem }) { const t = useTranslations("Projects"); if (project.progress.eligibleTaskCount === 0) return <p className={compact ? "text-sm font-medium text-[var(--ui-text-muted)]" : "mt-4 text-sm font-medium text-[var(--ui-text-muted)]"}>{t("noTasks")}</p>; const label = getProjectProgressLabel(project.progress); const markerOffset = project.progress.progressPercent === 100 ? "calc(100% - 0.375rem)" : `${project.progress.progressPercent}%`; return <div className={compact ? "min-w-0" : "mt-4"}><div className="flex items-center gap-3"><div className="relative h-3 min-w-0 flex-1" role="progressbar" aria-label={t("progressAria", { name: project.name, progress: label })} aria-valuemin={0} aria-valuemax={100} aria-valuenow={project.progress.progressPercent}><div className="absolute inset-x-0 top-1/2 h-2 -translate-y-1/2 rounded-full bg-[var(--ui-progress-track)]" /><div className="absolute left-0 top-1/2 h-2 -translate-y-1/2 rounded-full bg-[var(--ui-action-primary)]" style={{ width: `${project.progress.progressPercent}%` }} />{project.progress.progressPercent > 0 ? <span aria-hidden="true" className="absolute top-1/2 size-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-[var(--ui-surface)] bg-[var(--ui-action-primary)] shadow-[var(--ui-shadow-panel)]" style={{ left: markerOffset }} /> : null}</div><span className="ui-numeric min-w-10 text-right text-sm font-semibold text-[var(--ui-text)]">{project.progress.progressPercent}%</span></div><p className="ui-numeric mt-1.5 text-xs leading-5 text-[var(--ui-text-muted)]">{t("completedCount", { count: project.progress.completedTaskCount })} · {t("openCount", { count: project.progress.openTaskCount })}{project.progress.overdueTaskCount ? ` · ${t("overdueCount", { count: project.progress.overdueTaskCount })}` : ""}</p></div>; }
function ProjectDeadlines({ project }: { project: ProjectItem }) { const t = useTranslations("Projects"); const locale = useLocale(); return <div className="mt-4 text-sm text-[var(--ui-text-muted)] xl:mt-0 xl:text-xs"><p>{project.due_date ? t("projectDeadline", { date: formatDateOnly(project.due_date, locale) }) : t("noProjectDeadline")}</p></div>; }
function Badge({ className, label, title }: { className: string; label: string; title?: string }) { return <span title={title} className={`rounded-full px-2 py-0.5 text-xs font-medium ${className}`}>{label}</span>; }
