"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale, useTranslations } from "next-intl";
import type { FinanceManagementData } from "@/data/queries/finance-management";
import type { ProjectCashReceipt } from "@/lib/finance-profitability";
import { financeAmountText, financeAmountUnits, formatFinanceAmount } from "@/lib/finance";
import { summarizeManagementEntries } from "@/lib/finance-management";
import { saveFinanceProjectReporting } from "@/app/(app)/finance/reports/project-actions";
import { FinanceActionForm } from "./finance-action-form";
import { FinanceFxFields } from "./finance-fx-fields";
import { AnimatedDisclosure } from "@/components/ui/animated-form-content";
import { FormField, Input, Textarea } from "@/components/ui/form-field";
import { Button } from "@/components/ui/button";
import { DatePicker } from "@/components/ui/date-picker";
import { Select, SelectItem } from "@/components/ui/select";
import { formatDateOnly } from "@/lib/utils";
const panel = "min-w-0 rounded-[var(--ui-radius-panel)] border border-[var(--ui-border)] bg-[var(--ui-surface)] p-4 sm:p-5";
export function ProjectProfitabilitySection({ data, projectId, embedded = false, stream = "design" }: { data: FinanceManagementData; projectId?: string; embedded?: boolean; stream?: string }) {
  const t = useTranslations("Finance.profitability"), locale = useLocale(), router = useRouter();
  const rows = data.projectProfitability.filter(row => !projectId || row.projectId === projectId);
  const money = (value: string | null) => value === null ? "—" : `${formatFinanceAmount(value, data.currency, locale, "decimal")} ${data.displayCurrency}`;
  const refresh = () => router.refresh();
  const studio = summarizeManagementEntries(data.amountRows, data.filters.from, data.filters.to, data.currency.minor_units);
  const projects = summarizeManagementEntries(data.projectRows, data.filters.from, data.filters.to, data.currency.minor_units);
  const bridge = financeAmountText(financeAmountUnits(studio.knownResult, data.currency.minor_units) - financeAmountUnits(projects.knownResult, data.currency.minor_units), data.currency.minor_units);
  const params = new URLSearchParams({ report: "projects", from: data.filters.from, to: data.filters.to, version: data.version });
  if (projectId) params.set("project", projectId);
  return <section className="min-w-0 space-y-4" id="profitability">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{t("title")}</h2><p className="mt-1 text-xs text-[var(--ui-text-secondary)]">{data.filters.from} – {data.filters.to} · {t("coverageSince", { date: data.settings?.recognition_start_month ?? "—" })}</p></div><Link href={`/finance/reports/export?${params}`} className="text-sm underline underline-offset-4">{t("exportCsv")}</Link></div>
    {embedded && projectId ? <form method="get" action={`/projects/${projectId}`} className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><input type="hidden" name="view" value="finance"/><input type="hidden" name="stream" value={stream}/><FormField label={t("from")}><DatePicker name="profitFrom" defaultValue={data.filters.from} locale={locale}/></FormField><FormField label={t("to")}><DatePicker name="profitTo" defaultValue={data.filters.to} locale={locale}/></FormField><Button type="submit" variant="outline">{t("applyFilters")}</Button></form> : null}
    {rows.map(row => <article key={row.projectId} className={`${panel} space-y-3`}>
      <div className="flex flex-wrap items-baseline justify-between gap-2"><Link href={`/projects/${row.projectId}?view=finance`} className="font-semibold underline decoration-[var(--ui-border)] underline-offset-4">{row.name}</Link><span className="text-xs text-[var(--ui-text-secondary)]">{t(row.historyIncomplete || row.coverageGaps || row.laborIncomplete || row.lifetime.missingFx || row.pendingTripCount ? "incompleteCosts" : "knownCosts")}</span></div>
      <div className="grid grid-cols-1 gap-3 text-sm sm:grid-cols-3"><div><p className="text-xs text-[var(--ui-text-muted)]">{t("agreedNet")}</p><p className="mt-1 font-semibold tabular-nums">{money(row.agreed.net)}</p><p className="mt-1 text-xs text-[var(--ui-text-muted)]">{t("referenceFx", { date: row.agreed.referenceDate })}</p></div><div><p className="text-xs text-[var(--ui-text-muted)]">{t("recognized")}</p><p className="mt-1 font-semibold tabular-nums">{money(row.lifetime.revenue)}</p></div><div><p className="text-xs text-[var(--ui-text-muted)]">{t("receivedGross")}</p><p className="mt-1 font-semibold tabular-nums">{money(row.received.lifetime)}</p></div></div>
      <div className="overflow-x-auto"><table className="w-full table-fixed text-xs sm:table-auto sm:text-sm"><thead><tr className="border-b border-[var(--ui-border-subtle)] text-xs text-[var(--ui-text-muted)]"><th className="w-[42%] py-2 pr-2 text-left font-medium">{t("metric")}</th><th className="py-2 text-right font-medium">{t("period")}</th><th className="py-2 text-right font-medium">{t("lifetime")}</th></tr></thead><tbody>{(["revenue", "directCost", "tripCost", "labor", "result"] as const).map(key => <tr key={key} className={key === "result" ? "border-t border-[var(--ui-border)] font-semibold" : ""}><th className={`py-2 text-left ${key === "tripCost" ? "pl-3 text-xs text-[var(--ui-text-muted)]" : "font-normal"}`}><Link href={`/finance/reports?project=${row.projectId}&from=${data.filters.from}&to=${data.filters.to}#fx-history`} className="underline decoration-[var(--ui-border)] underline-offset-4">{t(key)}</Link></th><td className="py-2 text-right tabular-nums">{money(row.period[key])}</td><td className="py-2 text-right tabular-nums">{money(row.lifetime[key])}</td></tr>)}<tr><th className="py-2 text-left font-normal">{t("margin")}</th><td className="py-2 text-right">{row.period.margin === null ? "—" : `${row.period.margin}%`}</td><td className="py-2 text-right">{row.lifetime.margin === null ? "—" : `${row.lifetime.margin}%`}</td></tr><tr><th className="py-2 text-left font-normal">{t("receivedGross")}</th><td className="py-2 text-right">{money(row.received.period)}</td><td className="py-2 text-right">{money(row.received.lifetime)}</td></tr></tbody></table></div>
      <p className="text-xs text-[var(--ui-text-muted)]">{t("basis")}</p><p className="text-xs text-[var(--ui-text-secondary)]">{t("cashCoverage",{date:data.settings?.cutover_date ?? "—",count:data.projectReporting.receipts.filter(receipt => /[1-9]/.test(receipt.unattributed)).length})} <Link href="#cash-attribution" className="underline">{t("cashAttribution")}</Link></p>
      {row.historyIncomplete || row.coverageGaps || row.laborIncomplete || row.lifetime.missingFx || row.pendingTripCount ? <div className="space-y-1 text-xs text-[var(--ui-warning-text)]" role="status">{row.historyIncomplete ? <p>{t("historyIncomplete")}</p> : null}{row.pendingTripCount ? <p>{t("pendingTrips",{count:row.pendingTripCount})} <Link href="/finance/reports#trip-sources" className="underline">{t("reviewCoverage")}</Link></p> : null}{row.coverageGaps ? <p>{t("coverageGaps", { count: row.coverageGaps })} <Link href={`/finance/reports?project=${row.projectId}&from=${data.filters.from}&to=${data.filters.to}#coverage`} className="underline">{t("reviewCoverage")}</Link></p> : null}{row.laborIncomplete ? <p>{t("laborIncomplete")} <Link href="/finance/reports#labor" className="underline">{t("reviewLabor")}</Link></p> : null}{row.lifetime.missingFx ? <p>{t("missingFx", { count: row.lifetime.missingFx })} <Link href={`/finance/reports?project=${row.projectId}#fx-history`} className="underline">{t("reviewFx")}</Link></p> : null}</div> : null}
      <AnimatedDisclosure title={t("termsAndMatches")}><div className="space-y-2 pt-2 text-xs text-[var(--ui-text-secondary)]">{row.contracts.map(contract => <p key={contract.id}>{t(`stream.${contract.stream}`)} · {t(`mode.${contract.mode}`)} · {contract.net_amount ?? "—"} {contract.currency} · {t("gross")}: {contract.gross_amount ?? "—"} {contract.currency}</p>)}{row.matched.map(item => <p key={`${item.stream}-${item.currency}`}>{t("matched")}: {item.amount} {item.currency} · {t(`stream.${item.stream}`)}</p>)}<p>{t("matchBasis")}</p></div></AnimatedDisclosure>
      <AnimatedDisclosure title={t("costPlan")}><div className="space-y-3 pt-3">
        {row.estimateStale ? <p role="status" className="rounded-[var(--ui-radius-control)] bg-[var(--ui-warning-surface)] p-3 text-xs text-[var(--ui-warning-text)]">{t("estimateStale")}</p> : null}
        <dl className="grid grid-cols-2 gap-3 text-sm">{(["direct_budget", "labor_budget", "remaining_direct", "remaining_labor"] as const).map(key => <div key={key}><dt className="text-xs text-[var(--ui-text-muted)]">{t(key)}</dt><dd className="mt-1 tabular-nums">{money(row.estimateDisplay[key])}</dd></div>)}</dl>
        <p className="text-xs text-[var(--ui-text-secondary)]">{t("budgetVarianceHelp")}</p><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-[var(--ui-text-muted)]">{t("directVariance")}</dt><dd className="mt-1 tabular-nums">{money(row.budgetVariance.direct)}</dd></div><div><dt className="text-xs text-[var(--ui-text-muted)]">{t("laborVariance")}</dt><dd className="mt-1 tabular-nums">{money(row.budgetVariance.labor)}</dd></div></dl>
        <p className="text-sm">{t("finalMargin")}: <strong>{row.finalMargin === null ? "—" : `${row.finalMargin}%`}</strong></p>{row.finalMargin === null ? <p className="text-xs text-[var(--ui-text-muted)]">{t("finalMarginHelp")}</p> : null}<EstimateForm data={data} projectId={row.projectId} onSaved={refresh}/><AnimatedDisclosure title={t("estimateHistory")}><ul className="space-y-1 pt-2 text-xs text-[var(--ui-text-secondary)]">{data.projectReporting.estimates.filter(item => item.project_id === row.projectId).map(item => <li key={item.id}>{item.as_of} · #{item.revision} · {item.reason} · {item.direct_budget ?? "—"}/{item.labor_budget ?? "—"} · {item.remaining_direct ?? "—"}/{item.remaining_labor ?? "—"} {item.currency} · FX {item.fx_rate ?? "—"} {item.fx_source ?? ""} {item.fx_effective_date ?? ""}</li>)}</ul></AnimatedDisclosure></div></AnimatedDisclosure>
    </article>)}
    {!projectId ? <div className={`${panel} space-y-2`}><h3 className="font-semibold">{t("bridge")}</h3><p className="text-sm">{t("projectResults")}: {money(projects.knownResult)} · {t("studioRemainder")}: {money(bridge)} · {t("studioResult")}: {money(studio.knownResult)}</p><p className="text-xs text-[var(--ui-text-secondary)]">{t("bridgeHelp")}</p></div> : null}
    <div id="cash-attribution"><AnimatedDisclosure title={t("cashAttribution")} className={panel}><p className="my-3 text-xs text-[var(--ui-text-secondary)]">{t("cashHelp")}</p><div className="space-y-3">{data.projectReporting.receipts.map(receipt => <ReceiptForm key={`${receipt.id}:${receipt.revision}`} receipt={receipt} data={data} projectId={projectId} onSaved={refresh}/>)}</div>
      <AnimatedDisclosure title={t("cashHistory", { count: data.projectReporting.cashHistory.length })} className="mt-3"><p className="pb-2 text-xs text-[var(--ui-text-secondary)]">{t("cashHistoryHelp")}</p><ol className="divide-y divide-[var(--ui-border)]">{[...data.projectReporting.cashHistory].sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.revision - a.revision).map(item => { const receipt = data.projectReporting.receipts.find(row => row.id === item.movementId); const currency = item.currency; return <li key={item.id} className="py-2 text-xs"><p className="font-medium">{receipt?.description ?? item.description} · v{item.revision} · {formatDateOnly(item.createdAt.slice(0, 10), locale)} · {item.actor}</p><p className="mt-1 text-[var(--ui-text-secondary)]">{item.reason} · {currency}</p>{item.items.length ? <ul className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[var(--ui-text-secondary)]">{item.items.map((split, index) => <li key={`${item.id}-${split.projectId}-${index}`}>{data.projects.find(project => project.id === split.projectId)?.name ?? t("projectUnavailable")}: {split.amount} {currency}</li>)}</ul> : <p className="mt-1 text-[var(--ui-text-muted)]">{t("cashHistoryCleared")}</p>}<Link href={`/finance/movements?movement=${item.movementId}`} className="mt-1 inline-block underline">{t("source")}</Link></li>; })}</ol></AnimatedDisclosure>
    </AnimatedDisclosure></div>
  </section>;
}
function EstimateForm({ data, projectId, onSaved }: { data: FinanceManagementData; projectId: string; onSaved: () => void }) {
  const t = useTranslations("Finance.profitability"), management = useTranslations("Finance.management"), locale = useLocale();
  const estimate = data.projectProfitability.find(row => row.projectId === projectId)?.estimate;
  const [currency, setCurrency] = useState(estimate?.currency ?? data.settings?.base_currency ?? "USD");
  const start = data.settings?.recognition_start_month;
  if (!start) return <p className="text-xs text-[var(--ui-text-secondary)]">{management("activationRequired")} <Link href="/finance/reports" className="underline">{management("activate")}</Link></p>;
  if (start > data.today) return <p className="text-xs text-[var(--ui-text-secondary)]">{management("reportUnavailable", { date: formatDateOnly(start, locale) })}</p>;
  return <FinanceActionForm action={saveFinanceProjectReporting} label={t("saveEstimate")} onSaved={onSaved}>
    <input type="hidden" name="intent" value="estimate"/><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="revision" value={estimate?.revision ?? 0}/>
    <p className="text-xs text-[var(--ui-text-secondary)]">{t("unknownHelp")}</p><div className="grid gap-3 sm:grid-cols-2"><FormField label={t("currency")}><Select name="currency" value={currency} onValueChange={setCurrency}>{data.currencies.map(unit => <SelectItem key={unit.code} value={unit.code}>{unit.code}</SelectItem>)}</Select></FormField><FormField label={t("date")}><DatePicker name="date" defaultValue={data.today} min={data.settings?.recognition_start_month ?? undefined} max={data.today} locale={locale} required/></FormField>{([['directBudget','direct_budget'],['laborBudget','labor_budget'],['remainingDirect','remaining_direct'],['remainingLabor','remaining_labor']] as const).map(([name,key]) => <FormField key={name} label={t(key)}><Input name={name} inputMode="decimal" defaultValue={estimate?.[key] ?? ""}/></FormField>)}</div>
    {currency !== data.settings?.base_currency ? <FinanceFxFields currency={currency} base={data.settings?.base_currency ?? "USD"}/> : null}<FormField label={t("reason")}><Textarea name="reason" rows={2} required maxLength={2000}/></FormField>
  </FinanceActionForm>;
}
function ReceiptForm({ receipt, data, projectId, onSaved }: { receipt: ProjectCashReceipt; data: FinanceManagementData; projectId?: string; onSaved: () => void }) {
  const t = useTranslations("Finance.profitability");
  const [items, setItems] = useState<Array<{ projectId: string; amount: string }>>(receipt.items);
  const currency = data.currencies.find(unit => unit.code === receipt.currency);
  let total: bigint | null = BigInt(0); try { for (const item of items) total += financeAmountUnits(item.amount.replace(",", "."), currency?.minor_units ?? 2); } catch { total = null; }
  const invalid = total === null || total > financeAmountUnits(receipt.remaining, currency?.minor_units ?? 2) || items.some(item => !item.projectId || !/[1-9]/.test(item.amount));
  return <AnimatedDisclosure title={`${receipt.date} · ${receipt.description} · ${receipt.remaining} ${receipt.currency}`}>
    <p className="my-2 text-xs text-[var(--ui-text-secondary)]">{t("unattributed")}: {receipt.unattributed} {receipt.currency} · #{receipt.revision}</p>
    <FinanceActionForm action={saveFinanceProjectReporting} label={t("saveCash")} onSaved={onSaved} disabled={invalid}>
      <input type="hidden" name="intent" value="cash"/><input type="hidden" name="movementId" value={receipt.id}/><input type="hidden" name="revision" value={receipt.revision}/><input type="hidden" name="items" value={JSON.stringify(items)}/>
      {items.map((item,index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><FormField label={t("project")}><Select value={item.projectId} onValueChange={value => setItems(rows => rows.map((row,i) => i === index ? {...row,projectId:value} : row))}><SelectItem value="">—</SelectItem>{data.projects.map(project => <SelectItem key={project.id} value={project.id} disabled={items.some((other,i) => i !== index && other.projectId === project.id)}>{project.name}</SelectItem>)}</Select></FormField><FormField label={`${t("amount")} · ${receipt.currency}`}><Input value={item.amount} onChange={event => setItems(rows => rows.map((row,i) => i === index ? {...row,amount:event.target.value} : row))} inputMode="decimal" required/></FormField><Button type="button" variant="outline" onClick={() => setItems(rows => rows.filter((_,i) => i !== index))}>{t("remove")}</Button></div>)}
      <Button type="button" variant="outline" onClick={() => setItems(rows => [...rows,{projectId: items.length ? "" : projectId ?? "",amount:""}])}>{t("addProject")}</Button><FormField label={t("reason")}><Textarea name="reason" required rows={2} maxLength={2000}/></FormField>
    </FinanceActionForm><Link href={`/finance/movements?movement=${receipt.id}`} className="mt-2 inline-block text-xs underline">{t("source")}</Link>
  </AnimatedDisclosure>;
}

import { DisplayCurrencySelect } from "./display-currency-select";
import { PageHeader } from "@/components/shared/page-header";
export function ProjectsReportsWorkspace({ data }: { data: FinanceManagementData }) {
  const t = useTranslations("Finance.profitability"), management = useTranslations("Finance.management"), locale = useLocale();
  return <div className="space-y-5"><PageHeader title={t("title")} action={<DisplayCurrencySelect value={data.displayCurrency}/>}/>
    <nav aria-label={t("title")} className="flex flex-wrap gap-4 text-sm"><Link className="underline underline-offset-4" href={`/finance/reports?from=${data.filters.from}&to=${data.filters.to}`}>{t("tabPnl")}</Link><Link className="font-semibold underline underline-offset-4" aria-current="page" href="/finance/reports?report=projects">{t("tabProjects")}</Link></nav>
    <form method="get" action="/finance/reports" className={`${panel} grid gap-3 sm:grid-cols-2 lg:grid-cols-4 lg:items-end`}><input type="hidden" name="report" value="projects"/><FormField label={management("from")}><DatePicker name="from" defaultValue={data.filters.from} locale={locale}/></FormField><FormField label={management("to")}><DatePicker name="to" defaultValue={data.filters.to} locale={locale}/></FormField><FormField label={t("project")}><Select name="project" defaultValue={data.filters.projectId ?? ""}><SelectItem value="">{management("allProjects")}</SelectItem>{data.projects.map(project => <SelectItem key={project.id} value={project.id}>{project.name}</SelectItem>)}</Select></FormField><Button type="submit">{management("applyFilters")}</Button></form>
    <ProjectProfitabilitySection data={data} projectId={data.filters.projectId}/></div>;
}
