import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import en from "../../messages/en.json";
import uk from "../../messages/uk.json";
import type { Database } from "../../src/types/database.types";
const local = z.object({ EQUIPMENT_TEST_SUPABASE_URL: z.url(), EQUIPMENT_TEST_SERVICE_KEY: z.string() }).parse(process.env);
if (!["127.0.0.1", "localhost"].includes(new URL(local.EQUIPMENT_TEST_SUPABASE_URL).hostname)) throw new Error("Local fixtures only");
const client = createClient<Database>(local.EQUIPMENT_TEST_SUPABASE_URL, local.EQUIPMENT_TEST_SERVICE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const studio = randomUUID(), project = randomUUID(), bank = randomUUID();
const actors = ["admin", "employee"].map(role => ({ role, id: "", email: `trip-${randomUUID()}@example.test`, password: `Trip-${randomUUID()}` }));
function sql(statement: string) { return execFileSync("docker", ["exec", "-i", "supabase_db_design-manager", "psql", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-At"], { input: statement, encoding: "utf8" }).trim(); }
test.beforeAll(async () => {
  await client.from("studios").insert({ id: studio, name: "Trip browser fixture" }).throwOnError();
  for (const actor of actors) {
    const r = await client.auth.admin.createUser({ email: actor.email, password: actor.password, email_confirm: true });
    if (r.error) throw r.error; actor.id = r.data.user.id;
    await client.from("profiles").upsert({ id: actor.id, email: actor.email, full_name: `Trip ${actor.role}`, system_role: actor.role, is_active: true }).throwOnError();
    await client.from("studio_members").insert({ studio_id: studio, user_id: actor.id, system_role: actor.role }).throwOnError();
  }
  sql(`insert into finance_settings(studio_id,base_currency,cutover_date,created_by) values('${studio}','UAH','2026-09-01','${actors[0].id}');
  insert into finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values('${bank}','${studio}','Trip bank','UAH',0,'${actors[0].id}');
  select set_config('request.jwt.claim.sub','${actors[0].id}',false); select finalize_finance_setup('${studio}');
  insert into projects(id,studio_id,name,total_area_m2,start_date,status,created_by) values('${project}','${studio}','Dental Warsaw',100,'2026-09-01','active','${actors[0].id}');`);
});
test.afterAll(async () => {
  sql(`begin; set local session_replication_role=replica;
  do $$ declare tab record; begin for tab in select table_name from information_schema.columns where table_schema='public' and column_name='studio_id' and table_name like 'finance_%' and table_name in(select tablename from pg_tables where schemaname='public') loop execute format('delete from public.%I where studio_id=$1',tab.table_name) using '${studio}'::uuid; end loop; end $$;
  delete from calendar_event_participants where event_id in(select id from calendar_events where studio_id='${studio}'); delete from calendar_events where studio_id='${studio}'; delete from project_members where project_id='${project}'; delete from notifications where studio_id='${studio}'; delete from project_activity where project_id='${project}'; delete from project_task_stage_columns where project_id='${project}'; delete from projects where studio_id='${studio}'; delete from studio_members where studio_id='${studio}'; delete from studios where id='${studio}'; commit;`);
  for (const actor of actors) if (actor.id) await client.auth.admin.deleteUser(actor.id);
});

test("inline trip sheet: planning, actuals, editing, reconciliation and rendered QA", async({page},testInfo)=>{
  test.setTimeout(240_000);
  const t=en.Finance.trips,f=en.Finance;
  await page.goto("/login");await page.locator('input[type="email"]').fill(actors[0].email);await page.locator('input[type="password"]').fill(actors[0].password);await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/\/dashboard/);
  sql(`insert into project_members(project_id,user_id,project_role,assigned_area_m2,assigned_at) values('${project}','${actors[0].id}','designer',0,current_date),('${project}','${actors[1].id}','designer',0,current_date); update projects set city='Warsaw',country_code='PL' where id='${project}';`);
  const created=await page.request.post("/api/calendar/events",{data:{title:"Warsaw site visit",eventType:"business_trip",projectId:project,allDay:true,startsAt:"2026-10-24T00:00:00+03:00",endsAt:"2026-10-27T00:00:00+02:00",participantIds:actors.map(a=>a.id)}});expect(created.status()).toBe(201);
  const eventId=sql(`select id from calendar_events where studio_id='${studio}' and event_type='business_trip'`);
  const tripId=sql(`select id from finance_trips where calendar_source_id='${eventId}'`);
  const href=`/finance/trips/${tripId}?fx_PLN=10&fx_USD=40`;
  await page.goto(`/calendar?date=2026-10-24&event=${eventId}`);await page.getByRole("link",{name:en.Calendar.tripFinance}).click();await expect(page).toHaveURL(new RegExp(`/finance/trips/${tripId}$`));await page.goto(href);await expect(page.getByRole("button",{name:f.edit,exact:true})).toHaveCount(0);
  await page.setViewportSize({width:1920,height:1080});
  const row=(type:string)=>page.locator(`[data-expense-type="${type}"]`);
  const form=(type:string)=>row(type).locator("form");
  const plan=(type:keyof typeof t.types)=>row(type).getByRole("button",{name:`${t.plan} · ${t.types[type]}`,exact:true});
  const actual=(type:keyof typeof t.types)=>row(type).getByRole("button",{name:`${t.actual} · ${t.types[type]}`,exact:true});
  const save=async(type:string)=>{await page.getByRole("heading",{name:t.expenseSheet,exact:true}).click();await expect(form(type)).toHaveCount(0);};
  const chooseCurrency=async(type:string,code:string)=>{await form(type).getByRole("combobox",{name:t.currency,exact:true}).click();await page.getByRole("option",{name:code,exact:true}).click();};
  const chooseEmployee=async(type:string)=>{await form(type).getByRole("combobox",{name:t.paidBy,exact:true}).click();await page.getByRole("option",{name:"Trip employee",exact:true}).click();};
  const manualFx=async(type:string,code="PLN")=>{await form(type).getByRole("combobox",{name:f.movements.valuation.replace("{currency}",code).replace("{base}","UAH"),exact:true}).click();await page.getByRole("option",{name:f.movements.manual,exact:true}).click();await form(type).getByLabel(f.movements.rate.replace("{currency}",code).replace("{base}","UAH"),{exact:true}).fill("10");};
  await expect(page.getByRole("button",{name:t.openPlan})).toHaveText(t.notPlanned);await expect(page.getByText(t.emptyExpenseTitle,{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:t.startPlanning,exact:true})).toBeVisible();await expect(page.getByRole("button",{name:t.addActualFromEmpty,exact:true})).toBeVisible();await expect(page.locator('[data-trip-summary="variance"]')).toHaveText(t.variance+"—");await expect(row("other")).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("inline-empty-fullhd-en-light.png"),fullPage:true});
  // A: four plans, zero dialogs and no type selector. Enter confirms; Escape cancels.
  await page.getByRole("button",{name:t.startPlanning,exact:true}).click();await expect(form("travel").getByLabel(f.movements.amount,{exact:true})).toBeFocused();await expect(form("travel").getByRole("button",{name:f.close,exact:true})).toHaveCount(0);await expect(form("travel").getByRole("button",{name:f.planning.save,exact:true})).toHaveCount(0);await form("travel").getByLabel(f.movements.amount,{exact:true}).fill("4000");await form("travel").getByLabel(f.movements.amount,{exact:true}).press("Enter");await expect(form("travel")).toHaveCount(0);
  await plan("accommodation").click();await form("accommodation").getByLabel(f.movements.amount,{exact:true}).fill("1200");await chooseCurrency("accommodation","PLN");await expect(form("accommodation").getByText(/1200 PLN ≈ 12000.00 UAH/)).toBeVisible();
  await form("accommodation").getByRole("button",{name:t.moreOptions,exact:true}).click();await form("accommodation").getByRole("combobox",{name:t.expectedDate,exact:true}).click();await page.getByRole("button",{name:"Today",exact:true}).click();await expect(form("accommodation")).toBeVisible();await plan("meals").click();await expect(form("accommodation")).toHaveCount(0);await expect(form("meals").getByLabel(t.dailyRate,{exact:true})).toBeFocused();
  await form("meals").getByLabel(t.dailyRate,{exact:true}).fill("100");await chooseCurrency("meals","PLN");await expect(form("meals").getByText(/100 PLN × 3 days × 2 travelers = 600.00 PLN/)).toBeVisible();await page.screenshot({path:testInfo.outputPath("inline-per-diem-two.png"),fullPage:true});await plan("transport").click();await expect(form("meals")).toHaveCount(0);await expect(form("transport").getByLabel(f.movements.amount,{exact:true})).toBeFocused();
  await form("transport").getByLabel(f.movements.amount,{exact:true}).fill("300");await chooseCurrency("transport","PLN");await save("transport");
  await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("combobox",{name:t.expenseType,exact:true})).toHaveCount(0);
  expect(sql(`select count(*) from finance_movements where studio_id='${studio}'`)).toBe("0");await expect(page.getByRole("button",{name:t.openPlan})).toContainText("25,000.00");await expect(page.locator('[data-trip-summary="variance"]')).toHaveText(t.variance+"—");await expect(row("travel").locator("[data-variance]")).toHaveText(t.variance+"—");
  await page.screenshot({path:testInfo.outputPath("inline-planned-fullhd-en-light.png"),fullPage:true});
  const hotelPlan=sql(`select id from finance_trip_entries where trip_id='${tripId}' and expense_type='accommodation' and kind='plan'`);
  await plan("accommodation").click();await expect(form("accommodation").getByLabel(f.movements.amount,{exact:true})).toHaveValue("1200");await form("accommodation").getByLabel(f.movements.amount,{exact:true}).fill("1250");await save("accommodation");await plan("accommodation").click();await form("accommodation").getByLabel(f.movements.amount,{exact:true}).fill("1200");await save("accommodation");
  expect(sql(`select amount from finance_trip_entries where id='${hotelPlan}'`)).toBe("1200");
  await plan("travel").click();await form("travel").getByLabel(f.movements.amount,{exact:true}).fill("999");await page.keyboard.press("Escape");await expect(form("travel")).toHaveCount(0);await expect(plan("travel")).toContainText("4,000.00");
  await plan("meals").click();await form("meals").getByRole("button",{name:/Travelers & days/}).click();await form("meals").getByRole("button",{name:"Trip admin",exact:true}).click();await expect(form("meals").getByText(/100 PLN × 3 days × 1 travelers = 300.00 PLN/)).toBeVisible();await page.keyboard.press("Escape");
  // B: studio tickets, employee hotel and taxi. Context supplies the type and plan.
  await actual("travel").click();await form("travel").getByLabel(f.movements.amount,{exact:true}).fill("3800");await plan("accommodation").click();await expect(form("travel")).toHaveCount(0);await expect(form("accommodation").getByLabel(f.movements.amount,{exact:true})).toHaveValue("1200");await actual("accommodation").click();await expect(form("accommodation").getByLabel(f.movements.amount,{exact:true})).toBeFocused();
  await chooseEmployee("accommodation");await expect(form("accommodation").getByRole("combobox",{name:t.whichPlan,exact:true})).toHaveCount(0);await form("accommodation").getByLabel(f.movements.amount,{exact:true}).fill("1100");await manualFx("accommodation");await actual("transport").click();await expect(form("accommodation")).toHaveCount(0);await expect(form("transport").getByLabel(f.movements.amount,{exact:true})).toBeFocused();
  const hotelActual=sql(`select id from finance_trip_entries where trip_id='${tripId}' and expense_type='accommodation' and kind='expense'`);
  expect(sql(`select commitment from finance_expected_items where id=(select expected_item_id from finance_trip_entries where id=(select plan_id from finance_trip_entries where id='${hotelActual}'))`)).toBe("cancelled");
  await chooseEmployee("transport");await form("transport").getByLabel(f.movements.amount,{exact:true}).fill("120");await manualFx("transport");await form("transport").getByRole("button",{name:t.moreOptions,exact:true}).click();await form("transport").getByLabel(t.customLabel,{exact:true}).fill("Taxi");await save("transport");
  await expect(page.getByRole("dialog")).toHaveCount(0);expect(sql(`select count(*) from finance_movements where studio_id='${studio}'`)).toBe("1");
  await page.screenshot({path:testInfo.outputPath("inline-plan-actual-fullhd-en-light.png"),fullPage:true});
  // C: summary, payer totals and the actionable reimbursement are all on the sheet.
  await expect(page.locator("#trip-settlements")).toContainText("1,220.00");await expect(page.getByText(t.employeePaid,{exact:false})).toContainText("12,200.00");
  for(const [label,amount] of [["Uber","85"],["Train","60"]]){await actual("transport").click();await chooseEmployee("transport");await chooseCurrency("transport","PLN");await form("transport").getByLabel(f.movements.amount,{exact:true}).fill(amount);await manualFx("transport");await form("transport").getByRole("button",{name:t.moreOptions,exact:true}).click();await form("transport").getByLabel(t.customLabel,{exact:true}).fill(label);await save("transport");}
  await row("transport").getByRole("button",{name:`${t.details} · ${t.types.transport}`,exact:true}).click();await expect(row("transport").getByText("Taxi",{exact:true})).toBeVisible();await expect(row("transport")).toContainText("265.00");await page.screenshot({path:testInfo.outputPath("inline-expanded-transport.png"),fullPage:true});
  // Human-facing actual edit retains the immutable receipt and reconciles its debt.
  await row("accommodation").getByRole("button",{name:`${t.details} · ${t.types.accommodation}`,exact:true}).click();await row("accommodation").getByRole("button",{name:`${f.edit} · ${t.types.accommodation} · ${t.actual}`,exact:true}).click();await form("accommodation").getByLabel(f.movements.amount,{exact:true}).fill("1080");await form("accommodation").getByLabel(t.reason,{exact:true}).fill("Receipt corrected");await save("accommodation");
  expect(sql(`select amount from finance_trip_entries where id='${hotelActual}'`)).toBe("1100");await expect(page.locator("#trip-settlements")).toContainText("1,345.00");
  await row("travel").getByRole("button",{name:`${t.details} · ${t.types.travel}`,exact:true}).click();await row("travel").getByRole("button",{name:`${f.edit} · ${t.types.travel} · ${t.actual}`,exact:true}).click();await form("travel").getByLabel(f.movements.amount,{exact:true}).fill("3700");await form("travel").getByLabel(t.reason,{exact:true}).fill("Ticket receipt corrected");await form("travel").getByRole("checkbox",{name:t.confirmPaymentUpdate,exact:true}).check();await save("travel");expect(sql(`select recorded_balance from finance_account_balances where id='${bank}'`)).toBe("-3700");
  // Multiple plans require a deliberate choice; plan removal remains a confirmation.
  await plan("visa").click();await form("visa").getByLabel(f.movements.amount,{exact:true}).fill("100");await save("visa");
  sql(`select set_config('request.jwt.claim.sub','${actors[0].id}',false);select record_finance_trip_entry('${studio}','${randomUUID()}','${tripId}',jsonb_build_object('kind','plan','expenseType','visa','amount','200','currency','UAH','date','2026-10-24'));`);await page.reload();await plan("visa").click();await expect(form("visa").getByLabel(f.movements.amount,{exact:true})).toBeFocused();await page.keyboard.press("Escape");
  await actual("visa").click();await form("visa").getByLabel(f.movements.amount,{exact:true}).fill("90");await page.getByRole("heading",{name:t.expenseSheet,exact:true}).click();await expect(form("visa")).toBeVisible();await expect(form("visa").getByRole("alert")).toContainText(t.errors.invalid);await form("visa").getByRole("combobox",{name:t.whichPlan,exact:true}).click();await page.getByRole("option",{name:/100 UAH/,exact:false}).click();await save("visa");
  await plan("other").click();await form("other").getByLabel(f.movements.amount,{exact:true}).fill("50");await save("other");await row("other").getByRole("button",{name:`${t.details} · ${t.types.other}`,exact:true}).click();await row("other").getByRole("button",{name:t.remove,exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:t.remove,exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(plan("other")).toHaveText(t.addPlan);
  for(const locale of ["en","uk"]){await page.context().addCookies([{name:"studioflow-locale",value:locale,domain:"127.0.0.1",path:"/"}]);for(const theme of ["light","dark"]){for(const [size,width,height] of [["fullhd",1920,1080],["2k",2560,1440],["mobile",390,844]] as const){await page.setViewportSize({width,height});await page.evaluate(value=>localStorage.setItem("studioflow-theme",value),theme);await page.goto(href);await expect(page.locator("html")).toHaveAttribute("data-theme",theme);await expect(page.locator('[data-expense-type="other"]')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath(`inline-${size}-${locale}-${theme}.png`),fullPage:true});}}}
  await page.emulateMedia({reducedMotion:"reduce"});await row("meals").locator("[data-plan-trigger]").click();await expect(form("meals").getByLabel(uk.Finance.trips.dailyRate,{exact:true})).toBeFocused();await page.screenshot({path:testInfo.outputPath("inline-per-diem-mobile-uk-dark.png"),fullPage:true});await page.keyboard.press("Escape");
});

test("manual trip, inline personal expense, advance, return and matching",async({page},testInfo)=>{
  const t=en.Finance.trips,f=en.Finance;
  await page.goto("/login");await page.locator('input[type="email"]').fill(actors[0].email);await page.locator('input[type="password"]').fill(actors[0].password);await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/\/dashboard/);await page.goto("/finance/trips");
  await page.getByRole("button",{name:t.addTrip,exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel(t.name,{exact:true}).fill("Manual inspection");await dialog.getByLabel(t.destination,{exact:true}).fill("Kyiv");await dialog.getByRole("combobox",{name:t.start,exact:true}).click();await dialog.getByRole("gridcell",{name:"20",exact:true}).click();await dialog.getByRole("combobox",{name:t.end,exact:true}).click();await dialog.getByRole("gridcell",{name:"21",exact:true}).click();await dialog.getByRole("checkbox",{name:"Trip employee",exact:true}).check();await dialog.getByRole("button",{name:f.planning.save,exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page).toHaveURL(/\/finance\/trips\/[\w-]+$/);const href=page.url();await expect(page.getByText(t.statuses.completed,{exact:true})).toBeVisible();await page.getByRole("button",{name:f.edit,exact:true}).click();await expect(dialog.getByRole("combobox",{name:t.status,exact:true})).toHaveCount(0);await dialog.getByRole("button",{name:f.close,exact:true}).click();
  const row=page.locator('[data-expense-type="travel"]'),form=row.locator("form");
  await row.getByRole("button",{name:`${t.actual} · ${t.types.travel}`,exact:true}).click();await form.getByRole("combobox",{name:t.paidBy,exact:true}).click();await page.getByRole("option",{name:"Trip employee",exact:true}).click();await form.getByLabel(f.movements.amount,{exact:true}).fill("18400");await page.getByRole("heading",{name:t.expenseSheet,exact:true}).click();await expect(form).toHaveCount(0);await expect(page.getByRole("button",{name:t.openPlan})).toHaveText(t.notPlanned);await page.screenshot({path:testInfo.outputPath("inline-actual-only.png"),fullPage:true});
  await page.getByRole("button",{name:t.issueAdvance,exact:true}).click();await dialog.getByLabel(f.movements.amount,{exact:true}).fill("20000");await dialog.getByRole("button",{name:f.planning.save,exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator("#trip-settlements")).toContainText("1,600.00");
  await page.getByRole("link",{name:t.recordReturn,exact:true}).click();await expect(dialog).toBeVisible();await dialog.getByRole("button",{name:f.movements.record,exact:true}).click();await expect(page).toHaveURL(href);await expect(page.getByText(t.nothingDue,{exact:true})).toBeVisible();
  const today=sql("select (now() at time zone 'Europe/Kyiv')::date");sql(`select set_config('request.jwt.claim.sub','${actors[0].id}',false);select record_finance_movement('${studio}','${randomUUID()}',jsonb_build_object('kind','outgoing','date','${today}','accountId','${bank}','amount','100','description','Matched ticket','categoryId',(select id from finance_categories where studio_id='${studio}' and default_key='business_travel')));`);
  await page.reload();await row.getByRole("button",{name:`${t.actual} · ${t.types.travel}`,exact:true}).click();await form.getByRole("button",{name:t.moreOptions,exact:true}).click();await form.getByRole("combobox",{name:t.payment,exact:true}).click();await page.getByRole("option",{name:t.matchPayment,exact:true}).click();await form.getByRole("combobox",{name:t.existingPayment,exact:true}).click();await page.getByRole("option",{name:/Matched ticket/}).click();await page.getByRole("heading",{name:t.expenseSheet,exact:true}).click();await expect(form).toHaveCount(0);
  await page.getByRole("button",{name:t.openPlan}).click();await expect(row.locator("[data-plan-trigger]")).toBeFocused();
  const meals=page.locator('[data-expense-type="meals"]'),mealForm=meals.locator("form");const cashBefore=sql(`select recorded_balance from finance_account_balances where id='${bank}'`);
  await meals.getByRole("button",{name:`${t.actual} · ${t.types.meals}`,exact:true}).click();await mealForm.getByRole("combobox",{name:t.paidBy,exact:true}).click();await page.getByRole("option",{name:"Trip employee",exact:true}).click();await mealForm.getByRole("button",{name:t.perDiem,exact:true}).click();await mealForm.getByLabel(t.dailyRate,{exact:true}).fill("800");await expect(mealForm.getByText(/800 UAH × 2 days × 1 travelers = 1600.00 UAH/)).toBeVisible();await page.screenshot({path:testInfo.outputPath("inline-actual-per-diem.png"),fullPage:true});await page.getByRole("heading",{name:t.expenseSheet,exact:true}).click();await expect(mealForm).toHaveCount(0);expect(sql(`select recorded_balance from finance_account_balances where id='${bank}'`)).toBe(cashBefore);await expect(page.locator("#trip-settlements")).toContainText("1,600.00");

});

test("employee cannot open trips", async ({ page }) => {
  await page.goto("/login"); await page.locator('input[type="email"]').fill(actors[1].email); await page.locator('input[type="password"]').fill(actors[1].password); await page.locator('button[type="submit"]').click(); await expect(page).toHaveURL(/\/dashboard/); await page.goto("/finance/trips"); await expect(page).toHaveURL(/\/dashboard/);
});
