import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import uk from "../../messages/uk.json";
import type { Database } from "../../src/types/database.types";

const local=z.object({EQUIPMENT_TEST_SUPABASE_URL:z.url(),EQUIPMENT_TEST_SERVICE_KEY:z.string()}).parse(process.env);
if(!["127.0.0.1","localhost"].includes(new URL(local.EQUIPMENT_TEST_SUPABASE_URL).hostname))throw new Error("Local Supabase required");
const client=createClient<Database>(local.EQUIPMENT_TEST_SUPABASE_URL,local.EQUIPMENT_TEST_SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const studio=randomUUID(),project=randomUUID(),account=randomUUID(),email=`proposal-${randomUUID()}@example.test`,password=`Proposal-${randomUUID()}`;
let actor="";
const sql=(statement:string)=>execFileSync("docker",["exec","-i","supabase_db_design-manager","psql","-U","postgres","-d","postgres","-v","ON_ERROR_STOP=1","-At"],{input:statement,encoding:"utf8"}).trim();
test.beforeAll(async()=>{
 await client.from("studios").insert({id:studio,name:"Proposal browser test"}).throwOnError();
 const created=await client.auth.admin.createUser({email,password,email_confirm:true});if(created.error)throw created.error;actor=created.data.user.id;
 await client.from("profiles").upsert({id:actor,email,full_name:"Proposal admin",system_role:"admin",is_active:true}).throwOnError();
 await client.from("studio_members").insert({studio_id:studio,user_id:actor,system_role:"admin"}).throwOnError();
 sql(`insert into finance_settings(studio_id,base_currency,cutover_date,created_by) values('${studio}','EUR','2026-09-01','${actor}');
 insert into finance_accounts(id,studio_id,name,currency,opening_balance,created_by) values('${account}','${studio}','Bank','EUR',0,'${actor}');
 select set_config('request.jwt.claim.sub','${actor}',false);select finalize_finance_setup('${studio}');
 insert into projects(id,studio_id,name,total_area_m2,start_date,created_by,status,client_name,city,site_address,country_code) values('${project}','${studio}','336 Стоматологічна клініка',100,'2026-09-01','${actor}','active','Олена Коваль','Київ','вул. Городецького, 12','UA');`);
});
test.afterAll(async()=>{
 sql(`begin;set local session_replication_role=replica;
 delete from finance_project_proposals where studio_id='${studio}';delete from finance_project_items where studio_id='${studio}';delete from finance_project_plan_revisions where studio_id='${studio}';delete from finance_project_terms where studio_id='${studio}';delete from finance_expected_items where studio_id='${studio}';delete from finance_planning_requests where studio_id='${studio}';delete from finance_accounts where studio_id='${studio}';delete from finance_categories where studio_id='${studio}';delete from finance_settings where studio_id='${studio}';delete from notifications where studio_id='${studio}';delete from project_activity where project_id='${project}';delete from project_task_stage_columns where project_id='${project}';delete from projects where studio_id='${studio}';delete from studio_members where studio_id='${studio}';delete from studios where id='${studio}';commit;`);
 if(actor){const result=await client.auth.admin.deleteUser(actor);if(result.error)throw result.error;}
});
test("Project Finance → proposal preview → immutable PDF and later revision",async({page},testInfo)=>{
 test.setTimeout(180000);const f=uk.Finance,b=f.builder,p=f.proposal;
 await page.goto('/login');await page.locator('input[type="email"]').fill(email);await page.locator('input[type="password"]').fill(password);await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/\/dashboard/);
 await page.context().addCookies([{name:'studioflow-locale',value:'uk',url:new URL(page.url()).origin}]);
 await page.goto(`/projects/${project}?view=finance`);await page.getByRole('button',{name:f.project.editAgreement,exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:b.perAreaShort,exact:true}).click();await dialog.getByLabel(b.rate,{exact:true}).fill('40');
 await dialog.getByRole('group',{name:b.vatRate}).getByRole('button',{name:'23%',exact:true}).click();
 await dialog.getByRole('button',{name:'30 / 50 / 20',exact:true}).click();
 await expect(dialog.locator('[data-plan-row]').nth(0).getByLabel(b.paymentName,{exact:true})).toHaveValue(b.planningStage);
 await expect(dialog.locator('[data-plan-row]').nth(1).getByLabel(b.paymentName,{exact:true})).toHaveValue(b.visualizationStage);
 await expect(dialog.locator('[data-plan-row]').nth(2).getByLabel(b.paymentName,{exact:true})).toHaveValue(b.documentationStage);
 await dialog.locator('[data-plan-row]').nth(0).getByLabel(b.clientNote,{exact:true}).fill('Оплата перед початком етапу.');
 await dialog.locator('[data-plan-row]').nth(0).getByLabel(b.paymentName,{exact:true}).fill('Індивідуальне планування');
 await dialog.getByRole('button',{name:'50 / 50',exact:true}).click();await expect(dialog.locator('[data-plan-row]').nth(0).getByLabel(b.paymentName,{exact:true})).toHaveValue('Індивідуальне планування');
 await dialog.getByRole('button',{name:'30 / 50 / 20',exact:true}).click();await dialog.locator('[data-plan-row]').nth(0).getByLabel(b.paymentName,{exact:true}).fill(b.planningStage);
 await dialog.getByRole('button',{name:f.planning.save,exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.reload();await page.getByRole('button',{name:f.project.editAgreement,exact:true}).click();
 await dialog.getByRole('button',{name:'50 / 50',exact:true}).click();await expect(dialog.locator('[data-plan-row]').nth(0).getByLabel(b.paymentName,{exact:true})).toHaveValue(b.advance);
 await dialog.getByRole('button',{name:'30 / 50 / 20',exact:true}).click();await expect(dialog.locator('[data-plan-row]').nth(1).getByLabel(b.paymentName,{exact:true})).toHaveValue(b.visualizationStage);
 await dialog.getByLabel(f.project.reason,{exact:true}).fill('Review template defaults');await dialog.getByRole('button',{name:b.saveRevision,exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('button',{name:p.action,exact:true}).click();
 await expect(dialog.getByLabel(p.client,{exact:true})).toHaveValue('Олена Коваль');await expect(dialog.getByLabel(p.address,{exact:true})).toHaveValue('Київ, вул. Городецького, 12');
 const note=dialog.getByLabel(p.intro,{exact:true}), initialNoteHeight=await note.evaluate(el=>el.getBoundingClientRect().height);
 await note.fill('Площа об’єкта попередня та може бути уточнена після обмірів.\n'.repeat(8));
 await expect.poll(()=>note.evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(initialNoteHeight);
 expect(await note.evaluate(el=>getComputedStyle(el).resize)).toBe('none');
 await note.fill('Площа об’єкта попередня та може бути уточнена після обмірів.');
 await dialog.getByLabel(p.website,{exact:true}).fill('https://space.example');
 await dialog.getByLabel(p.email,{exact:true}).fill('hello@space.example');
 await dialog.getByLabel(p.phone,{exact:true}).fill('+380 44 000 00 00');
 await dialog.getByLabel(p.businessAddress,{exact:true}).fill('Київ, вул. Городецького, 12');
 await dialog.getByRole('button',{name:p.saveContacts,exact:true}).click();
 await expect(dialog.getByText(p.contactsSaved,{exact:true})).toBeVisible();
 await expect(dialog.locator('[data-proposal-pages] canvas')).toBeVisible({timeout:60000});await expect(dialog.getByRole('button',{name:p.generate,exact:true})).toBeEnabled();
 await expect(dialog.locator('[data-proposal-pages]')).toContainText(/100\s+м²\s*×\s*49,2\s+EUR\s*\/\s*м²/);
 const previewPixels=await dialog.locator('[data-proposal-pages] canvas').evaluate((canvas:HTMLCanvasElement)=>canvas.toDataURL());
 for(const [label,width,height] of [['desktop',1440,1000],['notebook',1024,768],['wide-short',1440,720],['mobile',390,844]] as const){await page.setViewportSize({width,height});expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
 await expect.poll(()=>dialog.locator('[data-proposal-pages]').evaluate(el=>el.scrollWidth<=el.clientWidth && el.scrollHeight<=el.clientHeight)).toBe(true);
 const canvas=dialog.locator('[data-proposal-pages] canvas');
 await expect.poll(()=>canvas.evaluate(el=>{const parent=el.parentElement;if(!parent)return false;const c=el.getBoundingClientRect(),p=parent.getBoundingClientRect();return c.left>=p.left && c.right<=p.right && c.top>=p.top && c.bottom<=p.bottom;})).toBe(true);
 expect(await canvas.evaluate((el:HTMLCanvasElement)=>{const style=getComputedStyle(el);return Number.parseFloat(style.width)/Number.parseFloat(style.height);})).toBeCloseTo(210/297,2);
 await expect(dialog.locator('[data-proposal-pages]')).not.toContainText(/Сторінка\s*\d+\s*\/|Page\s*\d+\s*of/);
 await page.screenshot({path:testInfo.outputPath(`proposal-${label}.png`)});if(label==='mobile'){await dialog.locator('[data-proposal-pages]').scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath('proposal-mobile-preview.png')});}}
 await page.setViewportSize({width:1440,height:1000});
 await dialog.getByRole('button',{name:p.generate,exact:true}).click();await expect(dialog.getByText(p.saved,{exact:true})).toBeVisible({timeout:60000});
 await page.setViewportSize({width:390,height:844});await expect(dialog.locator('[data-proposal-pages] canvas')).toBeVisible({timeout:60000});await dialog.locator('[data-proposal-pages]').scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath('proposal-mobile-saved.png')});await page.setViewportSize({width:1440,height:1000});
 await expect.poll(()=>dialog.locator('[data-proposal-pages] canvas').evaluate((canvas:HTMLCanvasElement)=>canvas.toDataURL())).toBe(previewPixels);
 const href=await dialog.getByRole('link',{name:p.download,exact:true}).getAttribute('href');expect(href).toBeTruthy();
 const response=await page.request.get(href!);expect(response.headers()['content-type']).toBe('application/pdf');const original=await response.body();expect(original.subarray(0,5).toString()).toBe('%PDF-');
 const download=page.waitForEvent('download');await dialog.getByRole('link',{name:p.download,exact:true}).click();const pdf=await download;expect(pdf.suggestedFilename()).toBe('SPACE-336-r1.pdf');await pdf.saveAs(testInfo.outputPath('SPACE-336-r1.pdf'));
 expect(sql(`select snapshot->>'gross' from finance_project_proposals where project_id='${project}'`)).toBe('4920.00');
 expect(sql(`select snapshot->'rows'->0->>'gross' from finance_project_proposals where project_id='${project}'`)).toBe('1476.00');
 await dialog.getByRole('button',{name:p.close,exact:true}).last().click();
 await page.getByRole('button',{name:p.action,exact:true}).click();
 await expect(dialog.getByRole('button',{name:p.revision.replace('{number}','1'),exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(dialog.getByRole('link',{name:p.download,exact:true})).toBeVisible();
 expect(sql(`select count(*) from finance_project_proposals where project_id='${project}'`)).toBe('1');
 await expect(dialog.getByLabel(p.title,{exact:true})).toHaveCount(0);
 sql(`update projects set site_address='Нова адреса',client_name='Новий клієнт' where id='${project}';update finance_expected_items set description='Новий етап',client_note='Нова примітка' where studio_id='${studio}';`);
 const repeated=await page.request.get(href!);expect(await repeated.body()).toEqual(original);
 await dialog.getByRole('button',{name:p.newRevision,exact:true}).click();
 expect(sql(`select count(*) from finance_project_proposals where project_id='${project}'`)).toBe('1');
 await expect(dialog.getByLabel(p.website,{exact:true})).toHaveValue('https://space.example');
 await expect(dialog.getByLabel(p.email,{exact:true})).toHaveValue('hello@space.example');
 await expect(dialog.getByLabel(p.phone,{exact:true})).toHaveValue('+380 44 000 00 00');
 await expect(dialog.getByLabel(p.businessAddress,{exact:true})).toHaveValue('Київ, вул. Городецького, 12');
 await expect(dialog.getByLabel(p.client,{exact:true})).toHaveValue('Новий клієнт');
 await dialog.getByLabel(p.title,{exact:true}).fill('336 Стоматологічна клініка з навчальним центром та адміністративними приміщеннями');
 await expect(dialog.getByRole('button',{name:p.generate,exact:true})).toBeEnabled({timeout:60000});
 await dialog.getByRole('button',{name:p.generate,exact:true}).click();await expect(dialog.getByRole('link',{name:p.download,exact:true})).toBeVisible({timeout:60000});
 await expect(dialog.locator('[data-proposal-pages] canvas')).toBeVisible({timeout:60000});await page.screenshot({path:testInfo.outputPath('proposal-long-title.png')});
 const secondPdf=await page.request.get((await dialog.getByRole('link',{name:p.download,exact:true}).getAttribute('href'))!);
 const {writeFileSync}=await import('node:fs');writeFileSync(testInfo.outputPath('SPACE-336-r2.pdf'),await secondPdf.body());
 expect(sql(`select string_agg(snapshot->>'projectNumber',',' order by revision) from finance_project_proposals where project_id='${project}'`)).toBe('336,336');
 expect(sql(`select count(*) from finance_project_proposals where project_id='${project}'`)).toBe('2');
 await dialog.getByRole('button',{name:p.close,exact:true}).last().click();await page.getByRole('button',{name:p.action,exact:true}).click();
 await expect(dialog.getByRole('button',{name:p.revision.replace('{number}','2'),exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(dialog.getByRole('link',{name:p.download,exact:true})).toBeVisible();
 expect(sql(`select count(*) from finance_project_proposals where project_id='${project}'`)).toBe('2');
 sql(`update studios set email='changed@space.example' where id='${studio}';`);
 expect(await (await page.request.get(href!)).body()).toEqual(original);
 expect(sql(`select snapshot->'studioContactDetails'->>'email' from finance_project_proposals where project_id='${project}' and revision=1`)).toBe('hello@space.example');
});
