import Link from "next/link";
import { ArrowUpRight, CalendarDays } from "lucide-react";
import { getLocale, getTranslations } from "next-intl/server";
import { DashboardSection, MetricStrip, OperationalSurface } from "@/components/dashboard/dashboard-patterns";
import { DashboardTaskList } from "@/components/tasks/dashboard-task-list";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { getAdministrationData } from "@/data/queries/administration";
import { getDashboard } from "@/data/queries/dashboard";
import { getAdminDashboardMetrics, getDashboardDeadlineHref, getEmployeeDashboardMetrics } from "@/lib/dashboard-presentation";
import { formatAdministrationDateRange, type AdministrationModel } from "@/lib/administration";
import { getProjectLifecycleBadgeStyle } from "@/lib/semantic-styles";
import { formatDate } from "@/lib/utils";
import type { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> { const t = await getTranslations("Dashboard"); return { title: t("metadata") }; }

export default async function DashboardPage() {
  const [dashboard, t] = await Promise.all([getDashboard(), getTranslations("Dashboard")]);
  if (!dashboard) return <div className="space-y-8"><PageHeader title={t("title")} description={t("loginDescription")} /><EmptyState compact title={t("loginRequired")} /></div>;
  if (dashboard.kind === "employee") return <Employee dashboard={dashboard} />;
  return <Admin dashboard={dashboard} administration={await getAdministrationData()} />;
}

async function Employee({ dashboard }: { dashboard: Extract<Awaited<ReturnType<typeof getDashboard>>, { kind: "employee" }> }) {
  const [t, status, locale] = await Promise.all([getTranslations("Dashboard"), getTranslations("Status"), getLocale()]);
  return <div className="space-y-8"><PageHeader title={t("welcome")} description={t("employeeIntro")} /><MetricStrip metrics={getEmployeeDashboardMetrics(dashboard.metrics)} /><div className="grid items-start gap-6 lg:grid-cols-2"><DashboardSection title={t("needsAttention")} description={t("needsAttentionDescription")}><OperationalSurface>{dashboard.needsAttention.length ? <DashboardTaskList currentUserId={dashboard.profile.id} tasks={dashboard.needsAttention} needsAttentionOnly emptyState={{ title: t("emptyEmployeeAttention"), description: t("emptyEmployeeAttentionDescription"), linkHref: "/my-tasks", linkLabel: t("viewMyTasks") }} /> : <EmptyState compact title={t("emptyEmployeeAttention")} description={t("emptyEmployeeAttentionDescription")} action={<TextLink href="/my-tasks">{t("viewMyTasks")}</TextLink>} />}</OperationalSurface></DashboardSection><Deadlines deadlines={dashboard.deadlines} /></div><DashboardSection title={t("currentProjects")} description={t("projectsDescription")}><OperationalSurface>{dashboard.projects.length ? <ul className="divide-y divide-[var(--ui-border)]">{dashboard.projects.map((project) => { const badge = getProjectLifecycleBadgeStyle(project.status); return <li key={project.id}><Link href={`/projects/${project.id}`} className="grid min-h-16 gap-2 px-3 py-3 hover:bg-[var(--ui-surface-subtle)] sm:grid-cols-[1fr_auto]"><div><p className="font-medium">{project.name}</p><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-xs ${badge.className}`}>{status(project.status)}</span></div><div className="text-sm sm:text-right"><p className="ui-numeric">{project.progressPercent === null ? t("noTasksYet") : t("progress", { count: project.progressPercent })} · {t("openCount", { count: project.openTaskCount })}</p><p className="mt-1 text-xs text-[var(--ui-text-muted)]">{project.nearestDueDate ? t("nextDue", { date: formatDate(project.nearestDueDate, locale) }) : t("noPersonalDeadline")}</p></div></Link></li>; })}</ul> : <EmptyState compact title={t("emptyProjects")} />}</OperationalSurface></DashboardSection></div>;
}

async function Admin({ administration, dashboard }: { administration: Pick<AdministrationModel, "pendingRequests" | "upcomingAbsences"> | null; dashboard: Extract<Awaited<ReturnType<typeof getDashboard>>, { kind: "admin" }> }) {
  const t = await getTranslations("Dashboard");
  return <div className="space-y-8"><PageHeader title={t("welcome")} description={t("employeeIntro")} /><MetricStrip metrics={getAdminDashboardMetrics(dashboard.metrics)} /><div className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]"><div className="space-y-6"><DashboardSection title={t("attentionProjects")} description={t("attentionProjectsDescription")}><OperationalSurface>{dashboard.attentionProjects.length ? <ul className="divide-y divide-[var(--ui-border)]">{dashboard.attentionProjects.map((project) => <li key={project.id}><Link href={`/projects/${project.id}`} className="flex min-h-14 items-center justify-between gap-3 px-3 py-2.5 hover:bg-[var(--ui-surface-subtle)]"><div><p className="font-medium">{project.name}</p><p className="text-xs text-[var(--ui-text-muted)]">{[project.overdueCount ? t("reasonOverdue", { count: project.overdueCount }) : null, project.deadlineDaysAway === 0 ? t("reasonDeadlineToday") : project.deadlineDaysAway !== null ? t("reasonDeadlineDays", { count: project.deadlineDaysAway }) : null, project.urgentCount ? t("reasonUrgent", { count: project.urgentCount }) : null].filter(Boolean).join(" · ")}</p></div><ArrowUpRight className="size-4" aria-hidden="true" /></Link></li>)}</ul> : <EmptyState compact title={t("emptyAdminAttention")} />}</OperationalSurface></DashboardSection><DashboardSection title={t("myTasks")} description={t("myTasksDescription")}><OperationalSurface>{dashboard.myTasks.length ? <DashboardTaskList currentUserId={dashboard.profile.id} tasks={dashboard.myTasks} /> : <EmptyState compact title={t("emptyMyTasks")} />}</OperationalSurface></DashboardSection><DashboardSection title={t("teamWorkload")} description={t("teamWorkloadDescription")}><OperationalSurface>{dashboard.workload.length ? <ul className="divide-y divide-[var(--ui-border)]">{dashboard.workload.map((member) => <li key={member.id} className="flex justify-between gap-3 px-3 py-2.5"><span><b>{member.full_name}</b><small className="block text-[var(--ui-text-muted)]">{member.job_title}</small></span><span className="ui-numeric text-sm">{t("openCount", { count: member.openTaskCount })} · {t("reasonOverdue", { count: member.overdueCount })}</span></li>)}</ul> : <EmptyState compact title={t("emptyWorkload")} />}</OperationalSurface></DashboardSection></div><aside className="space-y-6"><Deadlines deadlines={dashboard.deadlines} />{administration?.upcomingAbsences.length ? <Availability absences={administration.upcomingAbsences} /> : null}{administration?.pendingRequests.length ? <DashboardSection title={t("pendingActions")}><OperationalSurface className="p-4"><p className="ui-numeric font-semibold">{t("pendingCount", { count: administration.pendingRequests.length })}</p><p className="text-sm text-[var(--ui-text-muted)]">{t("timeOffReview")}</p><TextLink href="/admin#requests">{t("review")}</TextLink></OperationalSurface></DashboardSection> : null}</aside></div></div>;
}

async function Availability({ absences }: { absences: AdministrationModel["upcomingAbsences"] }) { const [t, locale] = await Promise.all([getTranslations("Dashboard"), getLocale()]); return <DashboardSection title={t("upcomingAvailability")} description={t("upcomingAvailabilityDescription")}><OperationalSurface><ul>{absences.slice(0, 3).map((absence) => <li key={absence.id} className="px-3 py-2.5"><p className="font-medium">{absence.employeeName}</p><p className="text-xs text-[var(--ui-text-muted)]">{formatAdministrationDateRange(absence, locale)}</p></li>)}</ul><Button asChild size="sm" variant="ghost" className="m-2 min-h-11"><Link href="/calendar?timeOff=1"><CalendarDays className="size-4" aria-hidden="true" />{t("viewTeamCalendar")}</Link></Button></OperationalSurface></DashboardSection>; }

async function Deadlines({ deadlines }: { deadlines: Extract<Awaited<ReturnType<typeof getDashboard>>, { kind: "admin" | "employee" }>['deadlines'] }) { const [t, locale] = await Promise.all([getTranslations("Dashboard"), getLocale()]); return <DashboardSection title={t("deadlines")} description={t("deadlinesDescription")}><OperationalSurface>{deadlines.length ? <ul className="divide-y divide-[var(--ui-border)]">{deadlines.map((deadline) => <li key={`${deadline.kind}-${deadline.id}`}><Link href={getDashboardDeadlineHref(deadline)} className="flex min-h-14 items-center justify-between gap-3 px-3 py-2.5 hover:bg-[var(--ui-surface-subtle)]"><span><b>{deadline.title}</b><small className="block text-[var(--ui-text-muted)]">{deadline.kind === "task" ? `${t("task")} · ${deadline.project?.name}` : t("projectDeadline")}</small></span><time className="ui-numeric text-xs">{formatDate(deadline.dueDate, locale)}</time></Link></li>)}</ul> : <EmptyState compact title={t("emptyDeadlines")} />}</OperationalSurface></DashboardSection>; }

function TextLink({ children, href }: { children: React.ReactNode; href: string }) { return <Link href={href} className="mt-2 inline-flex min-h-11 items-center text-sm font-medium underline underline-offset-4">{children}</Link>; }
